// packages/vue/src/components/cell-item/CellItem.vue
<template>
  <div
    class="cu-cell-item"
    :class="{ 'is-disabled': disabled, 'no-border': noBorder }"
    @click="onClick"
  >
    <div class="cu-cell-item-body" :class="{ multilines: !!brief }">
      <div v-if="$slots.left" class="cu-cell-item-left">
        <slot name="left"></slot>
      </div>
      <div v-if="title || brief || $slots.default" class="cu-cell-item-content">
        <p v-if="title" class="cu-cell-item-title" v-text="title"></p>
        <p v-if="brief" class="cu-cell-item-brief" v-text="brief"></p>
        <slot></slot>
      </div>
      <div v-if="arrow || addon || $slots.right" class="cu-cell-item-right">
        <slot name="right">{{ addon }}</slot>
        <CuIcon v-if="arrow" name="arrow" size="md" />
      </div>
    </div>
    <div v-if="$slots.children" class="cu-cell-item-children">
      <slot name="children"></slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import CuIcon from '../icon/Icon.vue'

defineOptions({ name: 'cu-cell-item' })

const props = withDefaults(
  defineProps<{
    title?: string
    brief?: string
    addon?: string
    arrow?: boolean
    disabled?: boolean
    noBorder?: boolean
  }>(),
  {
    title: '',
    brief: '',
    addon: '',
    arrow: false,
    disabled: false,
    noBorder: false,
  },
)

const emit = defineEmits<{
  (e: 'click', event: MouseEvent): void
}>()

function onClick(e: MouseEvent) {
  if (!props.disabled) {
    emit('click', e)
  }
}
</script>

// packages/react/src/components/cell-item/CellItem.tsx
import { type MouseEvent, type ReactNode } from 'react'
import { CuIcon } from '../icon/Icon'

export interface CellItemProps {
  className?: string
  title?: string
  brief?: string
  addon?: string
  arrow?: boolean
  disabled?: boolean
  noBorder?: boolean
  left?: ReactNode
  right?: ReactNode
  children?: ReactNode
  childrenSlot?: ReactNode
  onClick?: (event: MouseEvent<HTMLDivElement>) => void
}

export function CuCellItem({
  className,
  title = '',
  brief = '',
  addon = '',
  arrow = false,
  disabled = false,
  noBorder = false,
  left,
  right,
  children,
  childrenSlot,
  onClick,
}: CellItemProps) {
  const hasContent = !!(title || brief || children)

  return (
    <div
      className={[
        'cu-cell-item',
        className,
        disabled ? 'is-disabled' : '',
        noBorder ? 'no-border' : '',
      ]
        .filter(Boolean)
        .join(' ')}
      onClick={event => {
        if (!disabled) {
          onClick?.(event)
        }
      }}
    >
      <div className={`cu-cell-item-body${brief ? ' multilines' : ''}`}>
        {left ? <div className="cu-cell-item-left">{left}</div> : null}
        {hasContent ? (
          <div className="cu-cell-item-content">
            {title ? <p className="cu-cell-item-title">{title}</p> : null}
            {brief ? <p className="cu-cell-item-brief">{brief}</p> : null}
            {children}
          </div>
        ) : null}
        {arrow || addon || right ? (
          <div className="cu-cell-item-right">
            {right ?? addon}
            {arrow ? <CuIcon name="arrow" size="md" /> : null}
          </div>
        ) : null}
      </div>
      {childrenSlot ? <div className="cu-cell-item-children">{childrenSlot}</div> : null}
    </div>
  )
}
