// packages/react/src/components/switch/Switch.tsx
import { type MouseEvent } from 'react'

export interface SwitchProps {
  value?: boolean
  disabled?: boolean
  onChange?: (value: boolean, event: MouseEvent<HTMLDivElement>) => void
}

export function MdSwitch({ value = false, disabled = false, onChange }: SwitchProps) {
  return (
    <div
      className={`md-switch${disabled ? ' disabled' : ''}${value ? ' active' : ''}`}
      onClick={event => {
        if (disabled) {
          return
        }
        onChange?.(!value, event)
      }}
    ></div>
  )
}

// packages/vue/src/components/switch/Switch.vue
<template>
  <div
    class="md-switch"
    :class="[disabled ? 'disabled' : '', modelValue ? 'active' : '']"
    @click="onChange($event)"
  ></div>
</template>

<script setup lang="ts">
defineOptions({ name: 'md-switch' })

const props = withDefaults(
  defineProps<{
    modelValue?: boolean
    disabled?: boolean
  }>(),
  {
    modelValue: false,
    disabled: false,
  },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
  (e: 'change', event: MouseEvent): void
}>()

function onChange(event: MouseEvent) {
  if (props.disabled) {
    return
  }
  emit('update:modelValue', !props.modelValue)
  emit('change', event)
}
</script>
