// docs/src/components/demos/button/index.vue
<script setup lang="ts">
import { MdButton } from 'mand-mobile'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['默认', '主要', '禁用', '圆角', '朴素警告', '加载', '行内']
const code = `<MdButton type="primary" round>主要按钮</MdButton>
<MdButton type="warning" plain disabled>次要按钮</MdButton>`
</script>

<template>
  <DemoCanvas mode="stage" :scenes="scenes" :code="code">
    <template #scene-0>
      <MdButton type="default">默认按钮</MdButton>
    </template>
    <template #scene-1>
      <MdButton type="primary">主要按钮</MdButton>
    </template>
    <template #scene-2>
      <MdButton type="primary" disabled>主要按钮</MdButton>
      <MdButton type="default" disabled>默认按钮</MdButton>
    </template>
    <template #scene-3>
      <MdButton type="primary" round>主要按钮</MdButton>
    </template>
    <template #scene-4>
      <MdButton type="warning" plain>次要按钮</MdButton>
    </template>
    <template #scene-5>
      <MdButton type="primary" loading>加载中</MdButton>
      <MdButton type="default" loading>加载中</MdButton>
    </template>
    <template #scene-6>
      <MdButton type="primary" inline round>行内按钮</MdButton>
    </template>
  </DemoCanvas>
</template>

// docs/src/components/demos-react/button/index.tsx
import { MdButton } from 'mand-mobile-react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['默认', '主要', '禁用', '圆角', '朴素警告', '加载']
const code = `<MdButton type="primary" round>主要按钮</MdButton>
<MdButton type="warning" plain disabled>次要按钮</MdButton>`

export default function ButtonDemo() {
  return (
    <DemoCanvasReact mode="stage" scenes={scenes} code={code}>
      {active => {
        if (active === 0) return <MdButton>默认按钮</MdButton>
        if (active === 1) return <MdButton type="primary">主要按钮</MdButton>
        if (active === 2)
          return (
            <>
              <MdButton type="primary" disabled>主要按钮</MdButton>
              <MdButton disabled>默认按钮</MdButton>
            </>
          )
        if (active === 3) return <MdButton type="primary" round>主要按钮</MdButton>
        if (active === 4) return <MdButton type="warning" plain>次要按钮</MdButton>
        return <MdButton type="primary" loading>加载中</MdButton>
      }}
    </DemoCanvasReact>
  )
}
