// docs/src/components/demos-react/switch/index.tsx
import { useState } from 'react'
import { MdSwitch } from 'mand-mobile-react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['开启', '关闭', '开启不可用', '关闭不可用']
const code = `<MdSwitch value={v} onChange={setV} />`

export default function SwitchDemo() {
  const [on, setOn] = useState(true)
  const [off, setOff] = useState(false)
  const [onDisabled] = useState(true)
  const [offDisabled] = useState(false)

  return (
    <DemoCanvasReact mode="stage" scenes={scenes} code={code}>
      {active => {
        if (active === 0) return <MdSwitch value={on} onChange={setOn} />
        if (active === 1) return <MdSwitch value={off} onChange={setOff} />
        if (active === 2) return <MdSwitch value={onDisabled} disabled />
        return <MdSwitch value={offDisabled} disabled />
      }}
    </DemoCanvasReact>
  )
}

// docs/src/components/demos/switch/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { MdSwitch } from 'mand-mobile'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['开启', '关闭', '开启不可用', '关闭不可用']
const code = `<MdSwitch v-model="isActive" />`
const on = ref(true)
const off = ref(false)
const onDisabled = ref(true)
const offDisabled = ref(false)
</script>

<template>
  <DemoCanvas mode="stage" :scenes="scenes" :code="code">
    <template #scene-0><MdSwitch v-model="on" /></template>
    <template #scene-1><MdSwitch v-model="off" /></template>
    <template #scene-2><MdSwitch v-model="onDisabled" disabled /></template>
    <template #scene-3><MdSwitch v-model="offDisabled" disabled /></template>
  </DemoCanvas>
</template>
