// docs/src/components/demos-react/license-plate/index.tsx
import { useState } from 'react'
import { CuLicensePlate } from '@centui/react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['车牌输入', '半弹层版']
const code = `<CuLicensePlate defaultValue={dv} onConfirm={onConfirm} />`

export default function LicensePlateDemo() {
  const [result, setResult] = useState('')

  return (
    <DemoCanvasReact mode="stage" scenes={scenes} code={code}>
      {() => (
        <div className="license-plate-demo">
          <CuLicensePlate defaultValue="浙AD12345" onConfirm={v => setResult(v)} />
          {result ? <p className="license-plate-demo-result">{result}</p> : null}
        </div>
      )}
    </DemoCanvasReact>
  )
}

// docs/src/components/demos/license-plate/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { CuLicensePlate } from 'centui'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['车牌输入', '半弹层版']
const code = `<CuLicensePlate :default-value="defaultValue" @confirm="onConfirm" />`
const result = ref('')
function onConfirm(value: string) {
  result.value = value
}
</script>

<template>
  <DemoCanvas mode="stage" :scenes="scenes" :code="code">
    <template #scene-0>
      <div class="license-plate-demo">
        <CuLicensePlate :default-value="'浙AD12345'" @confirm="onConfirm" />
        <p v-if="result" class="license-plate-demo-result">{{ result }}</p>
      </div>
    </template>
  </DemoCanvas>
</template>
