// packages/react/src/components/textarea-item/TextareaItem.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  type FocusEvent as ReactFocusEvent,
  type KeyboardEvent as ReactKeyboardEvent,
} from 'react'
import { CuFieldItem } from '../field-item/FieldItem'
import { CuIcon } from '../icon/Icon'
import { getCursorsPosition, setCursorsPosition } from '../input-item/cursor'

export interface TextareaItemProps {
  title?: string
  name?: string | number
  placeholder?: string
  value?: string
  maxLength?: string | number
  maxHeight?: string | number
  solid?: boolean
  readonly?: boolean
  disabled?: boolean
  clearable?: boolean
  rows?: string | number
  autosize?: boolean
  error?: string
  formation?: (
    name: string | number,
    value: string,
    pos: number,
  ) => { value: string; range: number } | undefined
  onChange?: (value: string) => void
  onFocus?: () => void
  onBlur?: () => void
  onKeyup?: (event: ReactKeyboardEvent<HTMLTextAreaElement>) => void
  onKeydown?: (event: ReactKeyboardEvent<HTMLTextAreaElement>) => void
}

export interface TextareaItemExposed {
  resizeTextarea: () => void
  focus: () => void
  blur: () => void
  getValue: () => string
}

export const CuTextareaItem = forwardRef<TextareaItemExposed, TextareaItemProps>(function CuTextareaItem(
  {
    title = '',
    name = `textarea-item-${Math.floor(Math.random() * 10000)}`,
    placeholder = '',
    value = '',
    maxLength = '',
    maxHeight = '',
    solid = true,
    readonly = false,
    disabled = false,
    clearable = false,
    rows = '3',
    autosize = false,
    error = '',
    formation,
    onChange,
    onFocus,
    onBlur,
    onKeyup,
    onKeydown,
  },
  ref,
) {
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const [inputValue, setInputValue] = useState(value)
  const [isInputFocus, setIsInputFocus] = useState(false)
  const maxHeightRef = useRef(maxHeight)

  const isInputEmpty = !inputValue.length
  const errorInfo = error

  // v2 watch value：外部值同步 + 重新计算高度
  useEffect(() => {
    if (value !== inputValue) {
      setInputValue(value)
      setTimeout(() => resizeTextareaRef.current(), 0)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value])

  useEffect(() => {
    resizeTextareaRef.current()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const resizeTextareaRef = useRef<() => void>(() => {})

  useImperativeHandle(ref, () => ({
    resizeTextarea: () => resizeTextareaRef.current(),
    focus: () => {
      textareaRef.current?.focus()
      setTimeout(() => setIsInputFocus(true), 200)
    },
    blur: () => {
      textareaRef.current?.blur()
      setIsInputFocus(false)
    },
    getValue: () => inputValue,
  }))

  function formatValue(curValue: string, curPos = 0) {
    const customValue = formation?.(name, curValue, curPos)
    if (customValue) {
      return customValue
    }
    return { value: curValue, range: curPos }
  }

  function onInput(event: ReactFocusEvent<HTMLTextAreaElement> & { target: HTMLTextAreaElement }) {
    const target = event.target
    const formated = formatValue(target.value, getCursorsPosition(target))
    setInputValue(formated.value)
    setTimeout(() => {
      setCursorsPosition(target, formated.range)
      resizeTextareaRef.current()
    }, 0)
  }

  function calcTextareaHeight(el: HTMLTextAreaElement) {
    // 触发重绘
    el.style.height = 'auto'
    let scrollHeight = el.scrollHeight
    if (scrollHeight === 0) {
      return
    }
    const max = Number(maxHeightRef.current)
    if (maxHeightRef.current && scrollHeight > max) {
      scrollHeight = max
    }
    el.style.height = `${scrollHeight}px`
  }

  resizeTextareaRef.current = () => {
    if (autosize) {
      calcTextareaHeight(textareaRef.current!)
    }
  }

  return (
    <CuFieldItem
      className={`cu-textarea-item${disabled ? ' is-disabled' : ''}${errorInfo ? ' is-error' : ''}`}
      title={title}
      solid={solid}
      // v2.7.0 契约：clear 不参与渲染时右插槽整体不出现
      right={
        clearable && !disabled && !readonly ? (
          <div
            className="cu-textarea-item__clear"
            style={{ display: !isInputEmpty && isInputFocus ? '' : 'none' }}
            onClick={() => {
              setInputValue('')
              onChange?.('')
              setTimeout(() => resizeTextareaRef.current(), 0)
              textareaRef.current?.focus()
              setTimeout(() => setIsInputFocus(true), 200)
            }}
          >
            <CuIcon name="clear"></CuIcon>
          </div>
        ) : undefined
      }
      childrenSlot={
        errorInfo ? (
          <div className="cu-textarea-item-msg">
            <p>{errorInfo}</p>
          </div>
        ) : undefined
      }
    >
      <textarea
        ref={textareaRef}
        className="cu-textarea-item__textarea"
        disabled={disabled}
        readOnly={readonly}
        {...({ maxlength: maxLength === '' ? '' : Number(maxLength) } as object)}
        placeholder={placeholder}
        rows={typeof rows === 'string' ? Number(rows) : rows}
        value={inputValue}
        onChange={(event) => {
          onInput(event as unknown as ReactFocusEvent<HTMLTextAreaElement> & { target: HTMLTextAreaElement })
          onChange?.(event.target.value)
        }}
        onFocus={() => {
          setIsInputFocus(true)
          onFocus?.()
        }}
        onBlur={() => {
          setTimeout(() => {
            setIsInputFocus(false)
            onBlur?.()
          }, 100)
        }}
        onKeyUp={(e) => onKeyup?.(e)}
        onKeyDown={(e) => onKeydown?.(e)}
      ></textarea>
    </CuFieldItem>
  )
})

// packages/vue/src/components/textarea-item/TextareaItem.vue
<template>
  <CuFieldItem
    class="cu-textarea-item"
    :class="[isDisabled ? 'is-disabled' : '', errorInfo ? 'is-error' : '']"
    :title="title"
    :solid="solid"
  >
    <textarea
      ref="textarea"
      v-model="inputValue"
      class="cu-textarea-item__textarea"
      :disabled="isDisabled"
      :readonly="readonly"
      :maxlength="maxLength"
      :placeholder="placeholder"
      :rows="rows"
      @input="onInput"
      @focus="onFocus"
      @blur="onBlur"
      @keyup="onKeyup"
      @keydown="onKeydown"
    ></textarea>
    <slot name="footer"></slot>
    <template #right>
      <div
        v-if="clearable && !isDisabled && !readonly"
        v-show="!isInputEmpty && isInputFocus"
        class="cu-textarea-item__clear"
        @click="clearInput"
      >
        <CuIcon name="clear"></CuIcon>
      </div>
      <slot name="right"></slot>
    </template>
    <template #children>
      <div v-if="errorInfo" class="cu-textarea-item-msg">
        <p>{{ errorInfo }}</p>
      </div>
    </template>
  </CuFieldItem>
</template>

<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import CuFieldItem from '../field-item/FieldItem.vue'
import CuIcon from '../icon/Icon.vue'
import { getCursorsPosition, setCursorsPosition } from '../input-item/cursor'

defineOptions({ name: 'cu-textarea-item' })

const props = withDefaults(
  defineProps<{
    title?: string
    name?: string | number
    placeholder?: string
    value?: string
    maxLength?: string | number
    maxHeight?: string | number
    solid?: boolean
    readonly?: boolean
    disabled?: boolean
    clearable?: boolean
    rows?: string | number
    autosize?: boolean
    error?: string
    formation?: (name: string | number, value: string, pos: number) => { value: string; range: number } | undefined
  }>(),
  {
    title: '',
    name: () => `textarea-item-${Math.floor(Math.random() * 10000)}`,
    placeholder: '',
    value: '',
    maxLength: '',
    maxHeight: '',
    solid: true,
    readonly: false,
    disabled: false,
    clearable: false,
    rows: '3',
    autosize: false,
    error: '',
    formation: undefined,
  },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
  (e: 'change', value: string): void
  (e: 'input', value: string): void
  (e: 'focus'): void
  (e: 'blur'): void
  (e: 'keyup', event: KeyboardEvent): void
  (e: 'keydown', event: KeyboardEvent): void
}>()

const maxHeightInner = ref<string | number>(props.maxHeight)
const inputValue = ref(props.value)
const isInputFocus = ref(false)
const textarea = ref<HTMLTextAreaElement>()

const isDisabled = computed(() => props.disabled)
const errorInfo = computed(() => props.error)
const isInputEmpty = computed(() => !inputValue.value.length)

watch(
  () => props.value,
  (val) => {
    inputValue.value = val
    nextTick(() => {
      resizeTextarea()
    })
  },
)
watch(inputValue, (val) => {
  emit('update:modelValue', val)
  emit('change', val)
})
watch(
  () => props.maxHeight,
  (val) => {
    maxHeightInner.value = val
    resizeTextarea()
  },
)

onMounted(() => {
  resizeTextarea()
})

function onInput(event: Event) {
  const target = event.target as HTMLTextAreaElement
  const formatedValue = formatValue(target.value, getCursorsPosition(target))

  inputValue.value = formatedValue.value

  nextTick(() => {
    setCursorsPosition(target, formatedValue.range)
    resizeTextarea()
  })
}

function formatValue(curValue: string, curPos = 0) {
  // 自定义格式化
  const customValue = props.formation?.(props.name, curValue, curPos)

  if (customValue) {
    return customValue
  }

  // 无格式化
  return { value: curValue, range: curPos }
}

function clearInput() {
  inputValue.value = ''
  nextTick(() => {
    resizeTextarea()
  })
  focus()
}

function onKeyup(event: KeyboardEvent) {
  emit('keyup', event)
}
function onKeydown(event: KeyboardEvent) {
  emit('keydown', event)
}
function onFocus() {
  isInputFocus.value = true
  emit('focus')
}
function onBlur() {
  setTimeout(() => {
    isInputFocus.value = false
    emit('blur')
  }, 100)
}

function calcTextareaHeight(el: HTMLTextAreaElement) {
  // 触发重绘
  el.style.height = 'auto'

  let scrollHeight = el.scrollHeight
  // 不可见时跳过高度计算
  if (scrollHeight === 0) {
    return
  }

  if (maxHeightInner.value && scrollHeight > Number(maxHeightInner.value)) {
    scrollHeight = Number(maxHeightInner.value)
  }

  el.style.height = scrollHeight + 'px'
}

// MARK: public methods
function resizeTextarea() {
  if (props.autosize) {
    calcTextareaHeight(textarea.value!)
  }
}

function focus() {
  textarea.value?.focus()
  setTimeout(() => {
    isInputFocus.value = true
  }, 200)
}

function blur() {
  textarea.value?.blur()
  isInputFocus.value = false
}

function getValue() {
  return inputValue.value
}

defineExpose({ resizeTextarea, focus, blur, getValue })
</script>
