// packages/vue/src/components/image-viewer/ImageViewer.vue
<template>
  <div v-show="isViewerShow" class="md-image-viewer" @click="onViewerClick">
    <div class="viewer-container">
      <MdSwiper
        v-if="isViewerShow"
        ref="swiper"
        :autoplay="0"
        :default-index="currentImgIndex"
        :has-dots="false"
        :is-prevent="false"
        @after-change="afterChange"
      >
        <MdSwiperItem
          v-for="(item, index) in imgs"
          :key="index"
          class="viewer-item-wrap"
        >
          <div class="item">
            <img v-if="item.url" :src="item.url" :alt="item.alt" />
          </div>
        </MdSwiperItem>
      </MdSwiper>
      <div v-if="hasDots" class="viewer-index">{{ currentImgIndex + 1 }}/{{ list.length }}</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { nextTick, ref, watch } from 'vue'
import MdSwiper from '../swiper/Swiper.vue'
import MdSwiperItem from '../swiper/SwiperItem.vue'

defineOptions({ name: 'md-image-viewer' })

export interface ImageViewerItem {
  url?: string
  alt?: string
  cls?: string
}

const props = withDefaults(
  defineProps<{
    modelValue?: boolean
    list?: Array<string | ImageViewerItem>
    initialIndex?: number
    hasDots?: boolean
  }>(),
  { modelValue: false, list: () => [], initialIndex: 0, hasDots: true },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
  (e: 'change', fromIndex: number, toIndex: number): void
}>()

const isViewerShow = ref(false)
const imgs = ref<Array<ImageViewerItem>>([])
const currentImgIndex = ref(0)

// v2 mounted：初始显隐；initialIndex 在挂载即打开时同样生效
isViewerShow.value = props.modelValue
if (isViewerShow.value) {
  currentImgIndex.value = props.initialIndex
  imgsInit()
}

watch(
  () => props.modelValue,
  (val) => {
    currentImgIndex.value = props.initialIndex
    isViewerShow.value = val
    nextTick(() => {
      imgsInit()
    })
  },
)
watch(isViewerShow, (val) => {
  emit('update:modelValue', val)
})

function imgsInit() {
  imgs.value = props.list.map(item => (typeof item === 'object' ? item : { url: item }))
}

function afterChange(fromIndex: number, toIndex: number) {
  currentImgIndex.value = toIndex
  emit('change', fromIndex, toIndex)
}

function onViewerClick() {
  isViewerShow.value = false
}
</script>

// packages/react/src/components/image-viewer/ImageViewer.tsx
import { forwardRef, useEffect, useRef, useState } from 'react'
import { MdSwiper, MdSwiperItem, type SwiperExposed } from '../swiper/Swiper'

export interface ImageViewerItem {
  url?: string
  alt?: string
  cls?: string
}

export interface ImageViewerProps {
  value?: boolean
  list?: Array<string | ImageViewerItem>
  initialIndex?: number
  hasDots?: boolean
  onChange?: (fromIndex: number, toIndex: number) => void
}

export const MdImageViewer = forwardRef<HTMLDivElement, ImageViewerProps>(function MdImageViewer(
  { value = false, list = [], initialIndex = 0, hasDots = true, onChange },
  ref,
) {
  const [isViewerShow, setIsViewerShow] = useState(value)
  const [imgs, setImgs] = useState<Array<ImageViewerItem>>(() =>
    list.map(item => (typeof item === 'object' ? item : { url: item })),
  )
  const [currentImgIndex, setCurrentImgIndex] = useState(() => (value ? initialIndex : 0))
  const swiperRef = useRef<SwiperExposed | null>(null)
  void swiperRef

  // v2 watch value：打开时重置位置并归一化列表
  const prevValueRef = useRef(value)
  const listRef = useRef(list)
  listRef.current = list
  useEffect(() => {
    if (prevValueRef.current !== value) {
      prevValueRef.current = value
      setCurrentImgIndex(initialIndex)
      setIsViewerShow(value)
      setImgs(listRef.current.map(item => (typeof item === 'object' ? item : { url: item })))
    }
  }, [value, initialIndex])

  return (
    <div
      className="md-image-viewer"
      ref={ref}
      style={{ display: isViewerShow ? '' : 'none' }}
      onClick={() => {
        setIsViewerShow(false)
      }}
    >
      <div className="viewer-container">
        {isViewerShow ? (
          <MdSwiper
            autoplay={0}
            defaultIndex={currentImgIndex}
            hasDots={false}
            isPrevent={false}
            onAfterChange={(from, to) => {
              setCurrentImgIndex(to)
              onChange?.(from, to)
            }}
          >
            {imgs.map((item, index) => (
              <MdSwiperItem key={index} className={`viewer-item-wrap${item.cls ? ` ${item.cls}` : ''}`}>
                <div className="item">{item.url ? <img src={item.url} alt={item.alt} /> : null}</div>
              </MdSwiperItem>
            ))}
          </MdSwiper>
        ) : null}
        {hasDots ? (
          <div className="viewer-index">
            {currentImgIndex + 1}/{list.length}
          </div>
        ) : null}
      </div>
    </div>
  )
})
