// docs/src/components/demos-react/activity-indicator/index.tsx
import { MdActivityIndicator } from 'mand-mobile-react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['roller', 'spinner', 'carousel']
const code = `<MdActivityIndicator type="roller" />
<MdActivityIndicator type="spinner" />
<MdActivityIndicator type="carousel" />`

export default function ActivityIndicatorDemo() {
  return (
    <DemoCanvasReact mode="stage" scenes={scenes} code={code}>
      {active => (
        <div style={{ minHeight: 80, display: 'flex', alignItems: 'center', gap: 24 }}>
          <MdActivityIndicator
            type={active === 0 ? 'roller' : active === 1 ? 'spinner' : 'carousel'}
          />
          {active === 0 ? <span>加载中...</span> : null}
        </div>
      )}
    </DemoCanvasReact>
  )
}

// docs/src/components/demos/activity-indicator/index.vue
<script setup lang="ts">
import { MdActivityIndicator } from 'mand-mobile'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['样式', '带文案', '纵向排列']
const code = `<MdActivityIndicator type="roller" />
<MdActivityIndicator type="spinner" />
<MdActivityIndicator type="carousel" />
<MdActivityIndicator :size="40">加载中...</MdActivityIndicator>`
</script>

<template>
  <DemoCanvas mode="stage" :scenes="scenes" :code="code">
    <template #scene-0>
      <div class="ai-row">
        <MdActivityIndicator type="roller" />
        <MdActivityIndicator type="spinner" />
        <MdActivityIndicator type="carousel" />
      </div>
      <div class="ai-row">
        <MdActivityIndicator type="roller" :size="40" />
        <MdActivityIndicator type="spinner" :size="40" color="#2F86F6" />
        <MdActivityIndicator type="carousel" :size="40" />
      </div>
    </template>
    <template #scene-1>
      <div class="ai-row">
        <MdActivityIndicator :text-size="14">加载中...</MdActivityIndicator>
        <MdActivityIndicator type="spinner" :text-size="14">提交中，请稍候</MdActivityIndicator>
      </div>
    </template>
    <template #scene-2>
      <div class="ai-row">
        <MdActivityIndicator vertical :size="30">加载中...</MdActivityIndicator>
      </div>
    </template>
  </DemoCanvas>
</template>

<style scoped>
.ai-row {
  display: flex;
  align-items: center;
  gap: 24px;
  padding: 16px 12px;
}
</style>
