// docs/src/components/demos-react/popup/index.tsx
import { useState } from 'react'
import { MdPopup, MdPopupTitleBar, MdButton } from 'mand-mobile-react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['底部弹层', '居中弹层']
const code = `<MdPopup v-model="show" position="bottom">
  <MdPopupTitleBar title="标题" only-close />
</MdPopup>`

export default function PopupDemo() {
  const [bottom, setBottom] = useState(false)
  const [center, setCenter] = useState(false)
  return (
    <DemoCanvasReact mode="phone" scenes={scenes} code={code}>
      {active => (
        <div style={{ padding: 16, display: 'flex', gap: 12 }}>
          {active === 0 ? (
            <MdButton size="small" inline onClick={() => setBottom(true)}>底部弹层</MdButton>
          ) : (
            <MdButton size="small" inline onClick={() => setCenter(true)}>居中弹层</MdButton>
          )}
          <MdPopup value={bottom} position="bottom" onChange={setBottom}>
            <div style={{ background: '#fff' }}>
              <MdPopupTitleBar title="底部弹层" only-close onCancel={() => setBottom(false)} />
              <p style={{ padding: 40, textAlign: 'center' }}>弹层内容</p>
            </div>
          </MdPopup>
          <MdPopup value={center} onChange={setCenter}>
            <div style={{ background: '#fff', padding: 32, borderRadius: 8 }} onClick={() => setCenter(false)}>
              居中弹层，点击关闭
            </div>
          </MdPopup>
        </div>
      )}
    </DemoCanvasReact>
  )
}

// docs/src/components/demos/popup/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { MdPopup, MdButton } from 'mand-mobile'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['居中弹层', '底部弹层', '无遮罩']
const center = ref(false)
const bottom = ref(false)
const plain = ref(false)
const code = `<MdPopup v-model="center" position="center">
  <div class="demo-box">居中内容</div>
</MdPopup>
<MdPopup v-model="bottom" position="bottom">
  <div class="demo-box">底部内容</div>
</MdPopup>`
</script>

<template>
  <DemoCanvas mode="phone" :scenes="scenes" :code="code">
    <template #scene-0>
      <div class="ctr-pad">
        <MdButton type="primary" round @click="center = true">打开居中弹层</MdButton>
      </div>
      <MdPopup v-model="center" position="center">
        <div style="padding: 24px 40px; border-radius: 10px; text-align: center; background: #fff">
          <div style="margin-bottom: 8px">居中弹层内容</div>
          <MdButton size="small" @click="center = false">关闭</MdButton>
        </div>
      </MdPopup>
    </template>
    <template #scene-1>
      <div class="phone-pad">
        <MdButton type="primary" round @click="bottom = true">打开底部弹层</MdButton>
      </div>
      <MdPopup v-model="bottom" position="bottom">
        <div class="sheet">
          <div class="sheet-title">底部弹层</div>
          <div class="sheet-content">内容区域</div>
          <MdButton type="primary" round block @click="bottom = false">知道了</MdButton>
        </div>
      </MdPopup>
    </template>
    <template #scene-2>
      <div class="phone-pad">
        <MdButton type="default" round @click="plain = true">无遮罩弹层</MdButton>
      </div>
      <MdPopup v-model="plain" position="bottom" :has-mask="false">
        <div class="sheet">
          <div class="sheet-title">无遮罩，点击背景不关闭</div>
          <MdButton type="default" round block @click="plain = false">关闭</MdButton>
        </div>
      </MdPopup>
    </template>
  </DemoCanvas>
</template>

<style scoped>
.phone-pad {
  padding: 12px;
  display: flex;
  justify-content: center;
}
.sheet {
  padding: 16px 16px 24px;
  background: #fff;
  border-radius: 12px 12px 0 0;
  text-align: center;
}
.sheet-title {
  font-size: 15px;
  font-weight: 600;
  margin-bottom: 10px;
}
.sheet-content {
  padding: 20px 0;
  color: #999;
  font-size: 13px;
}
</style>
