// packages/vue/src/components/tip/TipContent.vue
<template>
  <div class="cu-tip" :class="wrapperCls">
    <div class="cu-tip-content">
      <template v-if="!$slots.default">
        <CuIcon v-if="icon" class="content-icon" :name="icon" :svg="iconSvg" />
        <div class="content-text" v-text="content"></div>
      </template>
      <template v-else>
        <slot></slot>
      </template>
      <CuIcon v-if="closable" name="close" size="md" @click="onClose" />
    </div>
    <div class="cu-tip-bg"></div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import CuIcon from '../icon/Icon.vue'

defineOptions({ name: 'cu-tip-content' })

const props = withDefaults(
  defineProps<{
    /** top | left | bottom | right */
    placement?: string
    closable?: boolean
    icon?: string
    iconSvg?: boolean
    content?: string | number
    name?: string | number
  }>(),
  {
    placement: 'top',
    closable: true,
    icon: undefined,
    iconSvg: false,
    content: '',
    name: undefined,
  },
)

const emit = defineEmits<{
  (e: 'close'): void
}>()

const wrapperCls = computed(() => ({
  'has-close': props.closable,
  [`is-${props.placement}`]: ['left', 'bottom', 'right'].includes(props.placement as string),
  [String(props.name)]: !!props.name,
}))

function onClose() {
  emit('close')
}
</script>

// packages/react/src/components/tip/TipContent.tsx
import type { ReactNode } from 'react'
import { CuIcon } from '../icon/Icon'

export interface TipContentProps {
  /** top | left | bottom | right */
  placement?: string
  closable?: boolean
  icon?: string
  iconSvg?: boolean
  content?: string | number
  name?: string | number
  children?: ReactNode
  onClose?: () => void
}

export function CuTipContent({
  placement = 'top',
  closable = true,
  icon,
  iconSvg = false,
  content = '',
  name,
  children,
  onClose,
}: TipContentProps) {
  const wrapperCls = [
    'cu-tip',
    closable ? 'has-close' : '',
    ['left', 'bottom', 'right'].includes(placement ?? '') ? `is-${placement}` : '',
    name ? String(name) : '',
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div className={wrapperCls}>
      <div className="cu-tip-content">
        {children ?? (
          <>
            {icon ? <CuIcon className="content-icon" name={icon} svg={iconSvg} /> : null}
            <div className="content-text">{content}</div>
          </>
        )}
        {closable ? <CuIcon name="close" size="md" onClick={() => onClose?.()} /> : null}
      </div>
      <div className="cu-tip-bg"></div>
    </div>
  )
}
