// docs/src/components/demos-react/steps/index.tsx
import { useState } from 'react'
import { MdSteps } from 'mand-mobile-react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['横向', '带描述', '纵向']
const code = `<MdSteps steps={steps} current={1} />
<MdSteps steps={stepsWithDesc} current={2} />
<MdSteps steps={steps} current={1} direction="vertical" />`
const steps = [{ name: '第一步' }, { name: '第二步' }, { name: '第三步' }]
const stepsWithDesc = [
  { name: '下单', text: '2016-12-12' },
  { name: '付款', text: '2016-12-13' },
  { name: '发货', text: '2016-12-14' },
]

export default function StepsDemo() {
  const [current] = useState(1)
  return (
    <DemoCanvasReact mode="stage" scenes={scenes} code={code}>
      {active => {
        if (active === 0) return <div className="steps-demo-box"><MdSteps steps={steps} current={current} /></div>
        if (active === 1) return <div className="steps-demo-box"><MdSteps steps={stepsWithDesc} current={2} /></div>
        return <div className="steps-demo-box"><MdSteps steps={steps} current={1} direction="vertical" /></div>
      }}
    </DemoCanvasReact>
  )
}

// docs/src/components/demos/steps/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { MdSteps } from 'mand-mobile'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['横向', '带描述', '纵向']
const code = `<MdSteps :steps="steps" :current="1" />
<div class="steps-demo-box"><MdSteps :steps="stepsWithDesc" :current="2" /></div>
<div class="steps-demo-box"><MdSteps :steps="steps" :current="1" direction="vertical" /></div>`
const steps = [{ name: '第一步' }, { name: '第二步' }, { name: '第三步' }]
const stepsWithDesc = [
  { name: '下单', text: '2016-12-12' },
  { name: '付款', text: '2016-12-13' },
  { name: '发货', text: '2016-12-14' },
]
const current = ref(1)
</script>

<template>
  <DemoCanvas mode="stage" :scenes="scenes" :code="code">
    <template #scene-0>
      <div class="steps-demo-box"><MdSteps :steps="steps" :current="current" /></div>
    </template>
    <template #scene-1>
      <div class="steps-demo-box"><MdSteps :steps="stepsWithDesc" :current="2" /></div>
    </template>
    <template #scene-2>
      <div class="steps-demo-box"><MdSteps :steps="steps" :current="1" direction="vertical" /></div>
    </template>
  </DemoCanvas>
</template>
