// packages/react/src/components/result-page/ResultPage.tsx
import { forwardRef, type MouseEvent, type ReactNode } from 'react'
import { MdButton } from '../button/Button'

export interface ResultPageButton {
  text?: string
  type?: string
  plain?: boolean
  round?: boolean
  inactive?: boolean
  loading?: boolean
  icon?: string
  iconSvg?: boolean
  handler?: (event: MouseEvent<HTMLButtonElement>) => void
}

export interface ResultPageProps {
  /** empty | network | lost 等内置类型（决定默认图与默认文案） */
  type?: string
  imgUrl?: string
  text?: string
  subtext?: string
  buttons?: ResultPageButton[]
  children?: ReactNode
}

const IMG_PRE = '//manhattan.didistatic.com/static/manhattan/mand-mobile/result-page/2.1/'

const DEFAULT_TEXT: Record<string, string> = {
  // 网络连接异常
  network: '网络连接异常',
  // 暂无信息
  empty: '暂无信息',
}

const DEFAULT_SUBTEXT: Record<string, string> = {
  // 您要访问的页面已丢失
  lost: '您要访问的页面已丢失',
}

export const MdResultPage = forwardRef<HTMLDivElement, ResultPageProps>(function MdResultPage(
  { type = 'empty', imgUrl = '', text = '', subtext = '', buttons = [], children },
  ref,
) {
  const actualImgUrl = imgUrl || `${IMG_PRE}${type}.png`
  const actualText = text || DEFAULT_TEXT[type] || ''
  const actualSubtext = subtext || DEFAULT_SUBTEXT[type] || ''

  return (
    <div className="md-result" ref={ref}>
      <div className="md-result-image">
        <img src={actualImgUrl} className={!imgUrl ? type : ''} />
      </div>
      {actualText ? <div className="md-result-text">{actualText}</div> : null}
      {actualSubtext ? <div className="md-result-subtext">{actualSubtext}</div> : null}
      {buttons.length ? (
        <div className="md-result-buttons">
          {buttons.map((button, index) => (
            <MdButton
              key={index}
              type={button.type}
              plain={button.plain === undefined || button.plain}
              round={button.round}
              inactive={button.inactive}
              loading={button.loading}
              icon={button.icon}
              iconSvg={button.iconSvg}
              size="small"
              inline
              onClick={(event) => button.handler?.(event)}
            >
              {button.text}
            </MdButton>
          ))}
        </div>
      ) : null}
      {children}
    </div>
  )
})

// packages/vue/src/components/result-page/ResultPage.vue
<template>
  <div class="md-result">
    <div class="md-result-image">
      <img :src="actualImgUrl" :class="!imgUrl && type" />
    </div>
    <div v-if="actualText" class="md-result-text">{{ actualText }}</div>
    <div v-if="actualSubText" class="md-result-subtext">{{ actualSubText }}</div>
    <div v-if="buttons.length" class="md-result-buttons">
      <MdButton
        v-for="(button, index) of buttons"
        :key="index"
        :type="button.type"
        :plain="button.plain === undefined || button.plain"
        :round="button.round"
        :inactive="button.inactive"
        :loading="button.loading"
        :icon="button.icon"
        :icon-svg="button.iconSvg"
        size="small"
        inline
        @click="button.handler?.()"
      >
        {{ button.text }}
      </MdButton>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { t } from '@mand-mobile/core'
import MdButton from '../button/Button.vue'

defineOptions({ name: 'md-result-page' })

export interface ResultPageButton {
  text?: string
  type?: string
  plain?: boolean
  round?: boolean
  inactive?: boolean
  loading?: boolean
  icon?: string
  iconSvg?: boolean
  handler?: () => void
}

const props = withDefaults(
  defineProps<{
    /** empty | network | lost 等内置类型（决定默认图与默认文案） */
    type?: string
    imgUrl?: string
    text?: string
    subtext?: string
    buttons?: ResultPageButton[]
  }>(),
  { type: 'empty', imgUrl: '', text: '', subtext: '', buttons: () => [] },
)

const actualImgUrl = computed(() => {
  const pre = '//manhattan.didistatic.com/static/manhattan/mand-mobile/result-page/2.1/'
  return props.imgUrl || `${pre}${props.type}.png`
})

const actualText = computed(
  () =>
    props.text ||
    {
      // 网络连接异常
      network: t('md.result_page.networkError'),
      // 暂无信息
      empty: t('md.result_page.noInformation'),
    }[props.type as 'network' | 'empty'] ||
    '',
)

const actualSubText = computed(
  () =>
    props.subtext ||
    {
      // 您要访问的页面已丢失
      lost: t('md.result_page.lostWay'),
    }[props.type as 'lost'] ||
    '',
)
</script>
