// docs/src/components/demos/tag/index.vue
<script setup lang="ts">
import { MdTag } from 'mand-mobile'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['圆角', '半圆', '线框', '阳文', '特殊标签']
const code = `<MdTag size="small" shape="circle" type="fill" fill-color="#FC7353">特惠</MdTag>
<MdTag size="large" shape="fillet" type="fill" font-color="#FF5B60">逾期23天</MdTag>
<MdTag shape="coupon" fill-color="#FC9153">免息券70.1</MdTag>`
</script>

<template>
  <DemoCanvas mode="stage" :scenes="scenes" :code="code">
    <template #scene-0>
      <div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap">
        <MdTag size="tiny" shape="circle" type="fill" fill-color="#FC7353" font-color="#000" />
        <MdTag size="small" shape="circle" type="fill" fill-color="#FC7353" font-color="#fff">特惠</MdTag>
        <MdTag size="large" shape="circle" type="fill" fill-color="#FC7353" font-color="#fff">返5000</MdTag>
        <MdTag size="small" shape="circle" type="ghost" font-color="#FC7353">特惠</MdTag>
        <MdTag size="small" shape="circle" sharp="bottom-left" type="fill" fill-color="linear-gradient(90deg, #FC7353 0%, #FC9153 100%)" font-color="#fff">续保3折起</MdTag>
      </div>
    </template>
    <template #scene-1>
      <div style="display: flex; gap: 12px; align-items: center">
        <MdTag size="large" shape="fillet" type="fill" fill-color="rgba(255, 91, 96, .1)" font-weight="normal" font-color="#FF5B60">逾期23天</MdTag>
        <MdTag size="large" shape="fillet" type="ghost" font-color="#FF5B60">逾期23天</MdTag>
      </div>
    </template>
    <template #scene-2>
      <div style="display: flex; gap: 12px; align-items: center">
        <MdTag size="large" shape="square" font-color="#FF8843" type="ghost">可选</MdTag>
        <MdTag size="small" shape="square" font-color="#28AA91" type="ghost">可选</MdTag>
      </div>
    </template>
    <template #scene-3>
      <div style="display: flex; gap: 12px; align-items: center">
        <MdTag size="large" shape="square" fill-color="rgba(0,0,0,0)" type="fill" font-weight="bolder" font-color="#333">￥3600</MdTag>
        <MdTag size="small" shape="square" fill-color="rgba(0,0,0,0)" type="fill" font-weight="bolder" font-color="#333">￥300</MdTag>
      </div>
    </template>
    <template #scene-4>
      <div style="display: flex; gap: 20px; align-items: center">
        <MdTag size="large" shape="coupon" fill-color="#FC9153" type="fill" font-color="#fff">免息券70.1</MdTag>
        <MdTag size="large" shape="quarter" fill-color="#FC9153" type="fill" font-color="#fff">免息券</MdTag>
      </div>
    </template>
  </DemoCanvas>
</template>

// docs/src/components/demos-react/tag/index.tsx
import { MdTag } from 'mand-mobile-react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['圆角', '半圆', '线框', '阳文', '特殊标签']
const code = `<MdTag size="small" shape="circle" type="fill" fillColor="#FC7353" fontColor="#fff">特惠</MdTag>
<MdTag size="large" shape="fillet" type="fill" fontColor="#FF5B60">逾期23天</MdTag>
<MdTag shape="coupon" fillColor="#FC9153">免息券70.1</MdTag>`

export default function TagDemo() {
  return (
    <DemoCanvasReact mode="stage" scenes={scenes} code={code}>
      {active => {
        if (active === 0)
          return (
            <div style={{ display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap' }}>
              <MdTag size="tiny" shape="circle" type="fill" fillColor="#FC7353" fontColor="#000" />
              <MdTag size="small" shape="circle" type="fill" fillColor="#FC7353" fontColor="#fff">特惠</MdTag>
              <MdTag size="large" shape="circle" type="fill" fillColor="#FC7353" fontColor="#fff">返5000</MdTag>
              <MdTag size="small" shape="circle" type="ghost" fontColor="#FC7353">特惠</MdTag>
              <MdTag size="small" shape="circle" sharp="bottom-left" type="fill" fillColor="linear-gradient(90deg, #FC7353 0%, #FC9153 100%)" fontColor="#fff">续保3折起</MdTag>
            </div>
          )
        if (active === 1)
          return (
            <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
              <MdTag size="large" shape="fillet" type="fill" fillColor="rgba(255, 91, 96, .1)" fontWeight="normal" fontColor="#FF5B60">逾期23天</MdTag>
              <MdTag size="large" shape="fillet" type="ghost" fontColor="#FF5B60">逾期23天</MdTag>
            </div>
          )
        if (active === 2)
          return (
            <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
              <MdTag size="large" shape="square" fontColor="#FF8843" type="ghost">可选</MdTag>
              <MdTag size="small" shape="square" fontColor="#28AA91" type="ghost">可选</MdTag>
            </div>
          )
        if (active === 3)
          return (
            <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
              <MdTag size="large" shape="square" fillColor="rgba(0,0,0,0)" type="fill" fontWeight="bolder" fontColor="#333">￥3600</MdTag>
              <MdTag size="small" shape="square" fillColor="rgba(0,0,0,0)" type="fill" fontWeight="bolder" fontColor="#333">￥300</MdTag>
            </div>
          )
        return (
          <div style={{ display: 'flex', gap: 20, alignItems: 'center' }}>
            <MdTag size="large" shape="coupon" fillColor="#FC9153" type="fill" fontColor="#fff">免息券70.1</MdTag>
            <MdTag size="large" shape="quarter" fillColor="#FC9153" type="fill" fontColor="#fff">免息券</MdTag>
          </div>
        )
      }}
    </DemoCanvasReact>
  )
}
