// docs/src/components/demos/dialog/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { MdDialog, Dialog, MdButton, type DialogBtn } from 'mand-mobile'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['基础', '竖排布局', '单例模式', '带图标']
const show1 = ref(false)
const show2 = ref(false)
const show3 = ref(false)
const btnClose: DialogBtn = { text: '取消', handler: () => (show1.value = false) }
const btnOk: DialogBtn = { text: '确定', warning: true, handler: () => (show1.value = false) }
const btnClose2: DialogBtn = { text: '取消', handler: () => (show2.value = false) }
const btnOk2: DialogBtn = { text: '确定', handler: () => (show2.value = false) }
const btnOk3: DialogBtn = { text: '知道了', handler: () => (show3.value = false) }
const code = `<MdDialog v-model="show" title="温馨提示" content="是否确认删除该条记录？" :btns="btns" />
<MdDialog v-model="show" title="删除确认" content="删除后将无法恢复" layout="column" :btns="btns" />`
</script>

<template>
  <DemoCanvas mode="phone" :scenes="scenes" :code="code">
    <template #scene-0>
      <div class="btn-col">
        <MdButton type="primary" @click="show1 = true">传统对话</MdButton>
        <MdButton type="warning" @click="show3 = true">单按钮</MdButton>
      </div>
      <MdDialog v-model="show1" title="确认操作" content="确定要删除该条记录吗？此操作不可恢复" :btns="[btnClose, btnOk]" />
      <MdDialog v-model="show3" title="提示" content="内容更新成功" :btns="[btnOk3]" />
    </template>
    <template #scene-1>
      <div class="btn-col">
        <MdButton type="primary" @click="show2 = true">竖排布局</MdButton>
      </div>
      <MdDialog v-model="show2" title="删除确认" content="删除后将无法恢复，是否继续？" layout="column" :btns="[btnOk2, btnClose2]" />
    </template>
    <template #scene-3>
      <div style="display: flex; gap: 12px; justify-content: center">
        <MdButton @click="Dialog.alert({ title: '警告', content: '警告弹窗', confirmText: '知道了' })">警告弹窗</MdButton>
        <MdButton @click="Dialog.confirm({ title: '确认', content: '确认弹窗' })">确认弹窗</MdButton>
        <MdButton @click="Dialog.succeed({ title: '成功', content: '操作成功' })">成功弹窗</MdButton>
        <MdButton @click="Dialog.failed({ title: '失败', content: '操作失败' })">失败弹窗</MdButton>
      </div>
    </template>
    <template #scene-2>
      <div class="btn-col">
        <MdButton type="primary" @click="show3 = true">带图标的对话框</MdButton>
      </div>
      <MdDialog v-model="show3" icon="success-color" icon-svg title="支付成功" content="您的订单已完成支付" :btns="[btnOk3]" />
    </template>
  </DemoCanvas>
</template>

<style scoped>
.btn-col {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 16px;
}
</style>

// docs/src/components/demos-react/dialog/index.tsx
import { useState } from 'react'
import { MdButton, MdDialog, Dialog } from 'mand-mobile-react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['确认对话框', '警告对话框', '成功/失败', '单例模式']
const code = `Dialog.confirm({ title: '确认', onConfirm })
Dialog.succeed({ title: '成功', content: '操作成功' })
MdDialog 组件式用法见右图`

export default function DialogDemo() {
  const [show, setShow] = useState(false)
  const [iconShow, setIconShow] = useState(false)

  return (
    <DemoCanvasReact mode="phone" scenes={scenes} code={code}>
      {active => (
        <div style={{ padding: 16, display: 'flex', gap: 12, flexWrap: 'wrap' }}>
          {active === 0 ? (
            <>
              <MdButton size="small" inline onClick={() => setShow(true)}>组件式对话框</MdButton>
              <MdButton
                size="small"
                inline
                onClick={() =>
                  Dialog.confirm({ title: '警告', content: '确认删除该项？', onConfirm: () => setShow(false) })
                }
              >
                命令式 confirm
              </MdButton>
              <MdDialog
                value={show}
                title="对话框"
                content="这是一个 React 对话框"
                btns={[
                  { text: '取消', handler: () => setShow(false) },
                  { text: '确定', warning: true, handler: () => setShow(false) },
                ]}
                onChange={setShow}
              />
            </>
          ) : active === 1 ? (
            <MdButton
              size="small"
              inline
              onClick={() =>
                Dialog.alert({ title: '警告', content: '警告弹窗', confirmText: '知道了' })
              }
            >
              警告弹窗
            </MdButton>
          ) : active === 2 ? (
            <>
              <MdButton size="small" inline onClick={() => setIconShow(true)}>成功弹窗</MdButton>
              <MdDialog
                value={iconShow}
                icon="success-color"
                iconSvg
                title="支付成功"
                content="您的订单已完成支付"
                btns={[{ text: '知道了', handler: () => setIconShow(false) }]}
                onChange={setIconShow}
              />
            </>
          ) : (
            <>
              <MdButton size="small" inline onClick={() => Dialog.succeed({ title: '成功', content: '操作成功' })}>
                成功弹窗
              </MdButton>
              <MdButton size="small" inline onClick={() => Dialog.failed({ title: '失败', content: '操作失败' })}>
                失败弹窗
              </MdButton>
            </>
          )}
        </div>
      )}
    </DemoCanvasReact>
  )
}
