// packages/vue/src/components/activity-indicator/ActivityIndicator.vue
<template>
  <div class="md-activity-indicator" :class="type">
    <div class="indicator-container" :class="{ vertical }">
      <div class="indicator-loading">
        <template v-if="type === 'roller'">
          <MdRoller :size="size" :color="color" :width="width"></MdRoller>
        </template>
        <template v-else-if="type === 'spinner'">
          <MdSpinning :size="size" :color="color"></MdSpinning>
        </template>
        <template v-else-if="type === 'carousel'">
          <MdCarousel :size="size" :color="color"></MdCarousel>
        </template>
      </div>
      <div
        v-if="$slots.default"
        :style="{ fontSize: `${textSize}px`, color: textColor }"
        class="md-activity-indicator-text indicator-text"
      >
        <slot></slot>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import MdRoller from './Roller.vue'
import MdSpinning from './Spinning.vue'
import MdCarousel from './Carousel.vue'

defineOptions({ name: 'md-activity-indicator' })

const props = withDefaults(
  defineProps<{
    /** roller | spinner | carousel */
    type?: string
    size?: number
    width?: number
    color?: string
    textColor?: string
    textSize?: number
    vertical?: boolean
  }>(),
  {
    type: 'roller',
    size: 70,
    width: undefined,
    color: undefined,
    textColor: '#999',
    textSize: undefined,
    vertical: false,
  },
)

const color = computed(() => props.color ?? (props.type === 'spinner' ? 'dark' : '#2F86F6'))
</script>

// packages/react/src/components/activity-indicator/ActivityIndicator.tsx
import type { ReactNode, HTMLAttributes } from 'react'
import { MdRoller } from './Roller'
import { MdSpinning } from './Spinning'
import { MdCarousel } from './Carousel'

export type ActivityIndicatorProps = {
  /** roller | spinner | carousel */
  type?: string
  size?: number
  width?: number
  color?: string
  textColor?: string
  textSize?: number
  vertical?: boolean
  children?: ReactNode
  /** v2 场景遗留：text 作为透传 attr（VTU propsData 行为） */
  text?: string
} & HTMLAttributes<HTMLDivElement>

export function MdActivityIndicator({
  type = 'roller',
  size = 70,
  width,
  color,
  textColor = '#999',
  textSize,
  vertical = false,
  children,
  ...rest
}: ActivityIndicatorProps) {
  const resolvedColor = color ?? (type === 'spinner' ? 'dark' : '#2F86F6')

  return (
    <div className={`md-activity-indicator ${type}`} {...rest}>
      <div className={`indicator-container${vertical ? ' vertical' : ''}`}>
        <div className="indicator-loading">
          {type === 'roller' ? (
            <MdRoller size={size} color={resolvedColor} width={width} />
          ) : type === 'spinner' ? (
            <MdSpinning size={size} color={resolvedColor} />
          ) : type === 'carousel' ? (
            <MdCarousel size={size} color={resolvedColor} />
          ) : null}
        </div>
        {children ? (
          <div
            className="md-activity-indicator-text indicator-text"
            style={{ fontSize: `${textSize}px`, color: textColor }}
          >
            {children}
          </div>
        ) : null}
      </div>
    </div>
  )
}

export { MdRoller, type RollerProps } from './Roller'
export { MdSpinning, type SpinningProps } from './Spinning'
export { MdCarousel, MdCarouselCircle } from './Carousel'
