// docs/src/components/demos/image-reader/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { MdImageReader } from 'mand-mobile'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['文件选择']
const code = `<MdImageReader @select="onSelect" @complete="onComplete" @error="onError" />`
const msg = ref('')
function onSelect(name: string, d: { files: File[] }) {
  msg.value = `已选择 ${d.files.length} 个文件`
}
function onError(name: string, d: { code: string; msg: string }) {
  msg.value = `错误 ${d.code}: ${d.msg}`
}
</script>

<template>
  <DemoCanvas mode="stage" :scenes="scenes" :code="code">
    <template #scene-0>
      <div class="image-reader-demo">
        <div class="image-reader-demo-box">
          <MdImageReader @select="onSelect" @error="onError" />
          <span class="image-reader-demo-tip">点击选择图片</span>
        </div>
        <p v-if="msg" class="image-reader-demo-msg">{{ msg }}</p>
      </div>
    </template>
  </DemoCanvas>
</template>

// docs/src/components/demos-react/image-reader/index.tsx
import { useState } from 'react'
import { MdImageReader } from 'mand-mobile-react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['文件选择']
const code = `<MdImageReader onSelect={onSelect} onError={onError} />`

export default function ImageReaderDemo() {
  const [msg, setMsg] = useState('')

  return (
    <DemoCanvasReact mode="stage" scenes={scenes} code={code}>
      {() => (
        <div className="image-reader-demo">
          <div className="image-reader-demo-box">
            <MdImageReader
              onSelect={(n, d) => setMsg(`已选择 ${d.files.length} 个文件`)}
              onError={(n, d) => setMsg(`错误 ${d.code}: ${d.msg}`)}
            />
            <span className="image-reader-demo-tip">点击选择图片</span>
          </div>
          {msg ? <p className="image-reader-demo-msg">{msg}</p> : null}
        </div>
      )}
    </DemoCanvasReact>
  )
}
