// docs/src/components/demos-react/swiper/index.tsx
import { MdSwiper, MdSwiperItem } from 'mand-mobile-react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['自动轮播', '手动滑动', '竖向滑动', '淡入淡出', '无指示器']
const code = `<MdSwiper autoplay={3000}>
  <MdSwiperItem>轮播 1</MdSwiperItem>
  <MdSwiperItem>轮播 2</MdSwiperItem>
  <MdSwiperItem>轮播 3</MdSwiperItem>
</MdSwiper>
<MdSwiper transition="slideY" autoplay={3000}>...</MdSwiper>
<MdSwiper transition="fade" autoplay={3000}>...</MdSwiper>`
const colors = ['#5C6B77', '#2F86F6', '#FF7A45']

function slides(prefix: string) {
  return colors.map((c, i) => (
    <MdSwiperItem key={i}>
      <div className="swiper-demo-item" style={{ background: c }}>
        {prefix} {i + 1}
      </div>
    </MdSwiperItem>
  ))
}

export default function SwiperDemo() {
  return (
    <DemoCanvasReact
      mode="stage"
      scenes={scenes}
      code={code}
    >
      {active => {
        if (active === 0) return <div className="swiper-demo-box"><MdSwiper autoplay={3000}>{slides('轮播')}</MdSwiper></div>
        if (active === 1) return <div className="swiper-demo-box"><MdSwiper autoplay={0}>{slides('拖我试试')}</MdSwiper></div>
        if (active === 2) return <div className="swiper-demo-box"><MdSwiper transition="slideY" autoplay={3000}>{slides('竖向')}</MdSwiper></div>
        if (active === 3) return <div className="swiper-demo-box"><MdSwiper transition="fade" autoplay={3000}>{slides('淡入淡出')}</MdSwiper></div>
        return <div className="swiper-demo-box"><MdSwiper autoplay={3000} hasDots={false}>{slides('无指示器')}</MdSwiper></div>
      }}
    </DemoCanvasReact>
  )
}

// docs/src/components/demos/swiper/index.vue
<script setup lang="ts">
import { MdSwiper, MdSwiperItem } from 'mand-mobile'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['自动轮播', '手动滑动', '竖向滑动', '淡入淡出', '无指示器']
const code = `<MdSwiper :autoplay="3000">
  <MdSwiperItem>轮播 1</MdSwiperItem>
  <MdSwiperItem>轮播 2</MdSwiperItem>
  <MdSwiperItem>轮播 3</MdSwiperItem>
</MdSwiper>
<MdSwiper transition="slideY" :autoplay="3000">...</MdSwiper>
<MdSwiper transition="fade" :autoplay="3000">...</MdSwiper>`
const colors = ['#5C6B77', '#2F86F6', '#FF7A45']
</script>

<template>
  <DemoCanvas mode="stage" :scenes="scenes" :code="code">
    <template #scene-0>
      <MdSwiper class="swiper-demo-box" :autoplay="3000">
        <MdSwiperItem v-for="(c, i) in colors" :key="i">
          <div class="swiper-demo-item" :style="{ background: c }">轮播 {{ i + 1 }}</div>
        </MdSwiperItem>
      </MdSwiper>
    </template>
    <template #scene-1>
      <MdSwiper class="swiper-demo-box" :autoplay="0">
        <MdSwiperItem v-for="(c, i) in colors" :key="i">
          <div class="swiper-demo-item" :style="{ background: c }">拖我试试 {{ i + 1 }}</div>
        </MdSwiperItem>
      </MdSwiper>
    </template>
    <template #scene-2>
      <MdSwiper class="swiper-demo-box" transition="slideY" :autoplay="3000">
        <MdSwiperItem v-for="(c, i) in colors" :key="i">
          <div class="swiper-demo-item" :style="{ background: c }">竖向 {{ i + 1 }}</div>
        </MdSwiperItem>
      </MdSwiper>
    </template>
    <template #scene-3>
      <MdSwiper class="swiper-demo-box" transition="fade" :autoplay="3000">
        <MdSwiperItem v-for="(c, i) in colors" :key="i">
          <div class="swiper-demo-item" :style="{ background: c }">淡入淡出 {{ i + 1 }}</div>
        </MdSwiperItem>
      </MdSwiper>
    </template>
    <template #scene-4>
      <MdSwiper class="swiper-demo-box" :autoplay="3000" :has-dots="false">
        <MdSwiperItem v-for="(c, i) in colors" :key="i">
          <div class="swiper-demo-item" :style="{ background: c }">无指示器 {{ i + 1 }}</div>
        </MdSwiperItem>
      </MdSwiper>
    </template>
  </DemoCanvas>
</template>
