// packages/vue/src/components/check/CheckList.vue
<template>
  <MdCheckGroup
    ref="group"
    class="md-check-list"
    :class="{ 'is-align-center': alignCenter }"
    :model-value="modelValue"
    @update:model-value="onInput"
  >
    <MdCellItem
      v-for="(item, index) in options"
      :key="index"
      class="md-check-item"
      :class="{
        'is-checked': modelValue.indexOf(item.value) !== -1,
      }"
      :title="hasSlot ? '' : item.text || item.label"
      :brief="hasSlot ? '' : item.brief"
      :disabled="item.disabled"
      @click="check(item)"
    >
      <template v-if="hasSlot">
        <slot :option="item" :index="index" :selected="modelValue.indexOf(item.value) > -1"></slot>
      </template>
      <template v-if="!alignCenter" #[iconSlotName]>
        <MdCheck
          :name="item.value"
          :disabled="item.disabled"
          :size="iconSize"
          :icon="icon"
          :icon-inverse="iconInverse"
          :icon-disabled="iconDisabled"
          :icon-svg="iconSvg"
        />
      </template>
    </MdCellItem>
  </MdCheckGroup>
</template>

<script setup lang="ts">
import { computed, ref, useSlots } from 'vue'
import MdCheck from './Check.vue'
import MdCheckGroup from './CheckGroup.vue'
import MdCellItem from '../cell-item/CellItem.vue'

defineOptions({ name: 'md-check-list' })

const props = withDefaults(
  defineProps<{
    options?: CheckListOption[]
    modelValue?: Array<string | number | boolean>
    alignCenter?: boolean
    isSlotScope?: boolean
    icon?: string
    iconInverse?: string
    iconDisabled?: string
    iconSvg?: boolean
    iconSize?: string
    iconPosition?: string
  }>(),
  {
    options: () => [],
    modelValue: () => [],
    alignCenter: false,
    isSlotScope: undefined,
    icon: 'checked',
    iconInverse: 'check',
    iconDisabled: 'check-disabled',
    iconSvg: false,
    iconSize: 'md',
    iconPosition: 'right',
  },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: Array<string | number | boolean>): void
}>()

const slots = useSlots()
const group = ref<InstanceType<typeof MdCheckGroup>>()

const hasSlot = computed(() =>
  props.isSlotScope !== undefined ? props.isSlotScope : !!slots.default,
)

const iconSlotName = computed(() => (props.iconPosition === 'right' ? 'right' : 'left'))

function check(option: CheckListOption) {
  group.value?.toggle?.(option.value)
}

function onInput(value: Array<string | number | boolean>) {
  emit('update:modelValue', value)
}
</script>

<script lang="ts">
export interface CheckListOption {
  value: string | number | boolean
  text?: string
  label?: string
  brief?: string
  disabled?: boolean
}
</script>

// packages/react/src/components/check/CheckList.tsx
import { useContext, useMemo, type ReactNode } from 'react'
import {
  CheckGroupContext,
  MdCheck,
  MdCheckGroup,
  type CheckValue,
} from './Check'
import { MdCellItem } from '../cell-item/CellItem'

export interface CheckListOption {
  value: CheckValue
  text?: string
  label?: string
  brief?: string
  disabled?: boolean
}

export interface CheckListProps {
  options?: CheckListOption[]
  value?: CheckValue[]
  alignCenter?: boolean
  isSlotScope?: boolean
  icon?: string
  iconInverse?: string
  iconDisabled?: string
  iconSvg?: boolean
  iconSize?: string
  iconPosition?: string
  children?: (slotProps: { option: CheckListOption; index: number; selected: boolean }) => ReactNode
  onChange?: (value: CheckValue[]) => void
}

export function MdCheckList({
  options = [],
  value = [],
  alignCenter = false,
  isSlotScope,
  icon = 'checked',
  iconInverse = 'check',
  iconDisabled = 'check-disabled',
  iconSvg = false,
  iconSize = 'md',
  iconPosition = 'right',
  children,
  onChange,
}: CheckListProps) {
  const hasSlot = isSlotScope !== undefined ? isSlotScope : !!children
  // 组操作经内部 CheckGroup 完成后回流
  const groupRef = useContext(CheckGroupContext)

  const items = useMemo(
    () =>
      options.map((item, index) => ({
        item,
        index,
        selected: value.indexOf(item.value) !== -1,
      })),
    [options, value],
  )

  const renderIcon = (item: CheckListOption) => (
    <MdCheck
      name={item.value}
      value={value.includes(item.value) ? item.value : false}
      disabled={item.disabled}
      size={iconSize}
      icon={icon}
      iconInverse={iconInverse}
      iconDisabled={iconDisabled}
      iconSvg={iconSvg}
    />
  )

  return (
    <MdCheckGroup value={value} onChange={onChange}>
      <InnerList
        options={items}
        alignCenter={alignCenter}
        hasSlot={hasSlot}
        iconPosition={iconPosition}
        renderIcon={renderIcon}
        slotRender={children}
        groupToggle={name => {
          // toggle 逻辑在 Provider 内部，通过二次渲染回调实现：
          // 直接以当前 value 计算增删（与组内 toggle 等价）
          const index = value.indexOf(name)
          if (index === -1) {
            onChange?.(value.concat(name))
          } else {
            onChange?.(value.slice(0, index).concat(value.slice(index + 1)))
          }
          void groupRef
        }}
      />
    </MdCheckGroup>
  )
}

interface InnerListItem {
  item: CheckListOption
  index: number
  selected: boolean
}

function InnerList({
  options,
  alignCenter,
  hasSlot,
  iconPosition,
  renderIcon,
  slotRender,
  groupToggle,
}: {
  options: InnerListItem[]
  alignCenter: boolean
  hasSlot: boolean
  iconPosition: string
  renderIcon: (item: CheckListOption) => ReactNode
  slotRender?: (slotProps: { option: CheckListOption; index: number; selected: boolean }) => ReactNode
  groupToggle: (name: CheckValue) => void
}) {
  return (
    <div
      className={`md-check-list${alignCenter ? ' is-align-center' : ''}`}
    >
      {options.map(({ item, index, selected }) => (
        <MdCellItem
          key={index}
          className={`md-check-item${selected ? ' is-checked' : ''}`}
          title={hasSlot ? '' : item.text || item.label || ''}
          brief={hasSlot ? '' : item.brief}
          disabled={item.disabled}
          right={iconPosition === 'right' && !alignCenter ? renderIcon(item) : undefined}
          left={iconPosition === 'left' && !alignCenter ? renderIcon(item) : undefined}
          onClick={() => groupToggle(item.value)}
        >
          {hasSlot ? slotRender?.({ option: item, index, selected }) : null}
        </MdCellItem>
      ))}
    </div>
  )
}
