// packages/react/src/components/notice-bar/NoticeBar.tsx
import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react'
import { MdIcon } from '../icon/Icon'

export interface NoticeBarProps {
  /** link | closable */
  mode?: string
  /** default | activity | warning */
  type?: string
  time?: number
  round?: boolean
  multiRows?: boolean
  scrollable?: boolean
  icon?: string
  iconSvg?: boolean
  closable?: boolean
  left?: ReactNode
  right?: ReactNode
  children?: ReactNode
  onClose?: () => void
}

export function MdNoticeBar({
  mode = '',
  type = 'default',
  time = 0,
  round = false,
  multiRows = false,
  scrollable = false,
  icon = '',
  iconSvg = false,
  closable = false,
  left,
  right,
  children,
  onClose,
}: NoticeBarProps) {
  const wrapRef = useRef<HTMLDivElement>(null)
  const contentRef = useRef<HTMLDivElement>(null)
  const [isShow, setIsShow] = useState(true)
  const [overflow, setOverflow] = useState(false)

  const customLeft = left !== undefined
  const customRight = right !== undefined
  const rightIcon = mode === 'link' ? 'arrow' : 'close'

  /**
   * 计算 padding-left 对宽度的影响（v2 契约：getBoundingClientRect）
   */
  const checkOverflow = useCallback(() => {
    if (!scrollable) {
      return
    }
    const wrapEl = wrapRef.current
    const contentEl = contentRef.current
    if (!wrapEl || !contentEl) {
      return
    }
    const paddingLeft =
      window.getComputedStyle(contentEl, null).getPropertyValue('padding').split(' ')[3] || '0px'
    const pad = +(paddingLeft.match(/\d+/g) as string[])[0]
    setOverflow(contentEl.scrollWidth - pad > Math.ceil(wrapEl.getBoundingClientRect().width))
  }, [scrollable])

  useEffect(() => {
    if (time) {
      const timer = setTimeout(() => setIsShow(false), time)
      return () => clearTimeout(timer)
    }
  }, [time])

  useEffect(() => {
    checkOverflow()
  }, [checkOverflow, children])

  const close = () => {
    if (mode === 'closable' || closable) {
      setIsShow(false)
    }
    onClose?.()
  }

  if (!isShow) {
    return null
  }

  return (
    <div
      className={`md-notice-bar${round ? ' md-notice-bar-round' : ''} ${type}`}
    >
      <div
        className={`md-notice-bar-left${!customLeft && !icon ? ' md-notice-bar-empty' : ''}`}
      >
        {customLeft ? (
          left
        ) : icon ? (
          <MdIcon name={icon} svg={iconSvg} className="md-notice-icon" />
        ) : null}
      </div>
      <div
        ref={wrapRef}
        className={`md-notice-bar-content${multiRows ? ' md-notice-bar-multi-content' : ''}`}
      >
        <div ref={contentRef} className={overflow && scrollable ? 'md-notice-bar-content-animate' : ''}>
          {children}
        </div>
      </div>
      <div className="md-notice-bar-right">
        {customRight ? (
          right
        ) : mode || closable ? (
          <MdIcon
            name={rightIcon}
            className="md-notice-icon md-notice-icon-right"
            onClick={event => {
              event.stopPropagation()
              close()
            }}
          />
        ) : null}
      </div>
    </div>
  )
}

// packages/vue/src/components/notice-bar/NoticeBar.vue
<template>
  <div v-if="isShow" class="md-notice-bar" :class="[round && 'md-notice-bar-round', type]">
    <div class="md-notice-bar-left" :class="[!customLeft && !icon && 'md-notice-bar-empty']">
      <!-- custom first -->
      <template v-if="customLeft">
        <slot name="left"></slot>
      </template>
      <template v-else-if="icon">
        <MdIcon class="md-notice-icon" :name="icon" :svg="iconSvg"></MdIcon>
      </template>
    </div>
    <div
      ref="wrap"
      class="md-notice-bar-content"
      :class="[multiRows && 'md-notice-bar-multi-content']"
    >
      <div ref="content" :class="[overflow && scrollable && 'md-notice-bar-content-animate']">
        <slot></slot>
      </div>
    </div>
    <div class="md-notice-bar-right">
      <!-- custom first -->
      <template v-if="customRight">
        <slot name="right"></slot>
      </template>
      <template v-else-if="mode || closable">
        <MdIcon
          class="md-notice-icon md-notice-icon-right"
          :name="rightIcon"
          @click.stop="close"
        ></MdIcon>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUpdated, ref, useSlots } from 'vue'
import MdIcon from '../icon/Icon.vue'

defineOptions({ name: 'md-notice-bar' })

const props = withDefaults(
  defineProps<{
    /** link | closable */
    mode?: string
    /** default | activity | warning */
    type?: string
    time?: number
    round?: boolean
    multiRows?: boolean
    scrollable?: boolean
    icon?: string
    iconSvg?: boolean
    closable?: boolean
  }>(),
  {
    mode: '',
    type: 'default',
    time: 0,
    round: false,
    multiRows: false,
    scrollable: false,
    icon: '',
    iconSvg: false,
    closable: false,
  },
)

const emit = defineEmits<{
  (e: 'close'): void
}>()

const slots = useSlots()
const wrap = ref<HTMLElement>()
const content = ref<HTMLElement>()
const isShow = ref(true)
const overflow = ref(false)

const customLeft = computed(() => !!slots.left)
const customRight = computed(() => !!slots.right)
const rightIcon = computed(() => (props.mode === 'link' ? 'arrow' : 'close'))

function hide(time: number) {
  setTimeout(() => {
    isShow.value = false
  }, time)
}

function close() {
  if (props.mode === 'closable' || props.closable) {
    isShow.value = false
  }
  emit('close')
}

/**
 * 计算 padding-left 对宽度的影响
 * 替换 clientWidth 为 getBoundingClientRect
 */
function checkOverflow() {
  if (!props.scrollable) {
    return
  }

  const wrapEl = wrap.value
  const contentEl = content.value
  if (!wrapEl || !contentEl) {
    return
  }

  const paddingLeft =
    window.getComputedStyle(contentEl, null).getPropertyValue('padding').split(' ')[3] || '0px'
  const left = +(paddingLeft.match(/\d+/g) as string[])[0]

  overflow.value = contentEl.scrollWidth - left > Math.ceil(wrapEl.getBoundingClientRect().width)
}

onMounted(() => {
  if (props.time) {
    hide(props.time)
  }
  checkOverflow()
})

onUpdated(() => {
  checkOverflow()
})
</script>
