// packages/react/src/components/popup/Popup.tsx
import {
  createContext,
  useEffect,
  useRef,
  useState,
  type ReactNode,
} from 'react'

export interface PopupContextValue {
  setLargeRadius: (value: boolean) => void
}

export const PopupContext = createContext<PopupContextValue>({
  setLargeRadius: () => {},
})

export interface PopupProps {
  value?: boolean
  hasMask?: boolean
  maskClosable?: boolean
  /** center | top | bottom | left | right */
  position?: string
  /** 覆盖默认过渡名（样式由 @mand-mobile/styles 提供） */
  transition?: string
  preventScroll?: boolean
  preventScrollExclude?: string | HTMLElement
  onBeforeShow?: () => void
  onBeforeHide?: () => void
  onShow?: () => void
  onHide?: () => void
  /** 遮罩点击（maskClosable 时触发） */
  onMaskClick?: () => void
  onChange?: (value: boolean) => void
  children?: ReactNode
  className?: string
}

const isTestEnv =
  typeof process !== 'undefined' && (process.env as { MAND_ENV?: string }).MAND_ENV === 'test'

function defaultTransition(position: string): string {
  switch (position) {
    case 'bottom':
      return 'md-slide-up'
    case 'top':
      return 'md-slide-down'
    case 'left':
      return 'md-slide-right'
    case 'right':
      return 'md-slide-left'
    default:
      return 'md-fade'
  }
}

export function MdPopup({
  value = false,
  hasMask = true,
  maskClosable = true,
  position = 'center',
  transition,
  preventScroll = false,
  preventScrollExclude = '',
  onBeforeShow,
  onBeforeHide,
  onShow,
  onHide,
  onMaskClick,
  onChange,
  children,
  className,
}: PopupProps) {
  const rootRef = useRef<HTMLDivElement>(null)
  const [isPopupShow, setIsPopupShow] = useState(false)
  const [isPopupBoxShow, setIsPopupBoxShow] = useState(false)
  // 过渡钩子需要读取最新开关态（state 闭包值在首帧过期）
  const isPopupBoxShowRef = useRef(false)
  const [largeRadius, setLargeRadius] = useState(false)
  const isAnimationRef = useRef(false)

  const transitionName = transition ?? defaultTransition(position)

  const fireTransitionStart = () => {
    if (!isPopupBoxShowRef.current) {
      onBeforeHide?.()
    } else {
      onBeforeShow?.()
    }
  }

  const fireTransitionEnd = () => {
    if (!isAnimationRef.current) {
      return
    }
    if (!isPopupBoxShowRef.current) {
      setIsPopupShow(false)
      onHide?.()
    } else {
      onShow?.()
    }
    isAnimationRef.current = false
  }

  const showPopupBox = () => {
    setIsPopupShow(true)
    isAnimationRef.current = true
    setIsPopupBoxShow(true)
    isPopupBoxShowRef.current = true
    if (isTestEnv) {
      // v2 契约：测试环境同步触发过渡钩子
      fireTransitionStart()
      fireTransitionEnd()
    }
    if (preventScroll) {
      bindPreventScroll(true)
    }
  }

  const hidePopupBox = () => {
    isAnimationRef.current = true
    setIsPopupBoxShow(false)
    isPopupBoxShowRef.current = false
    if (preventScroll) {
      bindPreventScroll(false)
    }
    onChange?.(false)
    if (isTestEnv) {
      fireTransitionStart()
      fireTransitionEnd()
    }
  }

  // v2 契约：动画锁期间再次打开走 50ms 延迟分支
  useEffect(() => {
    if (value) {
      if (isAnimationRef.current) {
        const timer = setTimeout(showPopupBox, 50)
        return () => clearTimeout(timer)
      }
      showPopupBox()
    } else if (isPopupShow || isPopupBoxShow) {
      hidePopupBox()
    }
  }, [value])

  const preventDefault = (event: Event) => event.preventDefault()
  const stopImmediatePropagation = (event: Event) => event.stopImmediatePropagation()

  const bindPreventScroll = (isBind: boolean) => {
    const handler = isBind ? 'addEventListener' : 'removeEventListener'
    const masker = rootRef.current?.querySelector<HTMLElement>('.md-popup-mask')
    const boxer = rootRef.current?.querySelector<HTMLElement>('.md-popup-box')
    masker?.[handler]('touchmove', preventDefault, false)
    boxer?.[handler]('touchmove', preventDefault, false)

    const excluder: HTMLElement | undefined | null =
      typeof preventScrollExclude === 'string'
        ? preventScrollExclude
          ? rootRef.current?.querySelector<HTMLElement>(preventScrollExclude)
          : undefined
        : preventScrollExclude
    if (excluder) {
      excluder[handler]('touchmove', stopImmediatePropagation, false)
    }
  }

  const handleMaskClick = () => {
    if (maskClosable) {
      hidePopupBox()
      onMaskClick?.()
    }
  }

  const contextValue = useRef({ setLargeRadius })
  contextValue.current.setLargeRadius = setLargeRadius

  return (
    <PopupContext.Provider value={contextValue.current}>
      <div
        ref={rootRef}
        className={[
          'md-popup',
          className,
          hasMask ? 'with-mask' : '',
          largeRadius ? 'large-radius' : '',
          position,
        ]
          .filter(Boolean)
          .join(' ')}
        style={{ display: isPopupShow ? undefined : 'none' }}
      >
        <div
          className="md-popup-mask"
          style={{ display: hasMask && isPopupBoxShow ? undefined : 'none' }}
          onClick={handleMaskClick}
        ></div>
        <div
          className={`md-popup-box ${transitionName}`}
          style={{ display: isPopupBoxShow ? undefined : 'none' }}
        >
          {children}
        </div>
      </div>
    </PopupContext.Provider>
  )
}

// packages/vue/src/components/popup/Popup.vue
<template>
  <div
    v-show="isPopupShow"
    ref="root"
    class="md-popup"
    :class="[hasMask ? 'with-mask' : '', largeRadius ? 'large-radius' : '', position]"
  >
    <transition name="md-mask-fade">
      <div v-show="hasMask && isPopupBoxShow" class="md-popup-mask" @click="onPopupMaskClick"></div>
    </transition>
    <transition
      :name="transitionName"
      @before-enter="onPopupTransitionStart"
      @before-leave="onPopupTransitionStart"
      @after-enter="onPopupTransitionEnd"
      @after-leave="onPopupTransitionEnd"
    >
      <div v-show="isPopupBoxShow" class="md-popup-box" :class="[transitionName]">
        <slot></slot>
      </div>
    </transition>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, provide, ref, watch, type Ref } from 'vue'

defineOptions({ name: 'md-popup' })

const props = withDefaults(
  defineProps<{
    modelValue?: boolean
    hasMask?: boolean
    maskClosable?: boolean
    /** center | top | bottom | left | right */
    position?: string
    /** 覆盖默认过渡名（md-fade / md-slide-up / ...，样式由 @mand-mobile/styles 提供） */
    transition?: string
    preventScroll?: boolean
    preventScrollExclude?: string | HTMLElement
  }>(),
  {
    modelValue: false,
    hasMask: true,
    maskClosable: true,
    position: 'center',
    transition: undefined,
    preventScroll: false,
    preventScrollExclude: '',
  },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
  (e: 'beforeShow'): void
  (e: 'before-show'): void
  (e: 'beforeHide'): void
  (e: 'before-hide'): void
  (e: 'show'): void
  (e: 'hide'): void
  (e: 'maskClick'): void
}>()

const isTestEnv = typeof process !== 'undefined' && process.env.MAND_ENV === 'test'

const root = ref<HTMLElement>()

// controle popup mask & popup box
const isPopupShow = ref(false)
// controle popup box
const isPopupBoxShow = ref(false)
// transition lock
const isAnimation = ref(false)
const largeRadius = ref(false)

provide('mdPopupLargeRadius', largeRadius as Ref<boolean>)

const transitionName = computed(() => props.transition ?? defaultTransition(props.position))

function defaultTransition(position: string): string {
  switch (position) {
    case 'bottom':
      return 'md-slide-up'
    case 'top':
      return 'md-slide-down'
    case 'left':
      return 'md-slide-right'
    case 'right':
      return 'md-slide-left'
    default:
      return 'md-fade'
  }
}

watch(
  () => props.modelValue,
  (val) => {
    if (val) {
      if (isAnimation.value) {
        setTimeout(() => {
          showPopupBox()
        }, 50)
      } else {
        showPopupBox()
      }
    } else {
      hidePopupBox()
    }
  },
)

watch(
  () => props.preventScrollExclude,
  (val, oldVal) => {
    // remove old listener before add
    preventScrollExcludeBind(false, oldVal)
    preventScrollExcludeBind(true, val)
  },
)

onMounted(() => {
  props.modelValue && showPopupBox()
})

function showPopupBox() {
  isPopupShow.value = true
  isAnimation.value = true
  // popup box enter the animation after popup show
  isPopupBoxShow.value = true
  if (isTestEnv) {
    onPopupTransitionStart()
    onPopupTransitionEnd()
  }

  props.preventScroll && preventScroll(true)
}

function hidePopupBox() {
  isAnimation.value = true
  isPopupBoxShow.value = false
  props.preventScroll && preventScroll(false)
  emit('update:modelValue', false)
  if (isTestEnv) {
    onPopupTransitionStart()
    onPopupTransitionEnd()
  }
}

function preventScroll(isBind: boolean) {
  const handler = isBind ? 'addEventListener' : 'removeEventListener'
  const masker = root.value?.querySelector<HTMLElement>('.md-popup-mask')
  const boxer = root.value?.querySelector<HTMLElement>('.md-popup-box')

  masker && masker[handler]('touchmove', preventDefault, false)
  boxer && boxer[handler]('touchmove', preventDefault, false)
  preventScrollExcludeBind(isBind)
}

function preventScrollExcludeBind(
  isBind: boolean,
  exclude: string | HTMLElement | undefined = props.preventScrollExclude,
) {
  const handler = isBind ? 'addEventListener' : 'removeEventListener'
  const excluder: HTMLElement | undefined | null =
    typeof exclude === 'string'
      ? exclude
        ? root.value?.querySelector<HTMLElement>(exclude)
        : undefined
      : exclude
  if (excluder) {
    excluder[handler]('touchmove', stopImmediatePropagation, false)
  }
}

function preventDefault(event: Event) {
  event.preventDefault()
}

function stopImmediatePropagation(event: Event) {
  event.stopImmediatePropagation()
}

function onPopupTransitionStart() {
  if (!isPopupBoxShow.value) {
    emit('beforeHide')
    emit('before-hide')
  } else {
    emit('beforeShow')
    emit('before-show')
  }
}

function onPopupTransitionEnd() {
  if (!isAnimation.value) {
    return
  }

  if (!isPopupBoxShow.value) {
    // popup hide after popup box finish animation
    isPopupShow.value = false
    emit('hide')
  } else {
    emit('show')
  }

  isAnimation.value = false
}

function onPopupMaskClick() {
  if (props.maskClosable) {
    hidePopupBox()
    emit('maskClick')
  }
}
</script>
