// packages/vue/src/components/detail-item/DetailItem.vue
<template>
  <div class="md-detail-item" :class="{ 'is-bold': bold }">
    <div class="md-detail-title" v-text="title"></div>
    <div class="md-detail-content">
      <slot>{{ content }}</slot>
    </div>
  </div>
</template>

<script setup lang="ts">
defineOptions({ name: 'md-detail-item' })

withDefaults(
  defineProps<{
    title?: string
    content?: string | number
    bold?: boolean
  }>(),
  { title: '', content: '', bold: false },
)
</script>

// packages/react/src/components/detail-item/DetailItem.tsx
import { forwardRef, type ReactNode } from 'react'

export interface DetailItemProps {
  title?: string
  content?: string | number
  bold?: boolean
  children?: ReactNode
}

export const CuDetailItem = forwardRef<HTMLDivElement, DetailItemProps>(function CuDetailItem(
  { title = '', content = '', bold = false, children },
  ref,
) {
  return (
    <div className={`cu-detail-item${bold ? ' is-bold' : ''}`} ref={ref}>
      <div className="cu-detail-title">{title}</div>
      <div className="cu-detail-content">{children ?? content}</div>
    </div>
  )
})
