// docs/src/components/demos/transition/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { MdTransition } from 'mand-mobile'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['淡入淡出', '滑动', '弹跳']
const code = `<MdTransition name="md-fade">
  <div v-if="show">内容</div>
</MdTransition>`
const names = ['md-fade', 'md-slide-up', 'md-bounce']
const idx = ref(0)
const show = ref(true)
const scene = ref(0)

function toggle(i: number) {
  idx.value = i
  show.value = false
  setTimeout(() => {
    show.value = true
  }, 300)
}

function onSelect(i: number) {
  scene.value = i
  toggle(i)
}
</script>

<template>
  <DemoCanvas mode="stage" :scenes="scenes" :code="code">
    <template #scene-0>
      <div class="transition-demo">
        <button class="transition-demo-btn" @click="toggle(0)">播放淡入淡出</button>
        <MdTransition name="md-fade">
          <div v-if="show && idx === 0" class="transition-demo-box">淡入淡出内容</div>
        </MdTransition>
      </div>
    </template>
    <template #scene-1>
      <div class="transition-demo">
        <button class="transition-demo-btn" @click="toggle(1)">播放上滑</button>
        <MdTransition name="md-slide-up">
          <div v-if="show && idx === 1" class="transition-demo-box">上滑内容</div>
        </MdTransition>
      </div>
    </template>
    <template #scene-2>
      <div class="transition-demo">
        <button class="transition-demo-btn" @click="toggle(2)">播放弹跳</button>
        <MdTransition name="md-bounce">
          <div v-if="show && idx === 2" class="transition-demo-box">弹跳内容</div>
        </MdTransition>
      </div>
    </template>
  </DemoCanvas>
</template>

// docs/src/components/demos-react/transition/index.tsx
import { useState } from 'react'
import { MdTransition } from 'mand-mobile-react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['淡入淡出', '滑动', '弹跳']
const code = `<MdTransition name="md-fade">
  {show && <div>内容</div>}
</MdTransition>`
const names = ['md-fade', 'md-slide-up', 'md-bounce']

export default function TransitionDemo() {
  const [show, setShow] = useState(true)
  const [idx, setIdx] = useState(0)

  const toggle = (i: number) => {
    setIdx(i)
    setShow(false)
    setTimeout(() => setShow(true), 300)
  }

  return (
    <DemoCanvasReact mode="stage" scenes={scenes} code={code}>
      {active => (
        <div className="transition-demo">
          <button className="transition-demo-btn" onClick={() => toggle(active)}>
            播放{scenes[active]}
          </button>
          <MdTransition name={names[active]}>
            {show ? <div className="transition-demo-box">{scenes[active]}内容</div> : null}
          </MdTransition>
        </div>
      )}
    </DemoCanvasReact>
  )
}
