// packages/vue/src/components/license-plate/LicensePlateKeyboard.vue
<template>
  <div class="md-license-plate-keyboard">
    <!-- 省份简写键盘（第一位） -->
    <div v-if="keyboardType === 1" class="md-shortcut-row">
      <div
        v-for="(item, index) in shortcuts"
        :key="index"
        class="md-shortcut-row-item"
        @click="$emit('enter', item)"
      >
        {{ item }}
      </div>
    </div>
    <!-- 字母数字混合键盘（第二位起） -->
    <div v-else class="md-mixed-key-board">
      <div
        v-for="(item, index) in mixedKeyboard"
        :key="index"
        class="md-mixed-key-board-item"
        :class="{ disabled: item.disabled }"
      >
        <template v-if="item.type">
          <div
            :class="item.type"
            @click="item.type === 'delete' ? $emit('delete') : $emit('confirm')"
          >
            <div v-if="item.type === 'confirm' && item.text">{{ item.text }}</div>
          </div>
        </template>
        <template v-else>
          <div @click="!item.disabled && $emit('enter', item.value)">{{ item.value }}</div>
        </template>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({ name: 'md-license-plate-keyboard' })

export interface LicenseKeyItem {
  value?: string | number
  type?: 'delete' | 'confirm'
  text?: string
  disabled?: boolean
}

const props = withDefaults(
  defineProps<{
    keyboard?: {
      shortcuts?: string[]
      mixedKeyboard?: LicenseKeyItem[]
      keyboardType?: number
    }
  }>(),
  { keyboard: () => ({}) },
)

defineEmits<{
  (e: 'enter', value: string | number | undefined): void
  (e: 'delete'): void
  (e: 'confirm'): void
}>()

const shortcuts = computed(() => props.keyboard.shortcuts || [])
const keyboardType = computed(() => props.keyboard.keyboardType || 1)
const mixedKeyboard = computed(() => props.keyboard.mixedKeyboard || [])
</script>

// packages/react/src/components/license-plate/LicensePlateKeyboard.tsx
export interface LicenseKeyItem {
  value?: string | number
  type?: 'delete' | 'confirm'
  text?: string
  disabled?: boolean
}

export interface LicensePlateKeyboardProps {
  keyboard?: {
    shortcuts?: string[]
    mixedKeyboard?: LicenseKeyItem[]
    keyboardType?: number
  }
  onEnter?: (value: string | number) => void
  onDelete?: () => void
  onConfirm?: () => void
}

export function MdLicensePlateKeyboard({ keyboard = {}, onEnter, onDelete, onConfirm }: LicensePlateKeyboardProps) {
  const shortcuts = keyboard.shortcuts || []
  const keyboardType = keyboard.keyboardType || 1
  const mixedKeyboard = keyboard.mixedKeyboard || []

  if (keyboardType === 1) {
    return (
      <div className="md-license-plate-keyboard">
        <div className="md-shortcut-row">
          {shortcuts.map((item, index) => (
            <div key={index} className="md-shortcut-row-item" onClick={() => onEnter?.(item)}>
              {item}
            </div>
          ))}
        </div>
      </div>
    )
  }

  return (
    <div className="md-license-plate-keyboard">
      <div className="md-mixed-key-board">
        {mixedKeyboard.map((item, index) => (
          <div key={index} className={`md-mixed-key-board-item${item.disabled ? ' disabled' : ''}`}>
            {item.type ? (
              <div
                className={item.type}
                onClick={() => {
                  if (item.disabled) {
                    return
                  }
                  if (item.type === 'delete') {
                    onDelete?.()
                  } else {
                    onConfirm?.()
                  }
                }}
              >
                {item.type === 'confirm' && item.text ? <div>{item.text}</div> : null}
              </div>
            ) : (
              <div onClick={() => !item.disabled && onEnter?.(item.value as string | number)}>{item.value}</div>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}
