// docs/src/components/demos/ruler/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { MdRuler } from 'mand-mobile'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['基础刻度', '自定义文案']
const code = `<MdRuler v-model="value" :scope="[0, 1000]" :step="100" :unit="25" />
<MdRuler v-model="value" :step-text-render="(v) => v + 'cm'" />`
const value = ref(500)
const value2 = ref(100)
</script>

<template>
  <DemoCanvas mode="stage" :scenes="scenes" :code="code">
    <template #scene-0>
      <div class="ruler-demo-box">
        <MdRuler v-model="value" :scope="[0, 1000]" :step="100" :unit="25" />
        <p class="ruler-demo-value">当前值：{{ value }}</p>
      </div>
    </template>
    <template #scene-1>
      <div class="ruler-demo-box">
        <MdRuler
          v-model="value2"
          :scope="[0, 200]"
          :step="50"
          :unit="10"
          :step-text-render="(v: number) => v + 'cm'"
        />
        <p class="ruler-demo-value">当前值：{{ value2 }}cm</p>
      </div>
    </template>
  </DemoCanvas>
</template>

// docs/src/components/demos-react/ruler/index.tsx
import { useState } from 'react'
import { MdRuler } from 'mand-mobile-react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['基础刻度', '自定义文案']
const code = `<MdRuler value={v} onChange={setV} scope={[0, 1000]} step={100} unit={25} />
<MdRuler value={v} onChange={setV} stepTextRender={(v) => v + 'cm'} />`

export default function RulerDemo() {
  const [value, setValue] = useState(500)
  const [value2, setValue2] = useState(100)

  return (
    <DemoCanvasReact mode="stage" scenes={scenes} code={code}>
      {active => {
        if (active === 0)
          return (
            <div className="ruler-demo-box">
              <MdRuler value={value} onChange={setValue} scope={[0, 1000]} step={100} unit={25} />
              <p className="ruler-demo-value">当前值：{value}</p>
            </div>
          )
        return (
          <div className="ruler-demo-box">
            <MdRuler
              value={value2}
              onChange={setValue2}
              scope={[0, 200]}
              step={50}
              unit={10}
              stepTextRender={v => `${v}cm`}
            />
            <p className="ruler-demo-value">当前值：{value2}cm</p>
          </div>
        )
      }}
    </DemoCanvasReact>
  )
}
