// packages/react/src/components/radio-list/RadioList.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef, useState, type ReactNode } from 'react'
import { MdRadio } from '../radio/Radio'
import { MdCellItem } from '../cell-item/CellItem'
import { MdInputItem } from '../input-item/InputItem'
import type { CheckValue } from '../check/Check'

export interface RadioListOption {
  value: CheckValue
  text?: string
  label?: string
  brief?: string
  disabled?: boolean
}

export interface RadioListProps {
  options?: RadioListOption[]
  value?: CheckValue
  hasInput?: boolean
  inputLabel?: string
  inputPlaceholder?: string
  alignCenter?: boolean
  isSlotScope?: boolean
  icon?: string
  iconInverse?: string
  iconDisabled?: string
  iconSvg?: boolean
  iconSize?: string
  iconPosition?: string
  children?: (slotProps: { option: RadioListOption; index: number; selected: boolean }) => ReactNode
  onChange?: (option: RadioListOption, index: number) => void
  onChangeValue?: (value: CheckValue) => void
}

export interface RadioListExposed {
  select: (value: CheckValue) => void
  selectByIndex: (index: number) => void
}

export const MdRadioList = forwardRef<RadioListExposed, RadioListProps>(function MdRadioList(
  {
    options = [],
  value = '',
  hasInput = false,
  inputLabel = '',
  inputPlaceholder = '',
  alignCenter = false,
  isSlotScope,
  icon = 'checked',
  iconInverse = 'check',
  iconDisabled = 'check-disabled',
  iconSvg = false,
  iconSize = 'md',
    iconPosition = 'left',
    children,
    onChange,
    onChangeValue,
  }: RadioListProps,
  ref,
) {
  const inputItemRef = useRef<{ focus: () => void } | null>(null)
  const [selectedValue, setSelectedValue] = useState(value)
  const [inputSelected, setInputSelected] = useState(false)
  const [inputValue, setInputValue] = useState('')

  const hasSlot = isSlotScope !== undefined ? isSlotScope : !!children
  const withoutIcon = !!isSlotScope && !icon

  // currentValue 变化派发（v2 watch 契约）
  const currentValue = inputSelected ? inputValue : selectedValue

  useEffect(() => {
    if (value !== selectedValue) {
      setSelectedValue(value)
    }
  }, [value])

  useEffect(() => {
    onChangeValue?.(currentValue)
  }, [currentValue])

  const select = (option: RadioListOption, index: number) => {
    setSelectedValue(option.value)
    setInputSelected(false)
    if (inputValue) {
      setInputValue('')
    }
    onChange?.(option, index)
  }

  const selectByValue = (val: CheckValue) => {
    setSelectedValue(val)
    setInputSelected(false)
  }

  const selectByIndex = (index: number) => {
    const item = options[index]
    if (item) {
      selectByValue(item.value)
    }
  }

  useImperativeHandle(ref, () => ({ select: selectByValue, selectByIndex }), [options])

  const iconNode = (item: RadioListOption) =>
    !alignCenter && !inputSelected && !withoutIcon ? (
      <MdRadio
        name={item.value}
        value={selectedValue}
        disabled={item.disabled}
        size={iconSize}
        icon={icon}
        iconInverse={iconInverse}
        iconDisabled={iconDisabled}
        iconSvg={iconSvg}
      />
    ) : null

  return (
    <div className={`md-radio-list${alignCenter ? ' is-align-center' : ''}`}>
      {options.map((item, index) => (
        <MdCellItem
          key={index}
          className={`md-radio-item${selectedValue === item.value && !inputSelected ? ' is-selected' : ''}`}
          title={hasSlot ? '' : item.text || item.label || ''}
          brief={hasSlot ? '' : item.brief}
          disabled={item.disabled}
          noBorder={index === options.length - 1 && !hasInput}
          left={iconPosition === 'left' ? iconNode(item) : undefined}
          right={iconPosition === 'right' ? iconNode(item) : undefined}
          onClick={() => select(item, index)}
        >
          {hasSlot ? children?.({ option: item, index, selected: currentValue === item.value }) : null}
        </MdCellItem>
      ))}
      {hasInput ? (
        <MdInputItem
          ref={inputItemRef as never}
          className={`md-radio-item${inputSelected ? ' is-selected' : ''}`}
          title={inputLabel}
          placeholder={inputPlaceholder}
          value={inputValue}
          onChange={setInputValue}
          onFocus={() => setInputSelected(true)}
        />
      ) : null}
    </div>
  )
})

// packages/vue/src/components/radio-list/RadioList.vue
<template>
  <div class="md-radio-list" :class="{ 'is-align-center': alignCenter }">
    <MdCellItem
      v-for="(item, index) in options"
      :key="index"
      class="md-radio-item"
      :class="{
        'is-selected': selectedValue === item.value && !inputSelected,
      }"
      :title="hasSlot ? '' : item.text || item.label"
      :brief="hasSlot ? '' : item.brief"
      :disabled="item.disabled"
      :no-border="index === options.length - 1"
      @click="select(item, index)"
    >
      <template v-if="hasSlot">
        <slot :option="item" :index="index" :selected="currentValue === item.value"></slot>
      </template>
      <template v-if="!alignCenter && !inputSelected && !withoutIcon" #[iconSlotName]>
        <MdRadio
          :name="item.value"
          :model-value="selectedValue"
          :disabled="item.disabled"
          :size="iconSize"
          :icon="icon"
          :icon-inverse="iconInverse"
          :icon-disabled="iconDisabled"
          :icon-svg="iconSvg"
        />
      </template>
    </MdCellItem>
    <MdInputItem
      v-if="hasInput"
      ref="inputItem"
      class="md-radio-item"
      :class="{
        'is-selected': inputSelected,
      }"
      :title="inputLabel"
      :placeholder="inputPlaceholder"
      :model-value="inputValue"
      @update:model-value="(value) => (inputValue = value)"
      @focus="inputSelected = true"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, ref, useSlots, watch } from 'vue'
import MdRadio from '../radio/Radio.vue'
import MdCellItem from '../cell-item/CellItem.vue'
import MdInputItem from '../input-item/InputItem.vue'

defineOptions({ name: 'md-radio-list' })

const props = withDefaults(
  defineProps<{
    options?: RadioListOption[]
    modelValue?: string | number | boolean
    hasInput?: boolean
    inputLabel?: string
    inputPlaceholder?: string
    alignCenter?: boolean
    isSlotScope?: boolean
    icon?: string
    iconInverse?: string
    iconDisabled?: string
    iconSvg?: boolean
    iconSize?: string
    iconPosition?: string
  }>(),
  {
    options: () => [],
    modelValue: '',
    hasInput: false,
    inputLabel: '',
    inputPlaceholder: '',
    alignCenter: false,
    isSlotScope: undefined,
    icon: 'checked',
    iconInverse: 'check',
    iconDisabled: 'check-disabled',
    iconSvg: false,
    iconSize: 'md',
    iconPosition: 'left',
  },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: string | number | boolean): void
  (e: 'change', option: RadioListOption, index: number): void
}>()

const slots = useSlots()

const selectedValue = ref(props.modelValue)
const inputSelected = ref(false)
const inputValue = ref('')

const currentValue = computed(() => (inputSelected.value ? inputValue.value : selectedValue.value))
const hasSlot = computed(() =>
  props.isSlotScope !== undefined ? props.isSlotScope : !!slots.default,
)
const withoutIcon = computed(() => props.isSlotScope && !props.icon)
const iconSlotName = computed(() => (props.iconPosition === 'right' ? 'right' : 'left'))

watch(
  () => props.modelValue,
  (val) => {
    if (val !== selectedValue.value) {
      selectedValue.value = val
    }
  },
)

watch(currentValue, (val) => {
  emit('update:modelValue', val)
})

function select(option: RadioListOption, index: number) {
  selectedValue.value = option.value
  inputSelected.value = false
  if (inputValue.value) {
    inputValue.value = ''
  }
  emit('change', option, index)
}

function selectByValue(value: string | number | boolean) {
  selectedValue.value = value
  inputSelected.value = false
}

function selectByIndex(index: number) {
  const item = props.options[index]
  if (item) {
    selectByValue(item.value)
  }
}

defineExpose({ select: selectByValue, selectByIndex })
</script>

<script lang="ts">
export interface RadioListOption {
  value: string | number | boolean
  text?: string
  label?: string
  brief?: string
  disabled?: boolean
}
</script>
