// packages/vue/src/components/drop-menu/DropMenu.vue
<template>
  <div class="md-drop-menu">
    <div class="md-drop-menu-bar">
      <div
        v-for="(item, index) in data"
        :key="index"
        class="bar-item"
        :class="{
          active: index === activeMenuBarIndex,
          selected: checkBarItemSelect(index),
          disabled: item.disabled,
        }"
        @click="onBarItemClick(item, index)"
      >
        <span v-text="getBarItemText(item, index)"></span>
      </div>
    </div>
    <MdPopup
      v-model="isPopupShow"
      position="top"
      prevent-scroll
      :prevent-scroll-exclude="scroller"
      @show="$emit('show')"
      @hide="$emit('hide')"
      @before-hide="activeMenuBarIndex = -1"
    >
      <div class="md-drop-menu-list">
        <MdRadioList
          :model-value="selectedMenuListValue[activeMenuBarIndex]"
          :options="activeMenuListData"
          :is-slot-scope="hasSlot"
          align-center
          @change="onListItemClick"
        >
          <template v-if="hasSlot" #default="{ option }">
            <slot :option="option"></slot>
          </template>
        </MdRadioList>
      </div>
    </MdPopup>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, useSlots, watch } from 'vue'
import MdPopup from '../popup/Popup.vue'
import MdRadioList from '../radio-list/RadioList.vue'
import type { RadioListOption } from '../radio-list/RadioList.vue'

defineOptions({ name: 'md-drop-menu' })

export interface DropMenuItem {
  text?: string
  disabled?: boolean
  options?: Array<{ value?: string | number; text?: string; label?: string }>
}

const props = withDefaults(
  defineProps<{
    data?: DropMenuItem[]
    defaultValue?: Array<string | number>
  }>(),
  { data: () => [], defaultValue: () => [] },
)

const emit = defineEmits<{
  (e: 'change', barItem: DropMenuItem, listItem: unknown): void
  (e: 'show'): void
  (e: 'hide'): void
}>()

const slots = useSlots()
const isPopupShow = ref(false)
const selectedMenuListItem = ref<Array<RadioListOption | undefined>>([])
const selectedMenuListValue = ref<Array<string | number>>([])
const activeMenuBarIndex = ref(-1)
const scroller = ref('')

const hasSlot = computed(() => {
  const fn = slots.default
  if (!fn) {
    return false
  }
  return fn({ option: {} }).some((n) => n.type !== Comment)
})
const activeMenuListData = computed(() => {
  if (activeMenuBarIndex.value < 0 || !props.data[activeMenuBarIndex.value]) {
    return []
  }
  return (props.data[activeMenuBarIndex.value].options ?? []) as unknown as RadioListOption[]
})

watch(
  () => props.data,
  (val, oldVal) => {
    if (JSON.stringify(val) !== JSON.stringify(oldVal)) {
      initSelectedBar()
    }
  },
)
watch(
  () => props.defaultValue,
  (val, oldVal) => {
    if (JSON.stringify(val) !== JSON.stringify(oldVal)) {
      initSelectedBar()
    }
  },
)

onMounted(() => {
  initSelectedBar()
})

// v2 traverse：按层级遍历 options，匹配 defaultValue 定位选中项
function initSelectedBar() {
  selectedMenuListValue.value = props.defaultValue
  const walk = (items: DropMenuItem[] | undefined, level: number, indexs: number[]) => {
    if (!items) {
      return
    }
    items.forEach((item) => {
      const barItemIndex = indexs[0]
      const defaultValue = props.defaultValue[barItemIndex]
      const record = item as unknown as Record<string, unknown>
      if (
        defaultValue !== undefined &&
        (record.value === defaultValue || record.text === defaultValue || record.label === defaultValue)
      ) {
        selectedMenuListItem.value[barItemIndex] = record as unknown as RadioListOption
        return
      }
      if (level > 0) {
        walk((record.options as unknown as DropMenuItem[]) ?? undefined, level, indexs)
      }
    })
  }
  props.data.forEach((barItem, barItemIndex) => {
    walk((barItem.options ?? []) as unknown as DropMenuItem[], 0, [barItemIndex])
  })
}

function checkBarItemSelect(index: number) {
  return !!(selectedMenuListItem.value[index] !== undefined || props.defaultValue[index])
}

function getBarItemText(item: DropMenuItem, index: number) {
  const selected = selectedMenuListItem.value[index]
  return selected !== undefined ? String((selected as { text?: string }).text ?? '') : item.text
}

function onBarItemClick(barItem: DropMenuItem, index: number) {
  if (!barItem || barItem.disabled) {
    return
  }

  if (!isPopupShow.value) {
    isPopupShow.value = true
    activeMenuBarIndex.value = index
  } else {
    isPopupShow.value = false
  }
}

function onListItemClick(listItem: RadioListOption) {
  const index = activeMenuBarIndex.value
  const barItem = props.data[index]
  isPopupShow.value = false
  selectedMenuListValue.value[index] = listItem.value as string | number
  selectedMenuListItem.value[index] = listItem
  emit('change', barItem, listItem)
}

defineExpose({
  getSelectedValues: () => selectedMenuListItem.value,
  getSelectedValue: (index: number) => selectedMenuListItem.value[index],
})
</script>

// packages/react/src/components/drop-menu/DropMenu.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef, useState, type ReactNode } from 'react'
import { MdPopup } from '../popup/Popup'
import { MdRadioList, type RadioListOption } from '../radio-list/RadioList'

export interface DropMenuItem {
  text?: string
  disabled?: boolean
  options?: Array<{ value?: string | number; text?: string; label?: string }>
}

export interface DropMenuProps {
  data?: DropMenuItem[]
  defaultValue?: Array<string | number>
  children?: (slotProps: { option: RadioListOption }) => ReactNode
  onChange?: (barItem: DropMenuItem, listItem: Record<string, unknown>) => void
  onShow?: () => void
  onHide?: () => void
}

export interface DropMenuExposed {
  getSelectedValues: () => Array<Record<string, unknown> | undefined>
  getSelectedValue: (index: number) => Record<string, unknown> | undefined
}

export const MdDropMenu = forwardRef<DropMenuExposed, DropMenuProps>(function MdDropMenu(
  { data = [], defaultValue = [], children, onChange, onShow, onHide },
  ref,
) {
  const [isPopupShow, setIsPopupShow] = useState(false)
  const [selectedMenuListItem, setSelectedMenuListItem] = useState<Array<Record<string, unknown> | undefined>>([])
  const [selectedMenuListValue, setSelectedMenuListValue] = useState<Array<string | number>>([])
  const [activeMenuBarIndex, setActiveMenuBarIndex] = useState(-1)
  const [scroller, setScroller] = useState('')

  const hasSlot = !!children
  const activeMenuListData: RadioListOption[] =
    activeMenuBarIndex < 0 || !data[activeMenuBarIndex]
      ? []
      : ((data[activeMenuBarIndex].options ?? []) as unknown as RadioListOption[])

  function initSelectedBar(currentData: DropMenuItem[], currentDefault: Array<string | number>) {
    setSelectedMenuListValue(currentDefault)
    const found: Array<Record<string, unknown> | undefined> = []
    currentData.forEach((barItem, barItemIndex) => {
      const dv = currentDefault[barItemIndex]
      const options = (barItem.options ?? []) as unknown as Array<Record<string, unknown>>
      options.forEach((record) => {
        if (
          dv !== undefined &&
          (record.value === dv || record.text === dv || record.label === dv)
        ) {
          found[barItemIndex] = record
        }
      })
    })
    setSelectedMenuListItem(found)
  }

  // v2 mounted + watch data/defaultValue
  const initDataRef = useRef({ data, defaultValue })
  initDataRef.current = { data, defaultValue }
  const mountedRef = useRef(false)
  useEffect(() => {
    if (!mountedRef.current) {
      mountedRef.current = true
      initSelectedBar(data, defaultValue)
      return
    }
    const prev = initDataRef.current
    if (
      JSON.stringify(prev.data) !== JSON.stringify(data) ||
      JSON.stringify(prev.defaultValue) !== JSON.stringify(defaultValue)
    ) {
      initDataRef.current = { data, defaultValue }
      initSelectedBar(data, defaultValue)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data, defaultValue])

  function checkBarItemSelect(index: number) {
    return !!(selectedMenuListItem[index] !== undefined || defaultValue[index])
  }

  function getBarItemText(item: DropMenuItem, index: number) {
    const selected = selectedMenuListItem[index]
    return selected !== undefined ? String((selected as { text?: string }).text ?? '') : item.text
  }

  function onBarItemClick(barItem: DropMenuItem, index: number) {
    if (!barItem || barItem.disabled) {
      return
    }

    if (!isPopupShow) {
      setIsPopupShow(true)
      setActiveMenuBarIndex(index)
    } else {
      setIsPopupShow(false)
    }
  }

  function onListItemClick(listItem: RadioListOption) {
    const index = activeMenuBarIndex
    const barItem = data[index]
    setIsPopupShow(false)
    setSelectedMenuListValue((prev) => {
      const next = [...prev]
      next[index] = listItem.value as string | number
      return next
    })
    setSelectedMenuListItem((prev) => {
      const next = [...prev]
      next[index] = listItem as unknown as Record<string, unknown>
      return next
    })
    onChange?.(barItem, listItem as unknown as Record<string, unknown>)
  }

  useImperativeHandle(ref, () => ({
    getSelectedValues: () => selectedMenuListItem,
    getSelectedValue: (index: number) => selectedMenuListItem[index],
  }))

  return (
    <div className="md-drop-menu">
      <div className="md-drop-menu-bar">
        {data.map((item, index) => (
          <div
            key={index}
            className={`bar-item${index === activeMenuBarIndex ? ' active' : ''}${
              checkBarItemSelect(index) ? ' selected' : ''
            }${item.disabled ? ' disabled' : ''}`}
            onClick={() => onBarItemClick(item, index)}
          >
            <span>{getBarItemText(item, index)}</span>
          </div>
        ))}
      </div>
      <MdPopup
        value={isPopupShow}
        position="top"
        preventScroll
        preventScrollExclude={scroller}
        onShow={() => {
          // v2 $_setScroller：弹层高度超出时列表自滚
          setScroller('.md-drop-menu-list')
          onShow?.()
        }}
        onHide={onHide}
        onBeforeHide={() => setActiveMenuBarIndex(-1)}
      >
        <div className="md-drop-menu-list">
          <MdRadioList
            value={selectedMenuListValue[activeMenuBarIndex]}
            options={activeMenuListData}
            isSlotScope={hasSlot}
            alignCenter
            onChange={(option) => onListItemClick(option)}
          >
            {children}
          </MdRadioList>
        </div>
      </MdPopup>
    </div>
  )
})
