// packages/vue/src/components/landscape/Landscape.vue
<template>
  <div class="cu-landscape" :class="{ 'is-full': fullScreen }">
    <CuPopup
      v-model="isLandscapeShow"
      :mask-closable="maskClosable"
      prevent-scroll
      prevent-scroll-exclude=".cu-landscape-content"
      :has-mask="!fullScreen && hasMask"
      :transition="actualTransition"
      @update:model-value="onPopupInput"
      @show="$emit('show')"
      @hide="$emit('hide')"
    >
      <div class="cu-landscape-body" :class="{ scroll }">
        <div class="cu-landscape-content">
          <slot></slot>
        </div>
        <CuIcon
          class="cu-landscape-close"
          :class="{ dark: !hasMask || fullScreen }"
          :name="fullScreen ? 'clear' : 'close'"
          @click="close"
        />
      </div>
    </CuPopup>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import CuPopup from '../popup/Popup.vue'
import CuIcon from '../icon/Icon.vue'

defineOptions({ name: 'cu-landscape' })

const props = withDefaults(
  defineProps<{
    modelValue?: boolean
    scroll?: boolean
    fullScreen?: boolean
    hasMask?: boolean
    maskClosable?: boolean
    transition?: string
  }>(),
  {
    modelValue: false,
    scroll: false,
    fullScreen: false,
    hasMask: true,
    maskClosable: false,
    transition: undefined,
  },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
  (e: 'input', value: boolean): void
  (e: 'show'): void
  (e: 'hide'): void
}>()

const isLandscapeShow = ref(props.modelValue)

// v2 契约：默认过渡按 fullScreen 区分（cu-fade / cu-punch）
const actualTransition = computed(() => props.transition ?? (props.fullScreen ? 'cu-fade' : 'cu-punch'))

watch(
  () => props.modelValue,
  (val) => {
    isLandscapeShow.value = val
  },
)

function onPopupInput(val: boolean) {
  isLandscapeShow.value = val
  emit('update:modelValue', false)
  emit('input', false)
}

function close() {
  isLandscapeShow.value = false
}
</script>

// packages/react/src/components/landscape/Landscape.tsx
import { forwardRef, useEffect, useRef, useState, type ReactNode } from 'react'
import { CuPopup } from '../popup/Popup'
import { CuIcon } from '../icon/Icon'

export interface LandscapeProps {
  value?: boolean
  scroll?: boolean
  fullScreen?: boolean
  hasMask?: boolean
  maskClosable?: boolean
  transition?: string
  children?: ReactNode
  onShow?: () => void
  onHide?: () => void
}

export const CuLandscape = forwardRef<HTMLDivElement, LandscapeProps>(function CuLandscape(
  { value = false, scroll = false, fullScreen = false, hasMask = true, maskClosable = false, transition, children, onShow, onHide },
  ref,
) {
  const [isLandscapeShow, setIsLandscapeShow] = useState(value)

  // v2 watch value
  const prevValueRef = useRef(value)
  useEffect(() => {
    if (prevValueRef.current !== value) {
      prevValueRef.current = value
      setIsLandscapeShow(value)
    }
  }, [value])

  // v2 契约：默认过渡按 fullScreen 区分（cu-fade / cu-punch）
  const actualTransition = transition ?? (fullScreen ? 'cu-fade' : 'cu-punch')

  return (
    <div className={`cu-landscape${fullScreen ? ' is-full' : ''}`} ref={ref}>
      <CuPopup
        value={isLandscapeShow}
        maskClosable={maskClosable}
        preventScroll
        preventScrollExclude=".cu-landscape-content"
        hasMask={!fullScreen && hasMask}
        transition={actualTransition}
        onChange={(val) => {
          setIsLandscapeShow(val)
        }}
        onShow={onShow}
        onHide={onHide}
      >
        <div className={`cu-landscape-body${scroll ? ' scroll' : ''}`}>
          <div className="cu-landscape-content">{children}</div>
          <CuIcon
            className={`cu-landscape-close${!hasMask || fullScreen ? ' dark' : ''}`}
            name={fullScreen ? 'clear' : 'close'}
            onClick={() => setIsLandscapeShow(false)}
          />
        </div>
      </CuPopup>
    </div>
  )
})
