// packages/vue/src/components/scroll-view/ScrollViewRefresh.vue
<template>
  <div ref="el" class="md-scroll-view-refresh">
    <MdActivityIndicatorRolling :process="!isRefreshing ? process : undefined" :width="10" :color="rollerColor"></MdActivityIndicatorRolling>
    <p class="refresh-tip">{{ refreshTip }}</p>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { t } from '@mand-mobile/core'
import MdActivityIndicatorRolling from '../activity-indicator/Roller.vue'

defineOptions({ name: 'md-scroll-view-refresh' })

const props = withDefaults(
  defineProps<{
    scrollTop?: number
    isRefreshing?: boolean
    isRefreshActive?: boolean
    refreshText?: string
    refreshActiveText?: string
    refreshingText?: string
    rollerColor?: string
  }>(),
  {
    scrollTop: 0,
    isRefreshing: false,
    isRefreshActive: false,
    refreshText: undefined,
    refreshActiveText: undefined,
    refreshingText: undefined,
    rollerColor: '#2F86F6',
  },
)

const el = ref<HTMLElement>()

const process = computed(() => {
  if (!el.value || !props.scrollTop) {
    return +props.scrollTop
  }
  const refreshHeight = el.value.clientHeight
  if (Math.abs(props.scrollTop) < refreshHeight / 2) {
    return 0
  }
  // first 1/3 is not included in progress
  return (Math.abs(props.scrollTop) - refreshHeight / 2) / (refreshHeight / 2)
})

const refreshTip = computed(() => {
  if (props.isRefreshing) {
    return props.refreshingText ?? t('md.scroll_view.refresh.refreshing')
  } else if (props.isRefreshActive) {
    return props.refreshActiveText ?? t('md.scroll_view.refresh.freedRefresh')
  }
  return props.refreshText ?? t('md.scroll_view.refresh.pullDownRefresh')
})
</script>

// packages/react/src/components/scroll-view/ScrollViewRefresh.tsx
import { useEffect, useRef, useState } from 'react'
import { MdActivityIndicatorRolling } from '../activity-indicator/Roller'

export interface ScrollViewRefreshProps {
  scrollTop?: number
  isRefreshing?: boolean
  isRefreshActive?: boolean
  refreshText?: string
  refreshActiveText?: string
  refreshingText?: string
  rollerColor?: string
}

export function MdScrollViewRefresh({
  scrollTop = 0,
  isRefreshing = false,
  isRefreshActive = false,
  refreshText = '下拉刷新',
  refreshActiveText = '释放刷新',
  refreshingText = '刷新中...',
  rollerColor = '#2F86F6',
}: ScrollViewRefreshProps) {
  // v2 契约：process 需挂载后测量 clientHeight；首帧以 +scrollTop 参与
  const [elHeight, setElHeight] = useState<number | null>(null)
  const elRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (elRef.current) {
      setElHeight(elRef.current.clientHeight)
    }
  }, [])

  const process = (() => {
    if (isRefreshing) {
      return undefined
    }
    if (elHeight === null || elHeight <= 0 || !scrollTop) {
      return +scrollTop
    }
    if (Math.abs(scrollTop) < elHeight / 2) {
      return 0
    }
    return (Math.abs(scrollTop) - elHeight / 2) / (elHeight / 2)
  })()

  const refreshTip = isRefreshing
    ? refreshingText
    : isRefreshActive
      ? refreshActiveText
      : refreshText

  return (
    <div ref={elRef} className="md-scroll-view-refresh">
      <MdActivityIndicatorRolling
        process={process}
        width={10}
        color={rollerColor}
      />
      <p className="refresh-tip">{refreshTip}</p>
    </div>
  )
}

export interface ScrollViewMoreProps {
  loadingText?: string
  finishedText?: string
  isFinished?: boolean
}

export function MdScrollViewMore({
  loadingText = '更多加载中...',
  finishedText = '全部已加载',
  isFinished = false,
}: ScrollViewMoreProps) {
  return <div className="md-scroll-view-more">{isFinished ? finishedText : loadingText}</div>
}
