// packages/vue/src/components/field/Field.vue
<template>
  <fieldset class="md-field" :class="{ 'is-plain': plain, 'is-disabled': disabled }">
    <header v-if="title || brief || $slots.header || $slots.action" class="md-field-header">
      <div class="md-field-heading">
        <legend v-if="title" class="md-field-title" v-text="title"></legend>
        <p v-if="brief" class="md-field-brief" v-text="brief"></p>
        <slot name="header"></slot>
      </div>
      <div class="md-field-action">
        <slot name="action"></slot>
      </div>
    </header>
    <div class="md-field-content">
      <slot></slot>
    </div>
    <footer v-if="$slots.footer" class="md-field-footer">
      <slot name="footer"></slot>
    </footer>
  </fieldset>
</template>

<script setup lang="ts">
import { provide, reactive } from 'vue'

defineOptions({ name: 'md-field' })

const props = withDefaults(
  defineProps<{
    title?: string
    brief?: string
    disabled?: boolean
    plain?: boolean
  }>(),
  {
    title: '',
    brief: '',
    disabled: false,
    plain: false,
  },
)

// v2 契约：Field 向表单子组件（InputItem 等）暴露自身状态
provide(
  'rootField',
  reactive({
    get disabled() {
      return props.disabled
    },
  }),
)
</script>

// packages/react/src/components/field/Field.tsx
import { createContext, useContext, type ReactNode } from 'react'

export interface FieldContextValue {
  disabled?: boolean
}

export const FieldContext = createContext<FieldContextValue>({})

export function useFieldDisabled(disabled?: boolean): boolean {
  const field = useContext(FieldContext)
  return !!field.disabled || !!disabled
}

export interface FieldProps {
  title?: string
  brief?: string
  disabled?: boolean
  plain?: boolean
  header?: ReactNode
  action?: ReactNode
  footer?: ReactNode
  children?: ReactNode
}

export function MdField({
  title = '',
  brief = '',
  disabled = false,
  plain = false,
  header,
  action,
  footer,
  children,
}: FieldProps) {
  return (
    <FieldContext.Provider value={{ disabled }}>
      <fieldset
        className={`md-field${plain ? ' is-plain' : ''}${disabled ? ' is-disabled' : ''}`}
      >
        {title || brief || header || action ? (
          <header className="md-field-header">
            <div className="md-field-heading">
              {title ? <legend className="md-field-title">{title}</legend> : null}
              {brief ? <p className="md-field-brief">{brief}</p> : null}
              {header}
            </div>
            {action ? <div className="md-field-action">{action}</div> : null}
          </header>
        ) : null}
        <div className="md-field-content">{children}</div>
        {footer ? <footer className="md-field-footer">{footer}</footer> : null}
      </fieldset>
    </FieldContext.Provider>
  )
}
