// docs/src/components/demos/amount/index.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { MdAmount } from 'mand-mobile'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['千位分隔符', '变化动效', '大写中文']
const code = `<MdAmount :value="1234.125" :precision="3" />
<MdAmount :value="v" :precision="2" transition />
<MdAmount :value="1234.125" is-capital />`
const v = ref(1000)
onMounted(() => {
  setInterval(() => {
    v.value = Math.round(Math.random() * 10000)
  }, 2000)
})
</script>

<template>
  <DemoCanvas mode="stage" :scenes="scenes" :code="code">
    <template #scene-0>
      <MdAmount :value="1234.125" :precision="3" />
    </template>
    <template #scene-1>
      <MdAmount :value="v" :precision="2" transition />
    </template>
    <template #scene-2>
      <MdAmount :value="1234.125" is-capital />
    </template>
  </DemoCanvas>
</template>

// docs/src/components/demos-react/amount/index.tsx
import { useEffect, useState } from 'react'
import { MdAmount } from 'mand-mobile-react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['千位分隔符', '变化动效', '大写中文']
const code = `<MdAmount value={1234.125} precision={3} />
<MdAmount value={v} precision={2} transition />
<MdAmount value={1234.125} isCapital />`

export default function AmountDemo() {
  const [v, setV] = useState(1000)
  useEffect(() => {
    const t = setInterval(() => setV(Math.round(Math.random() * 10000)), 2000)
    return () => clearInterval(t)
  }, [])

  return (
    <DemoCanvasReact mode="stage" scenes={scenes} code={code}>
      {active => {
        if (active === 0) return <MdAmount value={1234.125} precision={3} />
        if (active === 1) return <MdAmount value={v} precision={2} transition />
        return <MdAmount value={1234.125} isCapital />
      }}
    </DemoCanvasReact>
  )
}
