// packages/react/src/components/activity-indicator/Spinning.tsx
import { MdIcon } from '../icon/Icon'

export interface SpinningProps {
  size?: number
  color?: string
}

export function MdSpinning({ size = 70, color = 'dark' }: SpinningProps) {
  return (
    <div className={`md-activity-indicator-spinning${color === 'dark' ? ' dark' : ''}`}>
      <MdIcon
        name="spinner"
        className="md-activity-indicator-svg"
        style={{ width: `${size}px`, height: `${size}px` }}
      />
    </div>
  )
}

// packages/vue/src/components/activity-indicator/Spinning.vue
<template>
  <div class="md-activity-indicator-spinning" :class="{ dark: color === 'dark' }">
    <MdIcon
      class="md-activity-indicator-svg"
      name="spinner"
      :style="{ width: `${size}px`, height: `${size}px` }"
    ></MdIcon>
  </div>
</template>

<script setup lang="ts">
import MdIcon from '../icon/Icon.vue'

defineOptions({ name: 'md-activity-indicator-spinning' })

withDefaults(
  defineProps<{
    size?: number
    color?: string
  }>(),
  {
    size: 70,
    color: 'dark',
  },
)
</script>
