// packages/vue/src/components/ruler/Ruler.vue
<template>
  <div
    class="md-ruler"
    @touchstart="startDrag"
    @touchend="stopDrag"
  >
    <canvas ref="canvas" class="md-ruler-canvas"></canvas>
    <div class="md-ruler-cursor" :class="[isStepTextBottom && 'md-ruler-cursor-bottom']"></div>
    <div class="md-ruler-arrow"></div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { Scroller } from '@mand-mobile/core/web'
import { throttle } from '@mand-mobile/core'

defineOptions({ name: 'md-ruler' })

const props = withDefaults(
  defineProps<{
    value?: number
    scope?: Array<number>
    step?: number
    unit?: number
    min?: number
    max?: number
    /** top | bottom */
    stepTextPosition?: 'top' | 'bottom'
    stepTextRender?: (step: number) => string | number | undefined | null
  }>(),
  {
    value: 0,
    scope: () => [0, 100],
    step: 10,
    unit: 1,
    min: 0,
    max: 100,
    stepTextPosition: 'top',
    stepTextRender: () => undefined,
  },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: number): void
  (e: 'input', value: number): void
  (e: 'change', value: number): void
}>()

const canvas = ref<HTMLCanvasElement>()

const CLIENT_HEIGHT = 60
const RATIO = 2
const BLANK = 30

let ctx: CanvasRenderingContext2D | null = null
let scroller: Scroller | null = null

const isInitialed = ref(false)
const isDragging = ref(false)
const isScrolling = ref(false)

const x = ref(0)
let scrollingX = 0

const unitCount = computed(() => Math.ceil((props.scope[1] - props.scope[0]) / props.unit))

const canvasWidth = computed(() => (canvas.value?.clientWidth ?? 0) * RATIO)

const realMin = computed(() => {
  const [left, right] = props.scope
  if (props.min > right) {
    return left
  }
  return props.min > left ? props.min : left
})

const realMax = computed(() => {
  const [left, right] = props.scope
  if (left > props.max) {
    return right
  }
  return props.max > right ? right : props.max
})

const blankLeft = computed(
  () => Math.ceil((realMin.value - props.scope[0]) / props.unit) * BLANK,
)

const blankRight = computed(
  () => Math.ceil((props.scope[1] - realMax.value) / props.unit) * BLANK,
)

const isStepTextBottom = computed(() => props.stepTextPosition === 'bottom')

watch(
  () => props.value,
  () => {
    if (isScrolling.value) {
      return
    }
    scrollingX = 0
    isScrolling.value = true
    const nextX = initX()
    draw(nextX)
    scroller?.scrollTo(nextX, 0, true)
  },
)

onMounted(() => {
  // jsdom 无 canvas 实现：ctx 为 null 时跳过绘制，仅保留交互骨架
  ctx = canvas.value?.getContext('2d') ?? null

  initCanvas()
  x.value = canvasWidth.value
  initScroller()
})

function initCanvas() {
  const cv = canvas.value
  if (!cv || !ctx) {
    return
  }
  cv.width = canvasWidth.value
  cv.height = CLIENT_HEIGHT * RATIO

  ctx.scale(1 / RATIO, 1)
}

function initScroller() {
  const drawThrottled = throttle((left: number) => draw(left), 10)
  const sc = new Scroller(
    (left) => {
      if (isInitialed.value) {
        drawThrottled(left)
      } else {
        draw(left)
      }
    },
    {
      scrollingX: true,
      scrollingY: false,
      snapping: true,
      snappingVelocity: 1,
      animationDuration: 200,
      inRequestAnimationFrame: true,
      scrollingComplete: () => {
        isScrolling.value = false
      },
    },
  )

  // 实际可滚动宽度
  const innerWidth = unitCount.value * BLANK + canvasWidth.value - blankLeft.value - blankRight.value
  const nextX = initX()
  draw(nextX)
  sc.setDimensions(canvasWidth.value, CLIENT_HEIGHT, innerWidth, CLIENT_HEIGHT)
  sc.setSnapSize(BLANK, 0)
  sc.scrollTo(nextX, 0, false)

  scroller = sc
  isInitialed.value = true
}

function initX() {
  const [min] = props.scope
  x.value = canvasWidth.value - Math.ceil((realMin.value - min) / props.unit) * BLANK

  if (props.value <= realMin.value) {
    return 0
  } else if (props.value >= realMax.value) {
    return unitCount.value * BLANK
  } else {
    return Math.ceil((props.value - realMin.value) / props.unit) * BLANK
  }
}

function draw(left: number) {
  if (!ctx) {
    return
  }
  left = +left.toFixed(2)

  scrollingX = left
  x.value += scrollingX - left

  // 清除画布
  const scale = RATIO * RATIO
  ctx.clearRect(0, 0, canvasWidth.value * scale, CLIENT_HEIGHT * scale)

  drawLine()
}

function drawLine() {
  if (!ctx) {
    return
  }
  const c = ctx
  const [scopeLeft] = props.scope

  const fontSize = 22
  const y = 120 - (isStepTextBottom.value ? fontSize + 40 : 0)
  const stepUnit = Math.round(props.step / props.unit)

  c.lineWidth = 2
  c.font = `${fontSize * RATIO}px DIDIFD-Medium, "Helvetica Neue",Helvetica,"PingFang SC","Hiragino Sans GB","Microsoft YaHei","微软雅黑",Arial,sans-serif`

  for (let i = 0; i <= unitCount.value; i++) {
    const cx = x.value + i * BLANK

    if (cx < 0 || cx > canvasWidth.value * 2) {
      continue
    }

    // 超出范围用另一色
    const outRange = cx < x.value + blankLeft.value || cx > x.value + 1 + unitCount.value * BLANK - blankRight.value
    if (outRange) {
      c.fillStyle = '#E2E4EA'
      c.strokeStyle = '#E2E4EA'
    } else {
      c.fillStyle = '#C5CAD5'
      c.strokeStyle = '#858B9C'
    }

    c.beginPath()
    c.moveTo(cx, y)

    if (i % stepUnit === 0) {
      // 刻度文本
      const text = matchStepText(scopeLeft + props.unit * i)
      const textOffset = (String(text).length * fontSize) / 2
      c.fillText(String(text), cx - textOffset, fontSize * RATIO + (isStepTextBottom.value ? 70 : 0))

      // 长刻度线
      c.lineTo(cx, y - 40)
    } else {
      c.lineTo(cx, y - 20)
    }
    c.stroke()
  }

  // 基线
  c.strokeStyle = '#E2E4EA'
  c.beginPath()
  c.moveTo(x.value, y)
  c.lineTo(x.value + unitCount.value * BLANK, y)
  c.stroke()

  updateValue()
}

function matchStepText(step: number) {
  const match = props.stepTextRender?.(step)
  return match !== undefined && match !== null ? match : step
}

let touchDragging = false
function startDrag(event: TouchEvent) {
  if (isDragging.value || touchDragging) {
    return
  }

  event.preventDefault()
  event.stopPropagation()
  scroller?.doTouchStart(Array.from(event.touches), event.timeStamp)

  isDragging.value = true
  touchDragging = true
  isScrolling.value = true

  const onDrag = (e: TouchEvent) => {
    e.preventDefault()
    e.stopPropagation()
    if (!isDragging.value) {
      return
    }
    scroller?.doTouchMove(Array.from(e.touches), e.timeStamp, (e as TouchEvent & { scale?: number }).scale)
  }
  const onStop = (e: TouchEvent) => {
    e.preventDefault()
    e.stopPropagation()
    isDragging.value = false
    touchDragging = false

    scroller?.doTouchEnd(e.timeStamp)

    window.removeEventListener('touchmove', onDrag)
    window.removeEventListener('touchend', onStop)
  }
  window.addEventListener('touchmove', onDrag)
  window.addEventListener('touchend', onStop)
}
// 兼容 v2 stopDrag 命名（模板 touchend 未绑定，实际由 window 监听处理）
const stopDrag = (event: TouchEvent) => {
  event.preventDefault()
}

function updateValue() {
  if (!isInitialed.value) {
    return
  }

  const [min] = props.scope

  if (x.value > canvasWidth.value) {
    onInput(realMin.value)
    return
  }

  const absX = x.value >= 0 ? Math.abs(x.value - canvasWidth.value) : Math.abs(x.value) + canvasWidth.value
  let value = min + Math.round(absX / BLANK) * props.unit

  value > realMax.value && (value = realMax.value)
  value < realMin.value && (value = realMin.value)
  onInput(value)
}

function onInput(value: number) {
  emit('update:modelValue', value)
  emit('input', value)
  emit('change', value)
}
</script>

// packages/react/src/components/ruler/Ruler.tsx
import { forwardRef, useEffect, useRef, useState } from 'react'
import { Scroller } from '@mand-mobile/core/web'
import { throttle } from '@mand-mobile/core'

export interface RulerProps {
  value?: number
  scope?: number[]
  step?: number
  unit?: number
  min?: number
  max?: number
  /** top | bottom */
  stepTextPosition?: 'top' | 'bottom'
  stepTextRender?: (step: number) => string | number | undefined | null
  onChange?: (value: number) => void
}

const CLIENT_HEIGHT = 60
const RATIO = 2
const BLANK = 30

export const MdRuler = forwardRef<HTMLDivElement, RulerProps>(function MdRuler(
  {
    value = 0,
    scope = [0, 100],
    step = 10,
    unit = 1,
    min = 0,
    max = 100,
    stepTextPosition = 'top',
    stepTextRender,
    onChange,
  },
  ref,
) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const ctxRef = useRef<CanvasRenderingContext2D | null>(null)
  const scrollerRef = useRef<Scroller | null>(null)

  // v2 用实例字段记录拖拽/滚动状态（window 监听器需读实时值）
  const isDraggingRef = useRef(false)
  const isInitialedRef = useRef(false)
  const isInitialed = false
  const [isScrolling, setIsScrolling] = useState(false)
  const isScrollingRef = useRef(isScrolling)
  isScrollingRef.current = isScrolling

  const xRef = useRef(0)
  const scrollingXRef = useRef(0)

  const stateRef = useRef({ scope, step, unit, min, max, stepTextPosition, stepTextRender, onChange })
  stateRef.current = { scope, step, unit, min, max, stepTextPosition, stepTextRender, onChange }

  const unitCount = Math.ceil((scope[1] - scope[0]) / unit)
  const canvasWidth = (canvasRef.current?.clientWidth ?? 0) * RATIO

  const realMin = (() => {
    const [left, right] = scope
    if (min > right) {
      return left
    }
    return min > left ? min : left
  })()

  const realMax = (() => {
    const [left, right] = scope
    if (left > max) {
      return right
    }
    return max > right ? right : max
  })()

  const blankLeft = Math.ceil((realMin - scope[0]) / unit) * BLANK
  const blankRight = Math.ceil((scope[1] - realMax) / unit) * BLANK
  const isStepTextBottom = stepTextPosition === 'bottom'

  // v2 watch value：非滚动状态下重绘定位
  const prevValueRef = useRef(value)
  useEffect(() => {
    if (prevValueRef.current !== value) {
      prevValueRef.current = value
      if (isScrollingRef.current) {
        return
      }
      scrollingXRef.current = 0
      setIsScrolling(true)
      const nextX = initXRef.current()
      drawRef.current(nextX)
      scrollerRef.current?.scrollTo(nextX, 0, true)
    }
  }, [value])

  useEffect(() => {
    // jsdom 无 canvas 实现：ctx 为 null 时跳过绘制，仅保留交互骨架
    ctxRef.current = canvasRef.current?.getContext('2d') ?? null

    if (ctxRef.current) {
      const cv = canvasRef.current!
      cv.width = canvasWidth
      cv.height = CLIENT_HEIGHT * RATIO
      ctxRef.current.scale(1 / RATIO, 1)
    }

    xRef.current = canvasWidth

    const sc = new Scroller(
      (left) => {
        if (isInitialed) {
          drawThrottledRef.current(left)
        } else {
          drawRef.current(left)
        }
      },
      {
        scrollingX: true,
        scrollingY: false,
        snapping: true,
        snappingVelocity: 1,
        animationDuration: 200,
        inRequestAnimationFrame: true,
        scrollingComplete: () => {
          setIsScrolling(false)
        },
      },
    )

    const innerWidth = unitCount * BLANK + canvasWidth - blankLeft - blankRight
    const nextX = initXRef.current()
    drawRef.current(nextX)
    sc.setDimensions(canvasWidth, CLIENT_HEIGHT, innerWidth, CLIENT_HEIGHT)
    sc.setSnapSize(BLANK, 0)
    sc.scrollTo(nextX, 0, false)

    scrollerRef.current = sc
    isInitialedRef.current = true
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const initXRef = useRef<() => number>(() => 0)
  initXRef.current = () => {
    const { stepTextRender: _s, onChange: _o, ...rest } = stateRef.current
    const [scopeMin] = rest.scope
    const uc = Math.ceil((rest.scope[1] - rest.scope[0]) / rest.unit)
    const cw = (canvasRef.current?.clientWidth ?? 0) * RATIO
    const rMin = (() => {
      const [left, right] = rest.scope
      if (rest.min > right) {
        return left
      }
      return rest.min > left ? rest.min : left
    })()
    const rMax = (() => {
      const [left, right] = rest.scope
      if (left > rest.max) {
        return right
      }
      return rest.max > right ? right : rest.max
    })()

    xRef.current = cw - Math.ceil((rMin - scopeMin) / rest.unit) * BLANK

    if (value <= rMin) {
      return 0
    } else if (value >= rMax) {
      return uc * BLANK
    } else {
      return Math.ceil((value - rMin) / rest.unit) * BLANK
    }
  }

  const drawRef = useRef<(left: number) => void>(() => {})
  drawRef.current = (leftRaw: number) => {
    const ctx = ctxRef.current
    if (!ctx) {
      return
    }
    const left = +leftRaw.toFixed(2)
    const cw = (canvasRef.current?.clientWidth ?? 0) * RATIO

    scrollingXRef.current = left
    xRef.current += scrollingXRef.current - left

    const scale = RATIO * RATIO
    ctx.clearRect(0, 0, cw * scale, CLIENT_HEIGHT * scale)

    drawLine()
  }

  const drawThrottledRef = useRef<(left: number) => void>(() => {})
  drawThrottledRef.current = (left: number) => {
    throttleRefHelper(left)
  }
  const throttleRefHelper = (left: number) => {
    throttledDraw(left)
  }
  const throttledDraw = throttle((left: number) => drawRef.current(left), 10)

  function drawLine() {
    const ctx = ctxRef.current
    if (!ctx) {
      return
    }
    const { scope: scopeProp, step: stepProp, unit: unitProp, stepTextRender: render } = stateRef.current
    const [scopeLeft] = scopeProp

    const fontSize = 22
    const bottom = stepTextPosition === 'bottom'
    const y = 120 - (bottom ? fontSize + 40 : 0)
    const stepUnit = Math.round(stepProp / unitProp)
    const cw = (canvasRef.current?.clientWidth ?? 0) * RATIO

    ctx.lineWidth = 2
    ctx.font = `${fontSize * RATIO}px DIDIFD-Medium, "Helvetica Neue",Helvetica,"PingFang SC","Hiragino Sans GB","Microsoft YaHei","微软雅黑",Arial,sans-serif`

    for (let i = 0; i <= unitCount; i++) {
      const cx = xRef.current + i * BLANK

      if (cx < 0 || cx > cw * 2) {
        continue
      }

      const outRange = cx < xRef.current + blankLeft || cx > xRef.current + 1 + unitCount * BLANK - blankRight
      if (outRange) {
        ctx.fillStyle = '#E2E4EA'
        ctx.strokeStyle = '#E2E4EA'
      } else {
        ctx.fillStyle = '#C5CAD5'
        ctx.strokeStyle = '#858B9C'
      }

      ctx.beginPath()
      ctx.moveTo(cx, y)

      if (i % stepUnit === 0) {
        const stepValue = scopeLeft + unitProp * i
        const match = render?.(stepValue)
        const text = match !== undefined && match !== null ? match : stepValue
        const textOffset = (String(text).length * fontSize) / 2
        ctx.fillText(String(text), cx - textOffset, fontSize * RATIO + (bottom ? 70 : 0))

        ctx.lineTo(cx, y - 40)
      } else {
        ctx.lineTo(cx, y - 20)
      }
      ctx.stroke()
    }

    ctx.strokeStyle = '#E2E4EA'
    ctx.beginPath()
    ctx.moveTo(xRef.current, y)
    ctx.lineTo(xRef.current + unitCount * BLANK, y)
    ctx.stroke()

    updateValue()
  }

  function updateValue() {
    if (!isInitialedRef.current) {
      return
    }
    const { scope: scopeProp, onChange: cb } = stateRef.current
    const [scopeMin] = scopeProp

    if (xRef.current > canvasWidth) {
      cb?.(realMin)
      return
    }

    const absX = xRef.current >= 0 ? Math.abs(xRef.current - canvasWidth) : Math.abs(xRef.current) + canvasWidth
    let value0 = scopeMin + Math.round(absX / BLANK) * unit
    value0 > realMax && (value0 = realMax)
    value0 < realMin && (value0 = realMin)
    cb?.(value0)
  }

  const dragState = useRef({ onDrag: null as null | ((e: TouchEvent) => void), onStop: null as null | ((e: TouchEvent) => void) })

  const startDrag = (event: React.TouchEvent) => {
    if (isDraggingRef.current) {
      return
    }
    event.preventDefault()
    event.stopPropagation()
    scrollerRef.current?.doTouchStart(
      event.touches ? Array.from(event.touches) : [],
      event.timeStamp,
    )

    isDraggingRef.current = true
    setIsScrolling(true)

    const onDrag = (e: TouchEvent) => {
      e.preventDefault()
      e.stopPropagation()
      if (!isDraggingRef.current) {
        return
      }
      scrollerRef.current?.doTouchMove(
        Array.from(e.touches),
        e.timeStamp,
        (e as TouchEvent & { scale?: number }).scale,
      )
    }
    const onStop = (e: TouchEvent) => {
      e.preventDefault()
      e.stopPropagation()
      isDraggingRef.current = false
      scrollerRef.current?.doTouchEnd(e.timeStamp)
      window.removeEventListener('touchmove', onDrag)
      window.removeEventListener('touchend', onStop)
    }
    dragState.current.onDrag = onDrag
    dragState.current.onStop = onStop
    window.addEventListener('touchmove', onDrag)
    window.addEventListener('touchend', onStop)
  }

  return (
    <div className="md-ruler" ref={ref} onTouchStart={startDrag}>
      <canvas ref={canvasRef} className="md-ruler-canvas"></canvas>
      <div className={`md-ruler-cursor${isStepTextBottom ? ' md-ruler-cursor-bottom' : ''}`}></div>
      <div className="md-ruler-arrow"></div>
    </div>
  )
})
