// packages/react/src/components/cashier/Cashier.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef, useState, type ReactNode } from 'react'
import { t } from '@mand-mobile/core'
import { MdPopup } from '../popup/Popup'
import { MdPopupTitleBar } from '../popup/PopupTitleBar'
import { MdCaptcha } from '../captcha/Captcha'
import { MdIcon } from '../icon/Icon'
import { MdRollerSuccess } from '../activity-indicator/RollerSuccess'
import { MdCashierChannel, type CashierChannel } from './CashierChannel'
import { MdCashierChannelButton, type CashierAction } from './CashierChannelButton'

export type CashierScene = 'choose' | 'captcha' | 'loading' | 'success' | 'fail' | 'custom'

export interface CashierProps {
  value?: boolean
  channels?: CashierChannel[]
  channelLimit?: number
  defaultIndex?: number
  paymentTitle?: string
  paymentAmount?: string
  paymentDescribe?: string
  payButtonText?: string
  payButtonDisabled?: boolean
  moreButtonText?: string
  title?: string
  describe?: string
  largeRadius?: boolean
  headerSlot?: (scene: CashierScene) => ReactNode
  channelSlot?: ReactNode
  payButtonSlot?: ReactNode
  sceneSlot?: ReactNode
  footerSlot?: (scene: CashierScene) => ReactNode
  onChange?: (value: boolean) => void
  onSelect?: (item: CashierChannel) => void
  onPay?: (item: CashierChannel) => void
  onShow?: () => void
  onHide?: () => void
  onCancel?: () => void
}

export interface CashierSceneOption {
  loading?: { text?: string }
  success?: { text?: string; buttonText?: string; handler?: () => void; actions?: CashierAction[] }
  fail?: { text?: string; buttonText?: string; handler?: () => void; actions?: CashierAction[] }
  captcha?: {
    text?: string
    brief?: string
    maxlength?: number
    count?: number
    autoCountdown?: boolean
    countNormalText?: string
    countActiveText?: string
    onSend?: () => void
    onSubmit?: (code: string) => void
  }
}

export const MdCashier = forwardRef<
  { next: (scene: CashierScene, option?: CashierSceneOption) => void },
  CashierProps
>(function MdCashier(
  {
    value = false,
    channels = [],
    channelLimit = 2,
    defaultIndex = 0,
    paymentTitle = t('md.cashier.payCash'),
    paymentAmount = '0.00',
    paymentDescribe = '',
    payButtonText = t('md.cashier.confirmPay'),
    payButtonDisabled = false,
    moreButtonText = t('md.cashier.morePayWays'),
    title = t('md.cashier.pay'),
    describe = '',
    largeRadius = false,
    headerSlot,
    channelSlot,
    payButtonSlot,
    sceneSlot,
    footerSlot,
    onChange,
    onSelect,
    onPay,
    onShow,
    onHide,
    onCancel,
  },
  ref,
) {
  const [isCashierShow, setIsCashierShow] = useState(value)
  const [scene, setScene] = useState<CashierScene>('choose')
  const [sceneKey, setSceneKey] = useState(() => Date.now())
  const sceneOptionRef = useRef<{
    loading: { text: string }
    success: { text: string; buttonText: string; handler?: () => void; actions?: CashierAction[] }
    fail: { text: string; buttonText: string; handler?: () => void; actions?: CashierAction[] }
    captcha: {
      text: string
      brief: string
      maxlength: number
      count: number
      autoCountdown: boolean
      countNormalText?: string
      countActiveText?: string
      onSend: () => void
      onSubmit: (code: string) => void
    }
  }>({
    loading: { text: t('md.cashier.payResultSearch') },
    success: {
      text: t('md.cashier.paySuccess'),
      buttonText: t('md.cashier.confirm'),
      handler: undefined,
    },
    fail: {
      text: t('md.cashier.payFail'),
      buttonText: t('md.cashier.confirm'),
      handler: undefined,
    },
    captcha: {
      text: '',
      brief: '',
      maxlength: 4,
      count: 60,
      autoCountdown: true,
      onSend: () => {},
      onSubmit: () => {},
    },
  })

  // v2 watch value / isCashierShow
  const prevValueRef = useRef(value)
  useEffect(() => {
    if (prevValueRef.current !== value) {
      prevValueRef.current = value
      setIsCashierShow(value)
    }
  }, [value])

  const prevShowRef = useRef(isCashierShow)
  const onChangeRef = useRef(onChange)
  onChangeRef.current = onChange
  useEffect(() => {
    if (prevShowRef.current !== isCashierShow) {
      prevShowRef.current = isCashierShow
      onChangeRef.current?.(isCashierShow)
    }
  }, [isCashierShow])

  useImperativeHandle(ref, () => ({
    next: (nextScene, option = {}) => {
      const target = (sceneOptionRef.current as unknown as Record<string, unknown>)[nextScene]
      if (target) {
        Object.assign(target, option)
      }
      setScene(nextScene)
      setSceneKey(Date.now())
    },
  }))

  const captcha = sceneOptionRef.current.captcha

  return (
    <div className="md-cashier">
      <MdPopup
        className="inner-popup"
        value={isCashierShow}
        position="bottom"
        maskClosable={false}
        preventScrollExclude=".choose-channel"
        preventScroll
        onShow={() => onShow?.()}
        onHide={() => {
          setScene('choose')
          onHide?.()
        }}
      >
        <MdPopupTitleBar
          title={title}
          describe={describe}
          largeRadius={largeRadius}
          onlyClose
          onCancel={() => {
            setIsCashierShow(false)
            onCancel?.()
          }}
        />
        <div className="md-cashier-container">
          {headerSlot ? headerSlot(scene) : null}

          {scene === 'choose' ? (
            <div key={sceneKey} className="md-cashier-block md-cashier-choose">
              <MdCashierChannel
                paymentTitle={paymentTitle}
                paymentAmount={paymentAmount}
                paymentDescribe={paymentDescribe}
                moreButtonText={moreButtonText}
                payButtonText={payButtonText}
                payButtonDisabled={payButtonDisabled}
                channels={channels}
                channelLimit={channelLimit}
                defaultIndex={defaultIndex}
                channelSlot={channelSlot}
                buttonSlot={payButtonSlot}
                onSelect={onSelect}
                onPay={onPay}
              />
            </div>
          ) : scene === 'captcha' ? (
            <div key={sceneKey} className="md-cashier-block md-cashier-captcha">
              <MdCaptcha
                maxlength={captcha.maxlength}
                count={captcha.count}
                countNormalText={captcha.countNormalText}
                countActiveText={captcha.countActiveText}
                autoCountdown={captcha.autoCountdown}
                brief={captcha.brief}
                isView
                onSend={() => captcha.onSend()}
                onSubmit={code => captcha.onSubmit(code)}
              >
                <div>{captcha.text}</div>
              </MdCaptcha>
            </div>
          ) : scene === 'loading' || scene === 'success' ? (
            <div
              key={sceneKey}
              className={`md-cashier-block${scene === 'loading' ? ' md-cashier-loading' : ''}${
                scene === 'success' ? ' md-cashier-success' : ''
              }`}
            >
              <div className="md-cashier-block-icon">
                <MdRollerSuccess isSuccess={scene === 'success'} />
              </div>
              <div className="md-cashier-block-text">
                {scene === 'success' ? sceneOptionRef.current.success.text : sceneOptionRef.current.loading.text}
              </div>
              {scene === 'success' ? (
                <MdCashierChannelButton
                  actions={
                    sceneOptionRef.current.success.actions || [
                      {
                        buttonText: sceneOptionRef.current.success.buttonText,
                        handler: sceneOptionRef.current.success.handler,
                      },
                    ]
                  }
                />
              ) : null}
            </div>
          ) : scene === 'fail' ? (
            <div key={sceneKey} className="md-cashier-block md-cashier-fail">
              <div className="md-cashier-block-icon">
                <MdIcon name="warn-color" />
              </div>
              <div className="md-cashier-block-text">{sceneOptionRef.current.fail.text}</div>
              <MdCashierChannelButton
                actions={
                  sceneOptionRef.current.fail.actions || [
                    {
                      buttonText: sceneOptionRef.current.fail.buttonText,
                      handler: sceneOptionRef.current.fail.handler,
                    },
                  ]
                }
              />
            </div>
          ) : scene === 'custom' ? (
            <div key={sceneKey} className="md-cashier-block md-cashier-custom">
              {sceneSlot}
            </div>
          ) : null}

          {footerSlot ? footerSlot(scene) : null}
        </div>
      </MdPopup>
    </div>
  )
})

// packages/vue/src/components/cashier/Cashier.vue
<template>
  <div class="md-cashier">
    <MdPopup
      class="inner-popup"
      v-model="isCashierShow"
      position="bottom"
      :mask-closable="false"
      prevent-scroll-exclude=".choose-channel"
      prevent-scroll
      @show="$emit('show')"
      @hide="onPopupHide"
    >
      <MdPopupTitleBar
        :title="title"
        :describe="describe"
        :large-radius="largeRadius"
        only-close
        @cancel="onPopupCancel"
      ></MdPopupTitleBar>
      <div class="md-cashier-container">
        <slot name="header" :scene="scene"></slot>

        <!-- 选择支付渠道 -->
        <div v-if="scene === 'choose'" :key="sceneKey" class="md-cashier-block md-cashier-choose">
          <MdCashierChannel
            :payment-title="paymentTitle"
            :payment-amount="paymentAmount"
            :payment-describe="paymentDescribe"
            :more-button-text="moreButtonText"
            :pay-button-text="payButtonText"
            :pay-button-disabled="payButtonDisabled"
            :channels="channels"
            :channel-limit="channelLimit"
            :default-index="defaultIndex"
            @select="$emit('select', $event)"
            @pay="$emit('pay', $event)"
          >
            <slot name="channel"></slot>
            <template #button>
              <slot name="payButton"></slot>
            </template>
          </MdCashierChannel>
        </div>

        <!-- 验证码 -->
        <div v-else-if="scene === 'captcha'" :key="sceneKey" class="md-cashier-block md-cashier-captcha">
          <MdCaptcha
            :maxlength="sceneOption.captcha.maxlength"
            :count="sceneOption.captcha.count"
            :count-normal-text="sceneOption.captcha.countNormalText"
            :count-active-text="sceneOption.captcha.countActiveText"
            :auto-countdown="sceneOption.captcha.autoCountdown"
            :brief="sceneOption.captcha.brief"
            is-view
            @send="sceneOption.captcha.onSend"
            @submit="sceneOption.captcha.onSubmit"
          >
            <div v-text="sceneOption.captcha.text"></div>
          </MdCaptcha>
        </div>

        <!-- 加载中 / 成功 -->
        <div
          v-else-if="scene === 'loading' || scene === 'success'"
          :key="sceneKey"
          class="md-cashier-block"
          :class="{
            'md-cashier-loading': scene === 'loading',
            'md-cashier-success': scene === 'success',
          }"
        >
          <div class="md-cashier-block-icon">
            <MdRollerSuccess ref="rolling" :is-success="scene === 'success'"></MdRollerSuccess>
          </div>
          <div class="md-cashier-block-text">
            {{ scene === 'success' ? sceneOption.success.text : sceneOption.loading.text }}
          </div>
          <MdCashierChannelButton
            v-if="scene === 'success'"
            :actions="
              sceneOption.success.actions || [
                {
                  buttonText: sceneOption.success.buttonText,
                  handler: sceneOption.success.handler,
                },
              ]
            "
          />
        </div>

        <!-- 失败 -->
        <div v-else-if="scene === 'fail'" :key="sceneKey" class="md-cashier-block md-cashier-fail">
          <div class="md-cashier-block-icon">
            <MdIcon name="warn-color"></MdIcon>
          </div>
          <div class="md-cashier-block-text" v-text="sceneOption.fail.text"></div>
          <MdCashierChannelButton
            :actions="
              sceneOption.fail.actions || [
                {
                  buttonText: sceneOption.fail.buttonText,
                  handler: sceneOption.fail.handler,
                },
              ]
            "
          />
        </div>

        <!-- 自定义 -->
        <div v-else-if="scene === 'custom'" :key="sceneKey" class="md-cashier-block md-cashier-custom">
          <slot name="scene"></slot>
        </div>

        <slot name="footer" :scene="scene"></slot>
      </div>
    </MdPopup>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { t } from '@mand-mobile/core'
import MdPopup from '../popup/Popup.vue'
import MdPopupTitleBar from '../popup/PopupTitleBar.vue'
import MdCaptcha from '../captcha/Captcha.vue'
import MdIcon from '../icon/Icon.vue'
import MdRollerSuccess from '../activity-indicator/RollerSuccess.vue'
import MdCashierChannel, { type CashierChannel } from './CashierChannel.vue'
import MdCashierChannelButton from './CashierChannelButton.vue'

defineOptions({ name: 'md-cashier' })

export type CashierScene = 'choose' | 'captcha' | 'loading' | 'success' | 'fail' | 'custom'

export interface CashierSceneOption {
  loading: { text: string }
  success: { text: string; buttonText: string; handler: (() => void) | null; actions?: never }
  fail: { text: string; buttonText: string; handler: (() => void) | null; actions?: never }
  captcha: {
    text: string
    brief: string
    maxlength: number
    count: number
    autoCountdown: boolean
    countNormalText?: string
    countActiveText?: string
    onSend: () => void
    onSubmit: (code: string) => void
  }
}

const props = withDefaults(
  defineProps<{
    modelValue?: boolean
    channels?: CashierChannel[]
    channelLimit?: number
    defaultIndex?: number
    paymentTitle?: string
    paymentAmount?: string
    paymentDescribe?: string
    payButtonText?: string
    payButtonDisabled?: boolean
    moreButtonText?: string
    title?: string
    describe?: string
    largeRadius?: boolean
  }>(),
  {
    modelValue: false,
    channels: () => [],
    channelLimit: 2,
    defaultIndex: 0,
    paymentTitle: () => t('md.cashier.payCash'),
    paymentAmount: '0.00',
    paymentDescribe: '',
    payButtonText: () => t('md.cashier.confirmPay'),
    payButtonDisabled: false,
    moreButtonText: () => t('md.cashier.morePayWays'),
    title: () => t('md.cashier.pay'),
    describe: '',
    largeRadius: false,
  },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
  (e: 'select', item: CashierChannel): void
  (e: 'pay', item: CashierChannel): void
  (e: 'show'): void
  (e: 'hide'): void
  (e: 'cancel'): void
}>()

const isCashierShow = ref(props.modelValue)
const scene = ref<CashierScene>('choose')
const sceneKey = ref(Date.now())
const sceneOption = ref<CashierSceneOption>({
  loading: { text: t('md.cashier.payResultSearch') },
  success: {
    text: t('md.cashier.paySuccess'),
    buttonText: t('md.cashier.confirm'),
    handler: null,
  },
  fail: {
    text: t('md.cashier.payFail'),
    buttonText: t('md.cashier.confirm'),
    handler: null,
  },
  captcha: {
    text: '',
    brief: '',
    maxlength: 4,
    count: 60,
    autoCountdown: true,
    onSend: () => {},
    onSubmit: () => {},
  },
})

watch(
  () => props.modelValue,
  val => {
    isCashierShow.value = val
  },
)
watch(isCashierShow, val => {
  emit('update:modelValue', val)
})

function onPopupHide() {
  resetCashier()
  emit('hide')
}

function onPopupCancel() {
  isCashierShow.value = false
  emit('cancel')
}

function resetCashier() {
  scene.value = 'choose'
}

// MARK: public methods
function next(nextScene: CashierScene, option: Record<string, unknown> = {}) {
  if ((sceneOption.value as unknown as Record<string, unknown>)[nextScene]) {
    const target = (sceneOption.value as unknown as Record<string, unknown>)[nextScene] as Record<string, unknown>
    Object.assign(target, option)
  }
  scene.value = nextScene
  sceneKey.value = Date.now()
}

defineExpose({ next })
</script>
