// packages/react/src/components/cashier/CashierChannelItem.tsx
import { CuIcon } from '../icon/Icon'

export interface CashierChannelItemData {
  icon?: string
  img?: string
  text?: string
  desc?: string
  disabled?: boolean
  action?: { text: string; handler: () => void }
}

export function CuCashierChannelItem({
  data = {},
  active = false,
  className,
  onClick,
}: {
  data?: CashierChannelItemData
  active?: boolean
  className?: string
  onClick?: () => void
}) {
  return (
    <div
      className={`cu-cashier-channel-item${className ? ` ${className}` : ''}`}
      onClick={onClick}
    >
      {data.icon ? (
        <div className="item-icon" data-icon={data.icon}>
          <CuIcon name={data.icon} size="lg" />
        </div>
      ) : data.img ? (
        <div className="item-image">
          <img src={data.img} />
        </div>
      ) : null}
      <div className="item-label">
        <p className="title">
          <span dangerouslySetInnerHTML={{ __html: data.text ?? '' }} />
          {data.action ? (
            <span
              className="title-active"
              dangerouslySetInnerHTML={{ __html: data.action.text }}
              onClick={e => {
                e.stopPropagation()
                data.action?.handler()
              }}
            />
          ) : null}
        </p>
        {data.desc ? <p className="desc" dangerouslySetInnerHTML={{ __html: data.desc }} /> : null}
      </div>
      <div className="item-check-icon">
        {data.disabled ? <CuIcon name="check-disabled" /> : active ? <CuIcon name="checked" /> : <CuIcon name="check" />}
      </div>
    </div>
  )
}

// packages/vue/src/components/cashier/CashierChannelItem.vue
<template>
  <div class="cu-cashier-channel-item">
    <div v-if="data.icon" class="item-icon" :class="data.icon">
      <CuIcon :name="data.icon" size="lg"></CuIcon>
    </div>
    <div v-else-if="data.img" class="item-image">
      <img :src="data.img" />
    </div>
    <div class="item-label">
      <p class="title">
        <span v-html="data.text || data"></span>
        <span
          v-if="data.action"
          class="title-active"
          v-html="data.action.text"
          @click.stop="data.action.handler"
        ></span>
      </p>
      <p v-if="data.desc" class="desc" v-html="data.desc"></p>
    </div>
    <div class="item-check-icon">
      <CuIcon v-if="data.disabled" name="check-disabled"></CuIcon>
      <CuIcon v-else-if="active" name="checked"></CuIcon>
      <CuIcon v-else name="check"></CuIcon>
    </div>
  </div>
</template>

<script setup lang="ts">
import CuIcon from '../icon/Icon.vue'

defineOptions({ name: 'cu-cashier-channel-item' })

const props = withDefaults(
  defineProps<{
    data?: {
      icon?: string
      img?: string
      text?: string
      desc?: string
      disabled?: boolean
      action?: { text: string; handler: () => void }
    }
    active?: boolean
  }>(),
  { data: () => ({}), active: false },
)
void props
</script>
