// packages/react/src/components/cashier/CashierChannelButton.tsx
import { CuButton } from '../button/Button'

export interface CashierAction {
  buttonText?: string
  handler?: () => void
}

export function CuCashierChannelButton({ actions = [] }: { actions?: CashierAction[] }) {
  return (
    <div className="cu-cashier-block-btn">
      {actions.map((action, index) => (
        <CuButton
          key={index}
          type={index === actions.length - 1 ? 'primary' : 'default'}
          inline={actions.length > 1}
          onClick={() => action.handler && action.handler()}
        >
          {action.buttonText}
        </CuButton>
      ))}
    </div>
  )
}

// packages/vue/src/components/cashier/CashierChannelButton.vue
<template>
  <div class="cu-cashier-block-btn">
    <CuButton
      v-for="(action, index) in actions"
      :key="index"
      :type="index === actions.length - 1 ? 'primary' : 'default'"
      :inline="actions.length > 1"
      @click="() => action.handler && action.handler()"
    >
      {{ action.buttonText }}
    </CuButton>
  </div>
</template>

<script setup lang="ts">
import CuButton from '../button/Button.vue'

defineOptions({ name: 'cu-cashier-channel-button' })

withDefaults(
  defineProps<{
    actions?: Array<{ buttonText?: string; handler?: (() => void) | null }>
  }>(),
  { actions: () => [] },
)
</script>
