// packages/react/src/components/cashier/CashierChannel.tsx
import { useState, type ReactNode } from 'react'
import { CuButton } from '../button/Button'
import { CuCashierChannelItem } from './CashierChannelItem'
import type { CashierChannelItemData } from './CashierChannelItem'

export interface CashierChannel {
  text?: string
  desc?: string
  img?: string
  icon?: string
  value?: string
  disabled?: boolean
  action?: { text: string; handler: () => void }
}

export interface CashierChannelProps {
  paymentTitle?: string
  paymentAmount?: string
  paymentDescribe?: string
  moreButtonText?: string
  payButtonText?: string
  payButtonDisabled?: boolean
  channels?: CashierChannel[]
  channelLimit?: number
  defaultIndex?: number
  channelSlot?: ReactNode
  buttonSlot?: ReactNode
  onSelect?: (item: CashierChannel) => void
  onPay?: (item: CashierChannel) => void
}

export function CuCashierChannel({
  paymentTitle = '',
  paymentAmount = '',
  paymentDescribe = '',
  moreButtonText = '',
  payButtonText = '',
  payButtonDisabled = false,
  channels = [],
  channelLimit = 2,
  defaultIndex = 0,
  channelSlot,
  buttonSlot,
  onSelect,
  onPay,
}: CashierChannelProps) {
  const [isChannelShow, setIsChannelShow] = useState(false)
  const [isChannelActive, setIsChannelActive] = useState(false)
  const [activeChannelIndex, setActiveChannelIndex] = useState(defaultIndex)

  const isSingle = channelLimit < 1 || !(channels.length > channelLimit)

  return (
    <div className="cu-cashier-channel">
      <div className="choose-text">
        {paymentTitle ? <p className="choose-title" dangerouslySetInnerHTML={{ __html: paymentTitle }} /> : null}
        {paymentAmount ? <p className="choose-number" dangerouslySetInnerHTML={{ __html: paymentAmount }} /> : null}
        {paymentDescribe ? <p className="choose-describe" dangerouslySetInnerHTML={{ __html: paymentDescribe }} /> : null}
      </div>
      <div className={`choose-channel${isChannelActive ? ' active' : ''}`}>
        {channelSlot}
        {isChannelShow || isSingle ? (
          <div className="choose-channel-list">
            {channels.map((item, index) => (
              <CuCashierChannelItem
                key={index}
                className={index === defaultIndex ? 'default' : undefined}
                data={item}
                active={index === activeChannelIndex}
                onClick={() => {
                  if (item.disabled) {
                    return
                  }
                  setActiveChannelIndex(index)
                  onSelect?.(item)
                }}
              />
            ))}
          </div>
        ) : channels[defaultIndex] ? (
          <div className="choose-channel-list">
            <CuCashierChannelItem
              data={channels[defaultIndex] as unknown as CashierChannelItemData}
              active
              onClick={() => onSelect?.(channels[defaultIndex])}
            />
          </div>
        ) : null}
        {!isSingle ? (
          <div
            className={`choose-channel-more${isChannelActive ? ' disabled' : ''}`}
            dangerouslySetInnerHTML={{ __html: moreButtonText }}
            onClick={() => {
              if (isChannelActive) {
                return
              }
              setIsChannelShow(true)
              setTimeout(() => setIsChannelActive(true), 0)
            }}
          />
        ) : null}
      </div>
      <div className="cu-cashier-block-btn">
        <CuButton
          className="cu-cashier-pay-button"
          type={payButtonDisabled ? 'disabled' : 'primary'}
          onClick={() => onPay?.(channels[activeChannelIndex])}
        >
          {buttonSlot ?? payButtonText}
        </CuButton>
      </div>
    </div>
  )
}

// packages/vue/src/components/cashier/CashierChannel.vue
<template>
  <div class="cu-cashier-channel">
    <div class="choose-text">
      <p v-if="paymentTitle" class="choose-title" v-html="paymentTitle"></p>
      <p v-if="paymentAmount" class="choose-number" v-html="paymentAmount"></p>
      <p v-if="paymentDescribe" class="choose-describe" v-html="paymentDescribe"></p>
    </div>
    <div class="choose-channel" :class="{ active: isChannelActive }">
      <slot></slot>
      <div v-if="isChannelShow || isSingle" class="choose-channel-list">
        <CuCashierChannelItem
          v-for="(item, index) in channels"
          :key="index"
          :class="{ default: index === defaultIndex }"
          :data="item as unknown as CashierChannel & Record<string, unknown>"
          :active="index === activeChannelIndex"
          @click="onChannelItemClick(item, index)"
        />
      </div>
      <div v-else-if="channels[defaultIndex]" class="choose-channel-list">
        <CuCashierChannelItem
          class="default"
          :data="channels[defaultIndex] as unknown as CashierChannel & Record<string, unknown>"
          active
          @click="onChannelItemClick(channels[defaultIndex], defaultIndex)"
        />
      </div>
      <div
        v-if="!isSingle"
        class="choose-channel-more"
        :class="{ disabled: isChannelActive }"
        v-html="moreButtonText"
        @click="onChannelMoreClick"
      ></div>
    </div>
    <div class="cu-cashier-block-btn">
      <CuButton
        class="cu-cashier-pay-button"
        :type="payButtonDisabled ? 'disabled' : 'primary'"
        @click="onChannelBtnClick"
      >
        <slot name="button">{{ payButtonText }}</slot>
      </CuButton>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import CuButton from '../button/Button.vue'
import CuCashierChannelItem from './CashierChannelItem.vue'

defineOptions({ name: 'cu-cashier-channel' })

export interface CashierChannel {
  text?: string
  desc?: string
  img?: string
  icon?: string
  value?: string
  disabled?: boolean
  action?: { text: string; handler: () => void }
}

const props = withDefaults(
  defineProps<{
    paymentTitle?: string
    paymentAmount?: string
    paymentDescribe?: string
    moreButtonText?: string
    payButtonText?: string
    payButtonDisabled?: boolean
    channels?: CashierChannel[]
    channelLimit?: number
    defaultIndex?: number
  }>(),
  {
    paymentTitle: '',
    paymentAmount: '',
    paymentDescribe: '',
    moreButtonText: '',
    payButtonText: '',
    payButtonDisabled: false,
    channels: () => [],
    channelLimit: 2,
    defaultIndex: 0,
  },
)

const emit = defineEmits<{
  (e: 'select', item: CashierChannel): void
  (e: 'pay', item: CashierChannel): void
}>()

const isChannelShow = ref(false)
const isChannelActive = ref(false)
const activeChannelIndex = ref(props.defaultIndex)

const isSingle = computed(() => {
  if (props.channelLimit < 1) {
    return true
  }
  return !(props.channels.length > props.channelLimit)
})

function onChannelItemClick(item: CashierChannel, index: number) {
  if (item.disabled) {
    return
  }
  activeChannelIndex.value = index
  emit('select', item)
}

function onChannelMoreClick() {
  if (isChannelActive.value) {
    return
  }
  isChannelShow.value = true
  Promise.resolve().then(() => {
    isChannelActive.value = true
  })
}

function onChannelBtnClick() {
  const item = props.channels[activeChannelIndex.value]
  emit('pay', item)
}
</script>
