// packages/react/src/components/slider/Slider.tsx
import { useEffect, useRef, useState } from 'react'

export interface SliderProps {
  value?: number | Array<number>
  min?: number
  max?: number
  step?: number
  range?: boolean
  format?: (val: number) => number | string
  disabled?: boolean
  onChange?: (value: number | Array<number>) => void
}

type Values = [number, number]

function normalize(newVal: number | number[], cur: Values, min: number, max: number, step: number): Values | null {
  const newValues: [number | undefined, number | undefined] = [
    undefined as number | undefined,
    undefined as number | undefined,
  ]
  if (Array.isArray(newVal)) {
    newValues[0] = newVal[0]
    newValues[1] = newVal[1]
  } else {
    newValues[0] = newVal
  }
  if (typeof newValues[0] !== 'number') {
    newValues[0] = cur[0]
  } else {
    newValues[0] = Math.round((newValues[0] - min) / step) * step + min
  }
  if (typeof newValues[1] !== 'number') {
    newValues[1] = cur[1]
  } else {
    newValues[1] = Math.round((newValues[1] - min) / step) * step + min
  }
  if (newValues[0]! < min) {
    newValues[0] = min
  }
  if (newValues[1]! > max) {
    newValues[1] = max
  }
  if (newValues[0]! > newValues[1]!) {
    if (newValues[0] === cur[0]) {
      newValues[1] = newValues[0]
    } else {
      newValues[0] = newValues[1]
    }
  }
  if (cur[0] === newValues[0] && cur[1] === newValues[1]) {
    return null
  }
  return [newValues[0]!, newValues[1]!]
}

export function CuSlider({
  value = 0,
  min = 0,
  max = 100,
  step = 1,
  range = false,
  format,
  disabled = false,
  onChange,
}: SliderProps) {
  const elRef = useRef<HTMLDivElement>(null)
  const valuesRef = useRef<Values>([min, max])
  const [values, setValues] = useState<Values>(() => {
    const first = normalize(value, valuesRef.current, min, max, step)
    return first ?? [min, max]
  })
  valuesRef.current = values

  const [isDragging, setIsDragging] = useState(false)
  const [isDragingUpper, setIsDragingUpper] = useState(false)
  // v2 契约：isDragging 同步生效（拖拽 window 监听器在下一个渲染前就可能触发）
  const isDraggingRef = useRef(false)
  const isDragingUpperRef = useRef(false)

  const startDragMousePos = useRef(0)
  const startVal = useRef(0)
  const skipChangeRef = useRef(false)

  // v2 watch value：外部值变化 → 归一化（跳过自身派发引起的回环）
  useEffect(() => {
    if (skipChangeRef.current) {
      skipChangeRef.current = false
      return
    }
    const next = normalize(value, valuesRef.current, min, max, step)
    if (next) {
      skipChangeRef.current = true
      setValues(next)
    }
  }, [value])

  const lowerHandlePosition = ((values[0] - min) / (max - min)) * 100
  const upperHandlePosition = ((values[1] - min) / (max - min)) * 100
  const barStyle = range
    ? { width: ((values[1] - values[0]) / (max - min)) * 100 + '%', left: lowerHandlePosition + '%' }
    : { width: ((values[0] - min) / (max - min)) * 100 + '%' }

  const commit = (next: Values) => {
    if (range) {
      onChange?.(next)
    } else {
      onChange?.(next[0])
    }
  }

  const startLowerDrag = (e: React.MouseEvent | React.TouchEvent) => {
    if (disabled) {
      return
    }
    e.preventDefault()
    e.stopPropagation()
    const point = ('changedTouches' in e && e.changedTouches ? e.changedTouches[0] : e) as unknown as MouseEvent
    startDragMousePos.current = point.pageX
    startVal.current = valuesRef.current[0]
    isDragingUpperRef.current = false
    isDraggingRef.current = true
    setIsDragingUpper(false)
    setIsDragging(true)
    window.addEventListener('mousemove', onDrag)
    window.addEventListener('touchmove', onDrag)
    window.addEventListener('mouseup', onUp)
    window.addEventListener('touchend', onUp)
  }

  const startUpperDrag = (e: React.MouseEvent | React.TouchEvent) => {
    if (disabled) {
      return
    }
    e.preventDefault()
    e.stopPropagation()
    const point = ('changedTouches' in e && e.changedTouches ? e.changedTouches[0] : e) as unknown as MouseEvent
    startDragMousePos.current = point.pageX
    startVal.current = valuesRef.current[1]
    isDragingUpperRef.current = true
    isDraggingRef.current = true
    setIsDragingUpper(true)
    setIsDragging(true)
    window.addEventListener('mousemove', onDrag)
    window.addEventListener('touchmove', onDrag)
    window.addEventListener('mouseup', onUp)
    window.addEventListener('touchend', onUp)
  }

  function onDrag(e: MouseEvent | TouchEvent) {
    if (disabled || !isDraggingRef.current) {
      return
    }
    e.preventDefault()
    e.stopPropagation()
    const point =
      'changedTouches' in e && (e as TouchEvent).changedTouches
        ? (e as TouchEvent).changedTouches[0]
        : (e as MouseEvent)
    window.requestAnimationFrame(() => {
      const diff = ((point.pageX - startDragMousePos.current) / (elRef.current?.offsetWidth ?? 1)) * (max - min)
      const nextVal = startVal.current + diff
      if (!isDraggingRef.current) {
        return
      }
      const next = isDragingUpperRef.current
        ? normalize([null as unknown as number, nextVal], valuesRef.current, min, max, step)
        : normalize([nextVal, null as unknown as number], valuesRef.current, min, max, step)
      if (next) {
        skipChangeRef.current = true
        setValues(next)
        commit(next)
      }
    })
  }

  function onUp(e: Event) {
    e.preventDefault()
    e.stopPropagation()
    stopDrag()
  }

  function stopDrag() {
    isDraggingRef.current = false
    isDragingUpperRef.current = false
    setIsDragging(false)
    setIsDragingUpper(false)
    window.removeEventListener('mousemove', onDrag)
    window.removeEventListener('touchmove', onDrag)
    window.removeEventListener('mouseup', onUp)
    window.removeEventListener('touchend', onUp)
  }

  const formatHint = (val: number) => (format ? format(val) : val)

  return (
    <div className={`cu-slider${disabled ? ' is-disabled' : ''}`} ref={elRef}>
      {range ? (
        <>
          <div className="cu-slider-bar" style={barStyle}></div>
          <div
            className={`cu-slider-handle is-lower${isDragging && !isDragingUpper ? ' is-active' : ''}`}
            data-hint={String(formatHint(values[0]))}
            style={{ left: lowerHandlePosition + '%' }}
          >
            <span onMouseDown={startLowerDrag} onTouchStart={startLowerDrag}></span>
          </div>
          <div
            className={`cu-slider-handle is-higher${isDragging && isDragingUpper ? ' is-active' : ''}`}
            data-hint={String(formatHint(values[1]))}
            style={{ left: upperHandlePosition + '%' }}
          >
            <span onMouseDown={startUpperDrag} onTouchStart={startUpperDrag}></span>
          </div>
        </>
      ) : (
        <>
          <div className="cu-slider-bar" style={barStyle}></div>
          <div
            className={`cu-slider-handle${isDragging ? ' is-active' : ''}`}
            data-hint={String(formatHint(values[0]))}
            style={{ left: lowerHandlePosition + '%' }}
          >
            <span onMouseDown={startLowerDrag} onTouchStart={startLowerDrag}></span>
          </div>
        </>
      )}
    </div>
  )
}

// packages/vue/src/components/slider/Slider.vue
<template>
  <div class="cu-slider" :class="{ 'is-disabled': disabled }">
    <template v-if="range">
      <div class="cu-slider-bar" :style="barStyle"></div>
      <div
        class="cu-slider-handle is-lower"
        :data-hint="format(values[0])"
        :class="{ 'is-active': isDragging && !isDragingUpper }"
        :style="{ left: lowerHandlePosition + '%' }"
      >
        <span @mousedown="startLowerDrag" @touchstart="startLowerDrag"></span>
      </div>
      <div
        class="cu-slider-handle is-higher"
        :data-hint="format(values[1])"
        :class="{ 'is-active': isDragging && isDragingUpper }"
        :style="{ left: upperHandlePosition + '%' }"
      >
        <span @mousedown="startUpperDrag" @touchstart="startUpperDrag"></span>
      </div>
    </template>
    <template v-else>
      <div class="cu-slider-bar" :style="barStyle"></div>
      <div
        class="cu-slider-handle"
        :data-hint="format(values[0])"
        :class="{ 'is-active': isDragging }"
        :style="{ left: lowerHandlePosition + '%' }"
      >
        <span @mousedown="startLowerDrag" @touchstart="startLowerDrag"></span>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'

defineOptions({ name: 'cu-slider' })

const props = withDefaults(
  defineProps<{
    modelValue?: number | Array<number>
    min?: number
    max?: number
    step?: number
    range?: boolean
    format?: (val: number) => number | string
    disabled?: boolean
  }>(),
  {
    modelValue: 0,
    min: 0,
    max: 100,
    step: 1,
    range: false,
    format: undefined,
    disabled: false,
  },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: number | Array<number>): void
}>()

const isDragging = ref(false)
const isDragingUpper = ref(false)
const values = ref<[number, number]>([props.min, props.max])
let startDragMousePos = 0
let startVal = 0

const format = (val: number) => props.format?.(val) ?? val

watch(
  () => props.modelValue,
  val => {
    if (
      (Array.isArray(val) && (val[0] !== values.value[0] || val[1] !== values.value[1])) ||
      (!Array.isArray(val) && val !== values.value[0])
    ) {
      updateValue(val)
    }
  },
  { immediate: true },
)

watch(
  () => props.disabled,
  newVal => {
    if (!newVal) {
      stopDrag()
    }
  },
)

const lowerHandlePosition = computed(
  () => ((values.value[0] - props.min) / (props.max - props.min)) * 100,
)
const upperHandlePosition = computed(
  () => ((values.value[1] - props.min) / (props.max - props.min)) * 100,
)
const barStyle = computed(() => {
  if (props.range) {
    return {
      width: ((values.value[1] - values.value[0]) / (props.max - props.min)) * 100 + '%',
      left: lowerHandlePosition.value + '%',
    }
  }
  return {
    width: ((values.value[0] - props.min) / (props.max - props.min)) * 100 + '%',
  }
})

function updateValue(newVal: number | Array<number>) {
  const newValues: [number | undefined, number | undefined] = [
    undefined as number | undefined,
    undefined as number | undefined,
  ]

  if (Array.isArray(newVal)) {
    newValues[0] = newVal[0]
    newValues[1] = newVal[1]
  } else {
    newValues[0] = newVal
  }

  if (typeof newValues[0] !== 'number') {
    newValues[0] = values.value[0]
  } else {
    newValues[0] = Math.round((newValues[0] - props.min) / props.step) * props.step + props.min
  }

  if (typeof newValues[1] !== 'number') {
    newValues[1] = values.value[1]
  } else {
    newValues[1] = Math.round((newValues[1] - props.min) / props.step) * props.step + props.min
  }

  // value boundary adjust
  if (newValues[0]! < props.min) {
    newValues[0] = props.min
  }
  if (newValues[1]! > props.max) {
    newValues[1] = props.max
  }
  if (newValues[0]! > newValues[1]!) {
    if (newValues[0] === values.value[0]) {
      newValues[1] = newValues[0]
    } else {
      newValues[0] = newValues[1]
    }
  }

  if (values.value[0] === newValues[0] && values.value[1] === newValues[1]) {
    return
  }

  values.value = [newValues[0]!, newValues[1]!]

  if (props.range) {
    emit('update:modelValue', values.value)
  } else {
    emit('update:modelValue', values.value[0])
  }
}

function startLowerDrag(e: Event) {
  if (props.disabled) {
    return
  }
  e.preventDefault()
  e.stopPropagation()
  const point = ('changedTouches' in e
    ? (e as TouchEvent).changedTouches[0]
    : (e as MouseEvent)) as MouseEvent
  startDragMousePos = point.pageX
  startVal = values.value[0]
  isDragingUpper.value = false
  isDragging.value = true
  window.addEventListener('mousemove', onDrag)
  window.addEventListener('touchmove', onDrag)
  window.addEventListener('mouseup', onUp)
  window.addEventListener('touchend', onUp)
}

function startUpperDrag(e: Event) {
  if (props.disabled) {
    return
  }
  e.preventDefault()
  e.stopPropagation()
  const point = ('changedTouches' in e
    ? (e as TouchEvent).changedTouches[0]
    : (e as MouseEvent)) as MouseEvent
  startDragMousePos = point.pageX
  startVal = values.value[1]
  isDragingUpper.value = true
  isDragging.value = true
  window.addEventListener('mousemove', onDrag)
  window.addEventListener('touchmove', onDrag)
  window.addEventListener('mouseup', onUp)
  window.addEventListener('touchend', onUp)
}

function onDrag(e: Event) {
  if (props.disabled) {
    return
  }
  e.preventDefault()
  e.stopPropagation()
  if (!isDragging.value) {
    return
  }
  const point = ('changedTouches' in e
    ? (e as TouchEvent).changedTouches[0]
    : (e as MouseEvent)) as MouseEvent
  const el = document.querySelector<HTMLElement>('.cu-slider')
  window.requestAnimationFrame(() => {
    const diff = ((point.pageX - startDragMousePos) / el!.offsetWidth) * (props.max - props.min)
    const nextVal = startVal + diff
    if (isDragging.value) {
      if (isDragingUpper.value) {
        updateValue([null as unknown as number, nextVal])
      } else {
        updateValue([nextVal, null as unknown as number])
      }
    }
  })
}

function onUp(e: Event) {
  e.preventDefault()
  e.stopPropagation()
  stopDrag()
}

function stopDrag() {
  isDragging.value = false
  isDragingUpper.value = false
  window.removeEventListener('mousemove', onDrag)
  window.removeEventListener('touchmove', onDrag)
  window.removeEventListener('mouseup', onUp)
  window.removeEventListener('touchend', onUp)
}
</script>
