// packages/react/src/components/steps/Steps.tsx
import { Fragment, useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react'
import { MdIcon } from '../icon/Icon'

export interface StepItem {
  name?: string
  text?: string
}

export interface StepsProps {
  steps?: StepItem[]
  current?: number
  direction?: 'horizontal' | 'vertical'
  transition?: boolean
  verticalAdaptive?: boolean
  custom?: boolean
  /** 统一自定义图标（v2 scoped slot icon） */
  renderIcon?: (opts: { index: number; currentIndex: number }) => ReactNode
  /** 按状态自定义：已到达 */
  renderReached?: (opts: { index: number }) => ReactNode
  /** 按状态自定义：当前 */
  renderCurrent?: (opts: { index: number }) => ReactNode
  /** 按状态自定义：未到达 */
  renderUnreached?: (opts: { index: number }) => ReactNode
  /** 自定义文本 */
  renderContent?: (opts: { index: number; step: StepItem }) => ReactNode
  /** custom 模式下完全接管渲染 */
  children?: ReactNode
}

type Progress = { len: number; time: number }[]

const DURATION = 0.3

function formatValue(steps: StepItem[], val: number) {
  if (val < 0) {
    return 0
  } else if (val > steps.length - 1) {
    return steps.length - 1
  }
  return val
}

function sliceProgress(steps: StepItem[], current: number, prev: Progress): Progress {
  return steps.slice(0, steps.length - 1).map((_step, index) => {
    const offset = current - index
    const old = prev[index]
    const isNewProgress = old === undefined
    let len: number
    if (offset <= 0) {
      len = 0
    } else if (offset >= 1) {
      len = 1
    } else {
      len = offset
    }
    const time = (isNewProgress ? len : Math.abs(old.len - len)) * DURATION
    return { len, time }
  })
}

export function MdSteps({
  steps = [],
  current = 0,
  direction = 'horizontal',
  transition = false,
  verticalAdaptive = false,
  custom = false,
  renderIcon,
  renderReached,
  renderCurrent,
  renderUnreached,
  renderContent,
  children,
}: StepsProps) {
  const rootRef = useRef<HTMLDivElement>(null)
  const [progress, setProgress] = useState<Progress>(() => sliceProgress(steps, formatValue(steps, current), []))
  const [stepsSize, setStepsSize] = useState<number[]>([])
  const [currentLength, setCurrentLength] = useState(() => formatValue(steps, current))
  const currentLengthRef = useRef(currentLength)
  currentLengthRef.current = currentLength
  const progressRef = useRef(progress)
  progressRef.current = progress

  // v2 watch current：普通模式直接更新；transition 模式 100ms 后分段动画
  const isFirstRender = useRef(true)
  useEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false
      return
    }
    const currentStep = formatValue(steps, current)
    const newProgress = sliceProgress(steps, currentStep, progressRef.current)
    if (transition) {
      const isAdd = currentStep >= currentLengthRef.current
      let len = isAdd ? 0 : currentLengthRef.current
      const timer = setTimeout(() => {
        const walk = (index: number) => {
          if (index < newProgress.length && index > -1 && newProgress[index]) {
            if (isAdd) {
              len += newProgress[index].len
            } else {
              len -= progressRef.current[index].len - newProgress[index].len
            }
            setTimeout(() => {
              walk(isAdd ? index + 1 : index - 1)
              setCurrentLength((prev) => {
                if ((isAdd && len > prev) || (!isAdd && len < prev)) {
                  return len
                }
                return prev
              })
            }, newProgress[index].time * 1000)
          }
          setProgress((prev) => {
            const next = [...prev]
            next[index] = newProgress[index]
            return next
          })
        }
        walk(isAdd ? 0 : newProgress.length - 1)
      }, 100)
      return () => clearTimeout(timer)
    }
    setProgress(newProgress)
    setCurrentLength(currentStep)
  }, [current])

  // v2 $_initStepSize：垂直非 adaptive 时按文本块高度测距
  const stepsSizeRef = useRef(stepsSize)
  stepsSizeRef.current = stepsSize
  useEffect(() => {
    if (direction !== 'vertical' || verticalAdaptive) {
      return
    }
    const rootEl = rootRef.current
    if (!rootEl) {
      return
    }
    const iconWrappers = rootEl.querySelectorAll('.icon-wrapper')
    const textWrappers = rootEl.querySelectorAll('.text-wrapper')
    const sizes = Array.from(textWrappers).map((wrapper, index) => {
      let stepHeight = wrapper.clientHeight
      const iconHeight = iconWrappers[index]?.clientHeight ?? 0
      if (index === textWrappers.length - 1) {
        stepHeight -= iconHeight
      } else {
        stepHeight += 40
      }
      return stepHeight > 0 ? stepHeight : 0
    })
    if (sizes.toString() !== stepsSizeRef.current.toString()) {
      setStepsSize(sizes)
    }
  })

  const getStepSizeForStyle = (index: number): CSSProperties | undefined => {
    const size = direction === 'vertical' && !verticalAdaptive ? stepsSize[index] : 0
    return size ? { height: `${size}px` } : undefined
  }

  const getStepStatusClass = (index: number) => {
    const status: string[] = []
    if (index < currentLength) {
      status.push('reached')
    }
    if (index === Math.floor(currentLength)) {
      status.push('current')
    }
    return status.join(' ')
  }

  const barInnerStyle = (index: number): CSSProperties => {
    const p = progress[index]
    const transform =
      direction === 'horizontal'
        ? `(${(p.len - 1) * 100}%, 0, 0)`
        : `(0, ${(p.len - 1) * 100}%, 0)`
    return {
      transform: `translate3d${transform}`,
      transition: `all ${p.time}s linear`,
    }
  }

  const renderDefaultNode = (index: number) => {
    const nodeDefault = (
      <div className="step-node-default">
        <div className="step-node-default-icon" style={{ width: 6, height: 6, borderRadius: '50%' }}></div>
      </div>
    )
    if (index < currentLength) {
      return renderReached ? renderReached({ index }) : nodeDefault
    }
    if (index === currentLength) {
      return renderCurrent ? renderCurrent({ index }) : <MdIcon name="success"></MdIcon>
    }
    return renderUnreached ? renderUnreached({ index }) : nodeDefault
  }

  return (
    <div
      ref={rootRef}
      className={`md-steps${direction === 'vertical' ? ' md-steps-vertical' : ''}${
        direction === 'horizontal' ? ' md-steps-horizontal' : ''
      }${direction === 'vertical' && verticalAdaptive ? ' vertical-adaptive' : ''}${
        currentLength % 1 !== 0 ? ' no-current' : ''
      }`}
    >
      {custom ? children : null}
      {!custom &&
        steps.map((step, index) => (
          <Fragment key={index}>
            <div className={`step-wrapper${getStepStatusClass(index) ? ` ${getStepStatusClass(index)}` : ''}`}>
              {renderIcon ? (
                <div className="icon-wrapper">{renderIcon({ index, currentIndex: currentLength })}</div>
              ) : (
                <div className="icon-wrapper">{renderDefaultNode(index)}</div>
              )}
              <div className="text-wrapper">
                {renderContent ? (
                  renderContent({ index, step })
                ) : (
                  <>
                    <div className="name">{step.name}</div>
                    {step.text ? <div className="desc">{step.text}</div> : null}
                  </>
                )}
              </div>
            </div>
            <div
              className={`bar ${direction === 'horizontal' ? 'horizontal-bar' : 'vertical-bar'}`}
              style={getStepSizeForStyle(index)}
            >
              {progress[index] ? <i className="bar-inner" style={barInnerStyle(index)}></i> : null}
            </div>
          </Fragment>
        ))}
    </div>
  )
}

// packages/vue/src/components/steps/Steps.vue
<template>
  <div
    ref="root"
    class="md-steps"
    :class="{
      'md-steps-vertical': direction === 'vertical',
      'md-steps-horizontal': direction === 'horizontal',
      'vertical-adaptive': direction === 'vertical' && verticalAdaptive,
      'no-current': currentLength % 1 !== 0,
    }"
  >
    <slot v-if="custom" :steps="steps"></slot>
    <template v-else v-for="(step, index) of steps" :key="`steps-${index}`">
      <div class="step-wrapper" :class="getStepStatusClass(index)">
        <!-- 统一自定义图标 -->
        <div v-if="$slots.icon" class="icon-wrapper">
          <slot name="icon" :index="index" :current-index="currentLength"></slot>
        </div>
        <!-- 按状态自定义 -->
        <div v-else class="icon-wrapper">
          <template v-if="index < currentLength">
            <slot
              v-if="$slots.reached"
              name="reached"
              :index="index"
            ></slot>
            <div v-else class="step-node-default">
              <div class="step-node-default-icon" style="width: 6px; height: 6px; border-radius: 50%"></div>
            </div>
          </template>
          <template v-else-if="index === currentLength">
            <slot
              v-if="$slots.current"
              name="current"
              :index="index"
            ></slot>
            <MdIcon v-else name="success"></MdIcon>
          </template>
          <template v-else>
            <slot
              v-if="$slots.unreached"
              name="unreached"
              :index="index"
            ></slot>
            <div v-else class="step-node-default">
              <div class="step-node-default-icon" style="width: 6px; height: 6px; border-radius: 50%"></div>
            </div>
          </template>
        </div>
        <div class="text-wrapper">
          <slot
            v-if="$slots.content"
            name="content"
            :index="index"
            :step="step"
          ></slot>
          <template v-else>
            <div class="name">
              {{ step.name }}
            </div>
            <div v-if="step.text" class="desc">
              {{ step.text }}
            </div>
          </template>
        </div>
      </div>
      <div
        class="bar"
        :class="[direction === 'horizontal' ? 'horizontal-bar' : 'vertical-bar']"
        :style="getStepSizeForStyle(index)"
      >
        <i v-if="progress[index]" class="bar-inner" :style="barInnerStyle(index)"></i>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { nextTick, onMounted, onUpdated, ref, watch } from 'vue'
import MdIcon from '../icon/Icon.vue'

defineOptions({ name: 'md-steps' })

export interface StepItem {
  name?: string
  text?: string
}

const props = withDefaults(
  defineProps<{
    steps?: StepItem[]
    current?: number
    direction?: 'horizontal' | 'vertical'
    transition?: boolean
    verticalAdaptive?: boolean
    custom?: boolean
  }>(),
  { steps: () => [], current: 0, direction: 'horizontal', transition: false, verticalAdaptive: false, custom: false },
)

const root = ref<HTMLElement>()
const initialed = ref(false)
const progress = ref<Array<{ len: number; time: number }>>([])
const stepsSize = ref<number[]>([])
const currentLength = ref(0)
const duration = 0.3
let timer: ReturnType<typeof setTimeout> | null = null

const barInnerStyle = (index: number) => {
  const p = progress.value
  const transform =
    props.direction === 'horizontal'
      ? `(${(p[index].len - 1) * 100}%, 0, 0)`
      : `(0, ${(p[index].len - 1) * 100}%, 0)`
  return {
    transform: `translate3d${transform}`,
    transition: `all ${p[index].time}s linear`,
  }
}

watch(
  () => props.current,
  (val, oldVal) => {
    const currentStep = formatValue(val)
    const newProgress = sliceProgress(currentStep)
    if (props.transition) {
      const isAdd = currentStep >= oldVal
      if (timer) {
        clearTimeout(timer)
      }
      timer = setTimeout(() => {
        doTransition(newProgress, isAdd, (len) => {
          if ((isAdd && len > currentLength.value) || (!isAdd && len < currentLength.value)) {
            currentLength.value = len
          }
        })
      }, 100)
    } else {
      progress.value = newProgress
      currentLength.value = currentStep
    }
  },
)

// created 语义：初始化进度
{
  const currentStep = formatValue(props.current)
  currentLength.value = currentStep
  progress.value = sliceProgress(currentStep)
}

onMounted(() => {
  initStepSize()
  initialed.value = true
})
onUpdated(() => {
  nextTick(() => {
    initStepSize()
  })
})

function initStepSize() {
  if (props.direction !== 'vertical' || props.verticalAdaptive) {
    return
  }
  const rootEl = root.value
  if (!rootEl) {
    return
  }
  const iconWrappers = rootEl.querySelectorAll('.icon-wrapper')
  const textWrappers = rootEl.querySelectorAll('.text-wrapper')
  const sizes = Array.from(textWrappers).map((wrapper, index) => {
    let stepHeight = wrapper.clientHeight
    const iconHeight = iconWrappers[index]?.clientHeight ?? 0
    if (index === textWrappers.length - 1) {
      // 末步需要扣除浮动高度
      stepHeight -= iconHeight
    } else {
      // 步骤间距
      stepHeight += 40
    }
    return stepHeight > 0 ? stepHeight : 0
  })

  if (sizes.toString() !== stepsSize.value.toString()) {
    stepsSize.value = sizes
  }
}

function getStepSizeForStyle(index: number) {
  const size = props.direction === 'vertical' && !props.verticalAdaptive ? stepsSize.value[index] : 0
  return size
    ? {
        height: `${size}px`,
      }
    : null
}

function getStepStatusClass(index: number) {
  const current = currentLength.value
  const status: string[] = []
  if (index < current) {
    status.push('reached')
  }
  if (index === Math.floor(current)) {
    status.push('current')
  }
  return status.join(' ')
}

function formatValue(val: number) {
  if (val < 0) {
    return 0
  } else if (val > props.steps.length - 1) {
    return props.steps.length - 1
  }
  return val
}

function sliceProgress(current: number) {
  return props.steps.slice(0, props.steps.length - 1).map((_step, index) => {
    const offset = current - index
    const old = progress.value[index]
    const isNewProgress = old === undefined
    let len: number
    if (offset <= 0) {
      len = 0
    } else if (offset >= 1) {
      len = 1
    } else {
      len = offset
    }
    const time = (isNewProgress ? len : Math.abs(old.len - len)) * duration
    return {
      len,
      time,
    }
  })
}

function doTransition(
  newProgress: Array<{ len: number; time: number }>,
  isAdd: boolean,
  step: (len: number) => void,
) {
  let current = isAdd ? 0 : currentLength.value
  const walk = (index: number) => {
    if (index < newProgress.length && index > -1 && newProgress[index]) {
      if (isAdd) {
        current += newProgress[index].len
      } else {
        current -= progress.value[index].len - newProgress[index].len
      }
      setTimeout(() => {
        walk(isAdd ? index + 1 : index - 1)
        step(current)
      }, newProgress[index].time * 1000)
    }
    progress.value[index] = newProgress[index]
  }
  walk(isAdd ? 0 : newProgress.length - 1)
}
</script>
