// packages/vue/src/components/tabs/TabBar.vue
<template>
  <nav class="cu-tab-bar">
    <div ref="wrapper" class="cu-tab-bar-inner">
      <template v-if="scrollable">
        <div v-show="maskStartShown" class="cu-tab-bar-start"></div>
        <div v-show="maskEndShown" class="cu-tab-bar-end"></div>
      </template>
      <CuScrollView ref="scroller" :scrolling-x="scrollable" :scrolling-y="false" :key="scrollerTmpKey" @scroll="onScroll">
        <div class="cu-tab-bar-list" :style="{ width: contentW + 'px' }">
          <a
            v-for="(item, index) in items"
            :key="item.name"
            :ref="el => setItemRef(el, index)"
            class="cu-tab-bar-item"
            :class="{
              'is-active': currentName === item.name,
              'is-disabled': !!item.disabled,
              'more-than-five': items.length > 5 && index === 0,
            }"
            @click="onClick(item, index)"
          >
            <slot
              name="item"
              :item="item"
              :items="items"
              :index="index"
              :current-name="currentName"
            >{{ item.label }}</slot>
          </a>
        </div>
        <span
          v-if="hasInk"
          class="cu-tab-bar-ink"
          :class="{
            'is-disabled': currentTab && currentTab.disabled,
          }"
          :style="{
            width: inkWidth + 'px',
            transform: 'translateX(' + inkPos + 'px)',
          }"
        ></span>
      </CuScrollView>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { computed, nextTick, onActivated, onBeforeUnmount, onDeactivated, onMounted, ref, watch } from 'vue'
import CuScrollView from '../scroll-view/ScrollView.vue'

defineOptions({ name: 'cu-tab-bar' })

export interface TabBarItem {
  name: string | number
  label?: string
  disabled?: boolean
}

const props = withDefaults(
  defineProps<{
    value?: string | number
    items?: TabBarItem[]
    hasInk?: boolean
    inkLength?: number | string
    immediate?: boolean
  }>(),
  { value: '', items: () => [], hasInk: true, inkLength: '25', immediate: false },
)

const emit = defineEmits<{
  (e: 'change', item: TabBarItem, index: number, prevIndex: number): void
  (e: 'update:modelValue' | 'input', name: string | number): void
}>()

const currentName = ref<string | number>('')
const wrapperW = ref(0)
const contentW = ref(0)
const inkWidth = ref(0)
const inkPos = ref(0)
const scrollerTmpKey = ref(Date.now())
const maskStartShown = ref(false)
const maskEndShown = ref(true)

const wrapper = ref<HTMLElement>()
const scroller = ref<InstanceType<typeof CuScrollView> | null>(null)
const itemRefs: HTMLElement[] = []
function setItemRef(el: unknown, index: number) {
  if (el) {
    itemRefs[index] = el as HTMLElement
  }
}

const scrollable = computed(() => contentW.value > wrapperW.value)
const currentIndex = computed(() => {
  for (let i = 0, len = props.items.length; i < len; i++) {
    if (props.items[i].name === currentName.value) {
      return i
    }
  }
  return -1
})
// v2 契约：if (this.currentIndex) 真值判断（index 0 时 currentTab 为 undefined）
const currentTab = computed(() => {
  if (currentIndex.value) {
    return props.items[currentIndex.value]
  }
  return undefined
})

watch(
  () => props.value,
  (val) => {
    if (val !== currentName.value) {
      currentName.value = val
    }
  },
  { immediate: true },
)
watch(inkWidth, () => {
  nextTick(() => reflow())
})
watch(
  () => props.items,
  () => {
    nextTick(() => reflow())
  },
)
watch(currentIndex, () => {
  nextTick(() => reflow())
})
watch(scrollable, () => {
  scrollerTmpKey.value = Date.now()
})

// created 语义：默认选中首项
if (currentName.value === '' && props.items.length) {
  currentName.value = props.items[0].name
  emit('change', props.items[0], 0, 0)
}

onMounted(() => {
  resizeEnterBehavior()
})
onActivated(() => {
  resizeEnterBehavior()
})
onDeactivated(() => {
  resizeLeaveBehavior()
})
onBeforeUnmount(() => {
  resizeLeaveBehavior()
})

function onScroll({ scrollLeft: left }: { scrollLeft: number; scrollTop: number }) {
  if (left > 0) {
    maskStartShown.value = true
  } else {
    maskStartShown.value = false
  }
  maskEndShown.value = !(contentW.value > 0 && left >= contentW.value - wrapperW.value)
}

function onClick(item: TabBarItem, index: number) {
  if (item.disabled) {
    return
  }
  emit('change', item, index, currentIndex.value)
  currentName.value = item.name
  emit('update:modelValue', item.name)
}

function resizeEnterBehavior() {
  window.addEventListener('resize', reflow)
  reflow()
  if (props.immediate) {
    nextTick(() => {
      const item = props.items[currentIndex.value]
      if (item) {
        emit('change', item, currentIndex.value, currentIndex.value)
      }
    })
  }
}

function resizeLeaveBehavior() {
  window.removeEventListener('resize', reflow)
}

// MARK: public methods
function reflow() {
  if (!itemRefs.length) {
    return
  }

  const wrapperRect = wrapper.value?.getBoundingClientRect()
  wrapperW.value = wrapperRect?.width ?? 0

  let contentWidth = 0
  for (let i = 0, len = props.items.length; i < len; i++) {
    const rect = itemRefs[i]?.getBoundingClientRect()
    contentWidth += rect?.width ?? 0
  }
  contentW.value = contentWidth
  scroller.value?.reflowScroller()
  nextTick(() => {
    const target = itemRefs[currentIndex.value]
    if (!target) {
      return
    }
    inkWidth.value = typeof props.inkLength === 'string' ? Number(props.inkLength) : (target.offsetWidth * props.inkLength) / 100
    inkPos.value = target.offsetLeft + (target.offsetWidth - inkWidth.value) / 2

    const prevTarget = itemRefs[currentIndex.value - 1]
    const nextTarget = itemRefs[currentIndex.value + 1]

    if (!prevTarget) {
      scroller.value?.scrollTo(0, 0, true)
      return
    }
    if (!nextTarget) {
      scroller.value?.scrollTo(contentW.value, 0, true)
      return
    }

    const wrapperRect2 = wrapper.value?.getBoundingClientRect()
    const prevRect = prevTarget.getBoundingClientRect()
    const nextRect = nextTarget.getBoundingClientRect()
    if (wrapperRect2 && prevRect.left < wrapperRect2.left) {
      scroller.value?.scrollTo(prevTarget.offsetLeft, 0, true)
    } else if (wrapperRect2 && nextRect.right > wrapperRect2.right) {
      scroller.value?.scrollTo(nextTarget.offsetLeft + nextTarget.offsetWidth - wrapperW.value, 0, true)
    }
  })
}

defineExpose({ reflow })
</script>

// packages/react/src/components/tabs/TabBar.tsx
import { forwardRef, useCallback, useEffect, useImperativeHandle, useRef, useState, type ReactNode } from 'react'
import { CuScrollView, type ScrollViewExposed } from '../scroll-view/ScrollView'

export interface TabBarItem {
  name: string | number
  label?: string
  disabled?: boolean
}

export interface TabBarProps {
  value?: string | number
  items?: TabBarItem[]
  hasInk?: boolean
  inkLength?: number | string
  immediate?: boolean
  renderItem?: (opts: { item: TabBarItem; items: TabBarItem[]; index: number; currentName: string | number }) => ReactNode
  onChange?: (item: TabBarItem, index: number, prevIndex: number) => void
  onInput?: (name: string | number) => void
}

export interface TabBarExposed {
  reflow: () => void
}

export const CuTabBar = forwardRef<TabBarExposed, TabBarProps>(function CuTabBar(
  { value = '', items = [], hasInk = true, inkLength = '25', immediate = false, renderItem, onChange, onInput },
  ref,
) {
  const wrapperRef = useRef<HTMLDivElement>(null)
  const scrollViewRef = useRef<ScrollViewExposed | null>(null)
  const itemRefs = useRef<Array<HTMLAnchorElement | null>>([])
  const [currentName, setCurrentName] = useState<string | number>(() => {
    // created 语义：默认选中首项并通知
    if (value === '' && items.length) {
      const first = items[0]
      setTimeout(() => onChange?.(first, 0, 0), 0)
      return first.name
    }
    return value
  })
  const [wrapperW, setWrapperW] = useState(0)
  const [contentW, setContentW] = useState(0)
  const [inkWidth, setInkWidth] = useState(0)
  const [inkPos, setInkPos] = useState(0)
  const [scrollerTmpKey, setScrollerTmpKey] = useState(() => Date.now())
  const [maskStartShown, setMaskStartShown] = useState(false)
  const [maskEndShown, setMaskEndShown] = useState(true)

  // v2 watch value：仅在 prop 实际变化时同步（created 默认选中不被清掉）
  const prevValueRef = useRef(value)
  const currentNameRef = useRef(currentName)
  currentNameRef.current = currentName
  useEffect(() => {
    if (prevValueRef.current !== value) {
      prevValueRef.current = value
      if (value !== currentNameRef.current) {
        setCurrentName(value)
      }
    }
  }, [value])

  const currentIndex = items.findIndex((item) => item.name === currentName)
  // v2 契约：if (this.currentIndex) 真值判断（index 0 时 currentTab 为 undefined）
  const currentTab = currentIndex ? items[currentIndex] : undefined

  const scrollable = contentW > wrapperW

  // v2 watch scrollable：可滚动状态变化时重建 scroller
  const scrollableRef = useRef(scrollable)
  useEffect(() => {
    if (scrollableRef.current !== scrollable) {
      scrollableRef.current = scrollable
      setScrollerTmpKey(Date.now())
    }
  }, [scrollable])

  const reflowRef = useRef<() => void>(() => {})

  const reflow = useCallback(() => {
    const refs = itemRefs.current
    if (!refs.length) {
      return
    }
    const wrapperRect = wrapperRef.current?.getBoundingClientRect()
    setWrapperW(wrapperRect?.width ?? 0)

    let contentWidth = 0
    for (let i = 0; i < items.length; i++) {
      contentWidth += refs[i]?.getBoundingClientRect().width ?? 0
    }
    setContentW(contentWidth)
    scrollViewRef.current?.reflowScroller()

    setTimeout(() => {
      const target = itemRefs.current[currentIndex]
      if (!target) {
        return
      }
      const width = typeof inkLength === 'string' ? Number(inkLength) : (target.offsetWidth * inkLength) / 100
      setInkWidth(width)
      setInkPos(target.offsetLeft + (target.offsetWidth - width) / 2)

      const prevTarget = itemRefs.current[currentIndex - 1]
      const nextTarget = itemRefs.current[currentIndex + 1]
      if (!prevTarget) {
        scrollViewRef.current?.scrollTo(0, 0, true)
        return
      }
      if (!nextTarget) {
        scrollViewRef.current?.scrollTo(contentWidth, 0, true)
        return
      }
      const wrapperRect2 = wrapperRef.current?.getBoundingClientRect()
      const prevRect = prevTarget.getBoundingClientRect()
      const nextRect = nextTarget.getBoundingClientRect()
      if (wrapperRect2 && prevRect.left < wrapperRect2.left) {
        scrollViewRef.current?.scrollTo(prevTarget.offsetLeft, 0, true)
      } else if (wrapperRect2 && nextRect.right > wrapperRect2.right) {
        scrollViewRef.current?.scrollTo(nextTarget.offsetLeft + nextTarget.offsetWidth - (wrapperRect2.width ?? 0), 0, true)
      }
    }, 0)
  }, [items, currentIndex, inkLength])

  reflowRef.current = reflow
  useImperativeHandle(ref, () => ({ reflow: () => reflowRef.current() }))

  useEffect(() => {
    reflowRef.current()
    const onResize = () => reflowRef.current()
    window.addEventListener('resize', onResize)
    if (immediate) {
      setTimeout(() => {
        const item = items[currentIndex]
        if (item) {
          onChange?.(item, currentIndex, currentIndex)
        }
      }, 0)
    }
    return () => window.removeEventListener('resize', onResize)
  }, [])

  const setItemRef = (el: HTMLAnchorElement | null, index: number) => {
    itemRefs.current[index] = el
  }

  return (
    <nav className="cu-tab-bar">
      <div className="cu-tab-bar-inner" ref={wrapperRef}>
        {scrollable ? (
          <>
            <div className="cu-tab-bar-start" style={{ display: maskStartShown ? '' : 'none' }}></div>
            <div className="cu-tab-bar-end" style={{ display: maskEndShown ? '' : 'none' }}></div>
          </>
        ) : null}
        <CuScrollView
          key={scrollerTmpKey}
          ref={scrollViewRef as never}
          scrollingX={scrollable}
          scrollingY={false}
          onScroll={({ scrollLeft }) => {
            if (scrollLeft > 0) {
              setMaskStartShown(true)
            } else {
              setMaskStartShown(false)
            }
            setMaskEndShown(!(contentW > 0 && scrollLeft >= contentW - wrapperW))
          }}
        >
          <div className="cu-tab-bar-list" style={{ width: `${contentW}px` }}>
            {items.map((item, index) => (
              <a
                key={item.name}
                ref={(el) => setItemRef(el, index)}
                className={`cu-tab-bar-item${currentName === item.name ? ' is-active' : ''}${
                  item.disabled ? ' is-disabled' : ''
                }${items.length > 5 && index === 0 ? ' more-than-five' : ''}`}
                onClick={() => {
                  if (item.disabled) {
                    return
                  }
                  onChange?.(item, index, currentIndex)
                  setCurrentName(item.name)
                  onInput?.(item.name)
                }}
              >
                {renderItem
                  ? renderItem({ item, items, index, currentName })
                  : item.label}
              </a>
            ))}
          </div>
          {hasInk ? (
            <span
              className={`cu-tab-bar-ink${currentTab && currentTab.disabled ? ' is-disabled' : ''}`}
              style={{
                width: `${inkWidth}px`,
                transform: `translateX(${inkPos}px)`,
              }}
            ></span>
          ) : null}
        </CuScrollView>
      </div>
    </nav>
  )
})
