// packages/vue/src/components/bill/Bill.vue
<template>
  <CuWaterMark class="cu-bill" :content="waterMark">
    <header class="cu-bill-header">
      <template v-if="!hasHeaderSlot">
        <h4 v-if="title" class="cu-bill-title" v-text="title"></h4>
        <div v-if="no" class="cu-bill-no">NO.{{ no }}</div>
      </template>
      <template v-else>
        <slot name="header"></slot>
      </template>
    </header>
    <div class="cu-bill-neck">
      <span></span>
    </div>
    <div class="cu-bill-content">
      <div class="cu-bill-detail">
        <slot></slot>
      </div>
      <footer v-if="hasFooterSlot" class="cu-bill-footer">
        <slot name="footer"></slot>
      </footer>
    </div>
    <template v-if="hasWatermarkSlot" #watermark="{ coord }">
      <slot name="watermark" :coord="coord"></slot>
    </template>
  </CuWaterMark>
</template>

<script setup lang="ts">
import { computed, useSlots, Comment, Fragment } from 'vue'
import CuWaterMark from '../water-mark/WaterMark.vue'

defineOptions({ name: 'cu-bill' })

const props = withDefaults(
  defineProps<{
    title?: string
    no?: string | number
    waterMark?: string
  }>(),
  { title: '', no: '', waterMark: '' },
)

const slots = useSlots()

function slotHasContent(name: 'header' | 'footer' | 'watermark'): boolean {
  const fn = slots[name]
  if (!fn) {
    return false
  }
  const args = name === 'watermark' ? [{ coord: { row: 1, col: 1 } }] : []
  return fn(...(args as never[])).some((node) => {
    if (!node || typeof node !== 'object') {
      return false
    }
    const n = node as { type: unknown; children?: unknown }
    if (n.type === Comment) {
      return false
    }
    if (n.type === Fragment) {
      const children = n.children as unknown[]
      return Array.isArray(children) && children.length > 0
    }
    return true
  })
}

const hasHeaderSlot = computed(() => slotHasContent('header'))
const hasFooterSlot = computed(() => slotHasContent('footer'))
const hasWatermarkSlot = computed(() => slotHasContent('watermark'))
</script>

// packages/react/src/components/bill/Bill.tsx
import { forwardRef, type ReactNode } from 'react'
import { CuWaterMark } from '../water-mark/WaterMark'

export interface BillProps {
  title?: string
  no?: string | number
  waterMark?: string
  /** 水印插槽（作用于 WaterMark 平铺） */
  watermark?: ReactNode
  header?: ReactNode
  footer?: ReactNode
  children?: ReactNode
}

export const CuBill = forwardRef<HTMLDivElement, BillProps>(function CuBill(
  { title = '', no = '', waterMark = '', watermark, header, footer, children },
  ref,
) {
  void ref
  return (
    <CuWaterMark
      className="cu-bill"
      content={waterMark}
      renderWatermark={watermark ? () => watermark : undefined}
    >
      <header className="cu-bill-header">
        {header ?? (
          <>
            {title ? <h4 className="cu-bill-title">{title}</h4> : null}
            {no ? <div className="cu-bill-no">NO.{no}</div> : null}
          </>
        )}
      </header>
      <div className="cu-bill-neck">
        <span></span>
      </div>
      <div className="cu-bill-content">
        <div className="cu-bill-detail">{children}</div>
        {footer ? <footer className="cu-bill-footer">{footer}</footer> : null}
      </div>
    </CuWaterMark>
  )
})
