// packages/vue/src/components/codebox/Codebox.vue
<template>
  <div ref="root" class="md-codebox-wrapper">
    <div
      class="md-codebox"
      :class="{
        'is-disabled': disabled,
        'is-justify': justify,
      }"
      @click="focus"
    >
      <template v-if="Number(maxlength) > 0">
        <span
          v-for="i in num"
          :key="i"
          :class="[
            'md-codebox-box',
            i === code.length + 1 && focused && 'is-active',
            code.charAt(i - 1) !== '' && 'is-filled',
            isErrorStyle && 'is-error',
          ]"
        >
          <template v-if="code.charAt(i - 1)">
            <template v-if="mask"><i class="md-codebox-dot"></i></template>
            <template v-else>{{ code.charAt(i - 1) }}</template>
          </template>
          <template v-if="i === code.length + 1 && focused">
            <i class="md-codebox-blink"></i>
          </template>
        </span>
      </template>
      <template v-else>
        <input
          v-if="mask"
          type="password"
          :maxlength="maxlength"
          :value="code"
          readonly
          disabled
          :class="['md-codebox-holder', focused && 'is-active']"
        />
        <input
          v-else
          :type="inputType"
          :maxlength="maxlength"
          :value="code"
          readonly
          disabled
          :class="['md-codebox-holder', focused && 'is-active']"
        />
      </template>
    </div>
    <slot></slot>
    <form v-show="system" action="" @submit="onSubmit">
      <input
        ref="input"
        :value="code"
        :type="inputType"
        :maxlength="maxlength"
        class="md-codebox-input"
        @input="onInputChange"
        @focus="nativeFocus"
        @blur="nativeBlur"
      />
    </form>
    <MdNumberKeyboard
      v-show="!system"
      ref="keyboard"
      class="md-codebox-keyboard"
      :type="Number(maxlength) > 0 ? 'simple' : 'professional'"
      :ok-text="okText"
      :disorder="disorder"
      :is-view="isView"
      :model-value="focused"
      @update:model-value="(val) => (focused = val)"
      @delete="onDelete"
      @enter="onEnter"
      @confirm="onConfirm"
    ></MdNumberKeyboard>
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch, nextTick } from 'vue'
import MdNumberKeyboard from '../number-keyboard/NumberKeyboard.vue'

defineOptions({ name: 'md-codebox' })

const props = withDefaults(
  defineProps<{
    modelValue?: string
    maxlength?: number | string
    autofocus?: boolean
    disabled?: boolean
    justify?: boolean
    mask?: boolean
    closable?: boolean
    /** 使用系统键盘 */
    system?: boolean
    okText?: string
    disorder?: boolean
    isView?: boolean
    inputType?: string
    isErrorStyle?: boolean
  }>(),
  {
    modelValue: '',
    maxlength: 4,
    autofocus: false,
    disabled: false,
    justify: false,
    mask: false,
    closable: true,
    system: false,
    okText: undefined,
    disorder: false,
    isView: false,
    inputType: 'tel',
    isErrorStyle: false,
  },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
  (e: 'submit', code: string): void
  (e: 'focus'): void
  (e: 'blur'): void
}>()

const root = ref<HTMLElement>()
const input = ref<HTMLInputElement>()
const keyboard = ref<InstanceType<typeof MdNumberKeyboard>>()

const code = ref('')
const focused = ref(props.autofocus)

const num = computed(() => Math.abs(parseInt(String(props.maxlength), 10)) || 1)
const maxLengthNum = computed(() => Number(props.maxlength))

watch(
  () => props.modelValue,
  (val) => {
    if (val !== code.value) {
      code.value = val
    }
  },
  { immediate: true },
)

onMounted(() => {
  if (props.closable) {
    document.addEventListener('click', handleOutClick)
  }
  if (!props.system && !props.isView && keyboard.value?.$el) {
    document.body.appendChild(keyboard.value.$el)
  }
})

onBeforeUnmount(() => {
  if (props.closable) {
    document.removeEventListener('click', handleOutClick)
  }
  if (focused.value) {
    blur()
  }
  if (!props.system && !props.isView && keyboard.value?.$el && keyboard.value.$el.parentNode) {
    keyboard.value.$el.parentNode.removeChild(keyboard.value.$el)
  }
})

function handleOutClick(e: MouseEvent) {
  if (root.value && !root.value.contains(e.target as Node)) {
    focused.value = false
  }
}

function onInputChange(e: Event) {
  const value = (e.target as HTMLInputElement).value
  if (maxLengthNum.value < 0 || value.length <= maxLengthNum.value) {
    code.value = value
  }

  if (code.value.length === maxLengthNum.value) {
    emit('submit', code.value)
  }

  emit('update:modelValue', code.value)
}

function onSubmit(e: Event) {
  e.preventDefault()
  emit('submit', code.value)
}

function onEnter(val: string | number) {
  if ((maxLengthNum.value < 0 || code.value.length < maxLengthNum.value) && val !== '.') {
    code.value += val
  }

  if (code.value.length === maxLengthNum.value) {
    nextTick(() => {
      emit('submit', code.value)
    })
  }

  emit('update:modelValue', code.value)
}

function onDelete() {
  code.value = code.value.slice(0, code.value.length - 1)
  emit('update:modelValue', code.value)
}

function onConfirm() {
  emit('submit', code.value)
}

function blur() {
  focused.value = false
  if (props.system) {
    input.value?.blur()
  }
}

function focus() {
  if (props.disabled) {
    return
  }

  focused.value = true
  if (props.system) {
    input.value?.focus()
  }
}

function nativeBlur() {
  emit('blur')
}

function nativeFocus() {
  emit('focus')
}

defineExpose({ focus, blur })
</script>

// packages/react/src/components/codebox/Codebox.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  type ReactNode,
} from 'react'
import { MdNumberKeyboard, type NumberKeyboardExposed } from '../number-keyboard/NumberKeyboard'

export interface CodeboxProps {
  value?: string
  maxlength?: number | string
  autofocus?: boolean
  disabled?: boolean
  justify?: boolean
  mask?: boolean
  closable?: boolean
  /** 使用系统键盘 */
  system?: boolean
  okText?: string
  disorder?: boolean
  isView?: boolean
  inputType?: string
  isErrorStyle?: boolean
  children?: ReactNode
  onChange?: (value: string) => void
  onSubmit?: (code: string) => void
  onFocus?: () => void
  onBlur?: () => void
}

export interface CodeboxExposed {
  focus: () => void
  blur: () => void
}

export const MdCodebox = forwardRef<CodeboxExposed, CodeboxProps>(function MdCodebox(
  {
    value = '',
    maxlength = 4,
    autofocus = false,
    disabled = false,
    justify = false,
    mask = false,
    closable = true,
    system = false,
    okText,
    disorder = false,
    isView = false,
    inputType = 'tel',
    isErrorStyle = false,
    children,
    onChange,
    onSubmit,
    onFocus,
    onBlur,
  }: CodeboxProps,
  ref,
) {
  const rootRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLInputElement>(null)
  const keyboardRef = useRef<NumberKeyboardExposed | null>(null)

  // v2 watch immediate 契约：初始渲染即持 value
  const [code, setCode] = useState(value)
  const [focused, setFocused] = useState(autofocus)
  const codeRef = useRef(code)
  codeRef.current = code
  const focusedRef = useRef(focused)
  focusedRef.current = focused

  const maxLengthNum = Number(maxlength)
  const num = Math.abs(parseInt(String(maxlength), 10)) || 1

  // 外部 value 同步（v2 watch 契约）
  useEffect(() => {
    if (value !== codeRef.current) {
      setCode(value)
    }
  }, [value])

  useEffect(() => {
    if (closable) {
      const handler = (e: MouseEvent) => {
        if (rootRef.current && !rootRef.current.contains(e.target as Node)) {
          setFocused(false)
        }
      }
      document.addEventListener('click', handler)
      return () => document.removeEventListener('click', handler)
    }
  }, [closable])

  // 非系统键盘挂载到 body（v2 契约）
  useEffect(() => {
    const keyboard = keyboardRef.current
    if (!system && !isView && keyboard?.$el) {
      document.body.appendChild(keyboard.$el)
      return () => {
        keyboard.$el?.parentNode?.removeChild(keyboard.$el)
      }
    }
  }, [system, isView])

  useImperativeHandle(ref, () => ({
    focus: () => {
      if (disabled) {
        return
      }
      setFocused(true)
      if (system) {
        inputRef.current?.focus()
      }
    },
    blur: () => {
      setFocused(false)
      if (system) {
        inputRef.current?.blur()
      }
    },
  }))

  const emitChange = (next: string) => {
    setCode(next)
    onChange?.(next)
  }

  const onKeyboardEnter = (val: string | number) => {
    const current = codeRef.current
    if ((maxLengthNum < 0 || current.length < maxLengthNum) && val !== '.') {
      const next = current + val
      if (next.length === maxLengthNum) {
        setTimeout(() => onSubmit?.(next), 0)
      }
      emitChange(next)
    }
  }

  const onKeyboardDelete = () => {
    emitChange(codeRef.current.slice(0, codeRef.current.length - 1))
  }

  const onKeyboardConfirm = () => {
    onSubmit?.(codeRef.current)
  }

  const onNativeInput = (event: React.FormEvent<HTMLInputElement>) => {
    const inputValue = (event.target as HTMLInputElement).value
    if (maxLengthNum < 0 || inputValue.length <= maxLengthNum) {
      if (inputValue.length === maxLengthNum) {
        onSubmit?.(inputValue)
      }
      emitChange(inputValue)
    }
  }

  const boxes = []
  for (let i = 1; i <= num; i++) {
    const isActive = i === code.length + 1 && focused
    const isFilled = code.charAt(i - 1) !== ''
    boxes.push(
      <span
        key={i}
        className={[
          'md-codebox-box',
          isActive ? 'is-active' : '',
          isFilled ? 'is-filled' : '',
          isErrorStyle ? 'is-error' : '',
        ]
          .filter(Boolean)
          .join(' ')}
      >
        {code.charAt(i - 1) ? (
          mask ? <i className="md-codebox-dot" /> : code.charAt(i - 1)
        ) : null}
        {i === code.length + 1 && focused ? <i className="md-codebox-blink" /> : null}
      </span>,
    )
  }

  return (
    <div ref={rootRef} className="md-codebox-wrapper">
      <div
        className={`md-codebox${disabled ? ' is-disabled' : ''}${justify ? ' is-justify' : ''}`}
        onClick={() => {
          if (!disabled) {
            setFocused(true)
            if (system) {
              inputRef.current?.focus()
              onFocus?.()
            }
          }
        }}
      >
        {maxLengthNum > 0 ? (
          boxes
        ) : (
          <input
            type={mask ? 'password' : inputType}
            maxLength={maxLengthNum}
            value={code}
            readOnly
            disabled
            className={`md-codebox-holder${focused ? ' is-active' : ''}`}
          />
        )}
      </div>
      {children}
      <form
        action=""
        style={{ display: system ? undefined : 'none' }}
        onSubmit={event => {
          event.preventDefault()
          onSubmit?.(codeRef.current)
        }}
      >
        <input
          ref={inputRef}
          value={code}
          type={inputType}
          maxLength={maxLengthNum}
          className="md-codebox-input"
          onInput={onNativeInput}
          onFocus={() => onFocus?.()}
          onBlur={() => {
            setFocused(false)
            onBlur?.()
          }}
        />
      </form>
      <MdNumberKeyboard
        ref={keyboardRef}
        style={{ display: !system ? undefined : 'none' }}
        className="md-codebox-keyboard"
        type={maxLengthNum > 0 ? 'simple' : 'professional'}
        okText={okText}
        disorder={disorder}
        isView={isView}
        value={focused}
        onChange={setFocused}
        onDelete={onKeyboardDelete}
        onEnter={onKeyboardEnter}
        onConfirm={onKeyboardConfirm}
      />
    </div>
  )
})
