// packages/react/src/components/tabs/Tabs.tsx
import {
  useEffect,
  useRef,
  useState,
  forwardRef,
  useImperativeHandle,
  type ReactNode,
} from 'react'
import { CuTabBar, type TabBarItem, type TabBarExposed } from './TabBar'
import type { TabPaneRegistration } from './TabPane'
import { TabsContext, type TabsContextValue } from './context'

export interface TabsProps {
  value?: string
  hasInk?: boolean
  inkLength?: number
  immediate?: boolean
  children?: ReactNode
  onChange?: (tab: TabBarItem) => void
}

export interface TabsExposed {
  reflowTabBar: () => void
}

export const CuTabs = forwardRef<TabsExposed, TabsProps>(function CuTabs(
  { value, hasInk = true, inkLength = 25, immediate = false, children, onChange },
  ref,
) {
  const tabBarRef = useRef<TabBarExposed | null>(null)
  const [currentName, setCurrentName] = useState<string | undefined>(value)
  const [panes, setPanes] = useState<TabPaneRegistration[]>([])
  const prevIndex = useRef(0)
  const panesRef = useRef(panes)
  panesRef.current = panes
  const currentNameRef = useRef(currentName)
  currentNameRef.current = currentName

  const menus = panes.map((pane) => ({
    name: pane.name as string,
    label: pane.label as string,
    disabled: pane.disabled as boolean,
  }))
  const currentIndex = menus.findIndex((menu) => menu.name === currentName) >= 0
    ? menus.findIndex((menu) => menu.name === currentName)
    : 0

  // v2 watch value
  useEffect(() => {
    if (value !== undefined && value !== currentName) {
      setCurrentName(value)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value])

  // v2 mounted：未指定时默认选中首个 pane
  useEffect(() => {
    if (!currentNameRef.current && menus.length) {
      setCurrentName(menus[0].name)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [panes.length])

  const ctx: TabsContextValue = {
    registerPane: (pane) => {
      setPanes((prev) => {
        if (prev.some((p) => p.name === pane.name)) {
          return prev
        }
        return [...prev, pane]
      })
    },
    unregisterPane: (pane) => {
      setPanes((prev) => prev.filter((p) => p.name !== pane.name))
    },
    getState: () => ({
      currentName: currentNameRef.current,
      prevIndex: prevIndex.current,
      currentIndex,
    }),
  }

  useImperativeHandle(ref, () => ({
    reflowTabBar: () => tabBarRef.current?.reflow(),
  }))

  return (
    <TabsContext.Provider value={ctx}>
      <div className="cu-tabs">
        <CuTabBar
          ref={tabBarRef}
          items={menus}
          value={currentName}
          hasInk={hasInk}
          inkLength={inkLength}
          immediate={immediate}
          onChange={(tab, _index, prev) => {
            prevIndex.current = prev
            setCurrentName(tab.name as string)
            onChange?.(tab)
          }}
        />
        <div className="cu-tabs-content">{children}</div>
      </div>
    </TabsContext.Provider>
  )
})

// packages/vue/src/components/tabs/Tabs.vue
<template>
  <div class="cu-tabs">
    <CuTabBar
      ref="tabBar"
      :items="menus"
      :value="currentName"
      :has-ink="hasInk"
      :ink-length="inkLength"
      :immediate="immediate"
      @change="handleTabClick"
      @input="currentName = $event"
    />
    <div class="cu-tabs-content">
      <slot></slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, provide, ref, watch } from 'vue'
import CuTabBar, { type TabBarItem } from './TabBar.vue'
import type { ComponentInternalInstance } from 'vue'

defineOptions({ name: 'cu-tabs' })

const props = withDefaults(
  defineProps<{
    modelValue?: string
    hasInk?: boolean
    inkLength?: number
    immediate?: boolean
  }>(),
  { modelValue: undefined, hasInk: true, inkLength: 25, immediate: false },
)

const emit = defineEmits<{
  (e: 'update:modelValue', name: string): void
  (e: 'change', tab: TabBarItem): void
}>()

const tabBar = ref<InstanceType<typeof CuTabBar> | null>(null)
const currentName = ref<string | number | undefined>(props.modelValue)
const prevIndex = ref(0)
const panes = ref<Array<ComponentInternalInstance['proxy']>>([])

const menus = computed(() =>
  panes.value.map(pane => ({
    name: (pane as { name?: string }).name as string,
    label: (pane as { label?: string }).label as string,
    disabled: (pane as { disabled?: boolean }).disabled as boolean,
  })),
)
const currentIndex = computed(() => {
  for (let i = 0, len = menus.value.length; i < len; i++) {
    if (menus.value[i].name === currentName.value) {
      return i
    }
  }
  return 0
})

provide('rootTabs', {
  get currentName() {
    return currentName.value
  },
  get prevIndex() {
    return prevIndex.value
  },
  get currentIndex() {
    return currentIndex.value
  },
  addPane(pane: ComponentInternalInstance['proxy']) {
    if (panes.value.indexOf(pane) === -1) {
      panes.value.push(pane)
    }
  },
  removePane(pane: ComponentInternalInstance['proxy']) {
    const index = panes.value.indexOf(pane)
    if (index >= 0) {
      panes.value.splice(index, 1)
    }
  },
  forceUpdate() {
    // label/disabled 变化触发响应式更新（v2 $forceUpdate 等价）
    panes.value = [...panes.value]
  },
})

watch(
  () => props.modelValue,
  (val) => {
    if (val !== currentName.value) {
      currentName.value = val
    }
  },
)

onMounted(() => {
  if (!currentName.value && menus.value.length) {
    currentName.value = menus.value[0].name
  }
})

function handleTabClick(tab: TabBarItem, _index: number, prev: number) {
  currentName.value = tab.name as string
  prevIndex.value = prev
  emit('update:modelValue', tab.name as string)
  emit('change', tab)
}

function reflowTabBar() {
  tabBar.value?.reflow()
}

defineExpose({ reflowTabBar })
</script>
