// packages/vue/src/components/popup/PopupTitleBar.vue
<template>
  <div
    class="cu-popup-title-bar"
    :class="[
      `title-align-${titleAlign}`,
      {
        large: !!describe,
        'large-radius': largeRadius,
      },
    ]"
    @touchmove="preventScroll"
  >
    <!-- Cancel -->
    <template v-if="!onlyClose">
      <div
        v-if="cancelText"
        class="title-bar-left cu-popup-cancel"
        v-html="cancelText"
        @click="emit('cancel')"
      ></div>
      <div v-else-if="$slots.cancel" class="title-bar-left cu-popup-cancel" @click="emit('cancel')">
        <slot name="cancel"></slot>
      </div>
    </template>

    <!-- Title -->
    <div v-if="title" class="title-bar-title">
      <p v-if="title" class="title" v-html="title"></p>
      <p v-if="describe" class="describe" v-html="describe"></p>
    </div>
    <div v-else class="title-bar-title">
      <slot name="title"></slot>
    </div>

    <!-- Ok -->
    <template v-if="!onlyClose">
      <div
        v-if="okText"
        class="title-bar-right cu-popup-confirm"
        v-html="okText"
        @click="emit('confirm')"
      ></div>
      <div
        v-else-if="$slots.confirm"
        class="title-bar-right cu-popup-confirm"
        @click="emit('confirm')"
      >
        <slot name="confirm"></slot>
      </div>
    </template>
    <template v-if="onlyClose">
      <div class="title-bar-right cu-popup-close" @click="emit('cancel')">
        <CuIcon name="close" size="lg"></CuIcon>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { inject, watch, type Ref } from 'vue'
import CuIcon from '../icon/Icon.vue'

defineOptions({ name: 'cu-popup-title-bar' })

const props = withDefaults(
  defineProps<{
    title?: string
    describe?: string
    okText?: string
    cancelText?: string
    largeRadius?: boolean
    onlyClose?: boolean
    /** center | left | right */
    titleAlign?: string
  }>(),
  {
    title: '',
    describe: '',
    okText: '',
    cancelText: '',
    largeRadius: false,
    onlyClose: false,
    titleAlign: 'center',
  },
)

const emit = defineEmits<{
  (e: 'confirm'): void
  (e: 'cancel'): void
}>()

// v2 契约：title-bar 的 largeRadius 会同步到父级 Popup 的 large-radius 修饰类
const popupLargeRadius = inject<Ref<boolean> | null>('mdPopupLargeRadius', null)

watch(
  () => props.largeRadius,
  (val) => {
    if (popupLargeRadius) {
      popupLargeRadius.value = val
    }
  },
  { immediate: true },
)

function preventScroll(e: TouchEvent) {
  e.preventDefault()
}
</script>

// packages/react/src/components/popup/PopupTitleBar.tsx
import { useContext, useEffect, type ReactNode } from 'react'
import { CuIcon } from '../icon/Icon'
import { PopupContext } from './Popup'

export interface PopupTitleBarProps {
  title?: string
  describe?: string
  okText?: string
  cancelText?: string
  largeRadius?: boolean
  onlyClose?: boolean
  /** center | left | right */
  titleAlign?: string
  onConfirm?: () => void
  onCancel?: () => void
  cancelSlot?: ReactNode
  confirmSlot?: ReactNode
  titleSlot?: ReactNode
}

export function CuPopupTitleBar({
  title = '',
  describe = '',
  okText = '',
  cancelText = '',
  largeRadius = false,
  onlyClose = false,
  titleAlign = 'center',
  onConfirm,
  onCancel,
  cancelSlot,
  confirmSlot,
  titleSlot,
}: PopupTitleBarProps) {
  // v2 契约：title-bar 的 largeRadius 同步到父级 Popup 修饰类
  const popup = useContext(PopupContext)
  useEffect(() => {
    popup.setLargeRadius(largeRadius)
  }, [largeRadius, popup])

  const preventTouch = (event: React.TouchEvent) => event.preventDefault()

  return (
    <div
      className={`cu-popup-title-bar title-align-${titleAlign}${describe ? ' large' : ''}${
        largeRadius ? ' large-radius' : ''
      }`}
      onTouchMove={preventTouch}
    >
      {!onlyClose ? (
        <>
          {cancelText ? (
            <div
              className="title-bar-left cu-popup-cancel"
              dangerouslySetInnerHTML={{ __html: cancelText }}
              onClick={() => onCancel?.()}
            ></div>
          ) : cancelSlot ? (
            <div className="title-bar-left cu-popup-cancel" onClick={() => onCancel?.()}>
              {cancelSlot}
            </div>
          ) : null}
        </>
      ) : null}

      {title ? (
        <div className="title-bar-title">
          <p className="title" dangerouslySetInnerHTML={{ __html: title }}></p>
          {describe ? (
            <p className="describe" dangerouslySetInnerHTML={{ __html: describe }}></p>
          ) : null}
        </div>
      ) : (
        <div className="title-bar-title">{titleSlot}</div>
      )}

      {!onlyClose ? (
        <>
          {okText ? (
            <div
              className="title-bar-right cu-popup-confirm"
              dangerouslySetInnerHTML={{ __html: okText }}
              onClick={() => onConfirm?.()}
            ></div>
          ) : confirmSlot ? (
            <div className="title-bar-right cu-popup-confirm" onClick={() => onConfirm?.()}>
              {confirmSlot}
            </div>
          ) : null}
        </>
      ) : null}
      {onlyClose ? (
        <div className="title-bar-right cu-popup-close" onClick={() => onCancel?.()}>
          <CuIcon name="close" size="lg" />
        </div>
      ) : null}
    </div>
  )
}
