// docs/src/components/demos-react/check-base/index.tsx
import { useState } from 'react'
import { MdCheckBox, MdRadioBox } from 'mand-mobile-react'
import DemoCanvasReact from '../../DemoCanvasReact'

const scenes = ['复选盒', '单选盒']
const code = `<MdCheckBox v-model="checked" name="a" label="选项" />`

export default function CheckBaseDemo() {
  const [checked, setChecked] = useState<string | number | boolean>('a')
  const [radio, setRadio] = useState<string | number | boolean>('a')
  return (
    <DemoCanvasReact mode="stage" scenes={scenes} code={code}>
      {active =>
        active === 0 ? (
          <div style={{ display: 'flex', gap: 12 }}>
            <MdCheckBox name="a" value={checked} label="选项一" onChange={setChecked} />
            <MdCheckBox name="b" value={checked} label="选项二" onChange={setChecked} />
          </div>
        ) : (
          <div style={{ display: 'flex', gap: 12 }}>
            <MdRadioBox name="a" value={radio} label="选项一" onChange={setRadio} />
            <MdRadioBox name="b" value={radio} label="选项二" onChange={setRadio} />
          </div>
        )
      }
    </DemoCanvasReact>
  )
}

// docs/src/components/demos/check-base/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { MdCheckBox, MdRadio } from 'mand-mobile'
import DemoCanvas from '../../DemoCanvas.vue'

const scenes = ['复选框', '单选框', '禁用']
const checked = ref(true)
const unchecked = ref(false)
const radioVal = ref('A')
const code = `<MdCheckBox v-model="checked" label="默认选中" />
<MdCheckBox v-model="unchecked" label="默认未选" />
<MdRadio v-model="radioVal" name="A" label="选项 A" />`
</script>

<template>
  <DemoCanvas mode="stage" :scenes="scenes" :code="code">
    <template #scene-0>
      <div class="ck-row"><MdCheckBox v-model="checked" label="默认选中" /></div>
      <div class="ck-row"><MdCheckBox v-model="unchecked" label="默认未选" /></div>
    </template>
    <template #scene-1>
      <div class="ck-row"><MdRadio v-model="radioVal" name="A" label="选项 A" /></div>
      <div class="ck-row"><MdRadio v-model="radioVal" name="B" label="选项 B" /></div>
      <div class="ck-row ck-note">当前选中：{{ radioVal }}</div>
    </template>
    <template #scene-2>
      <div class="ck-row"><MdCheckBox v-model="unchecked" label="禁用未选" disabled /></div>
      <div class="ck-row"><MdCheckBox v-model="checked" label="禁用已选" disabled /></div>
    </template>
  </DemoCanvas>
</template>

<style scoped>
.ck-row {
  padding: 12px 14px;
  font-size: 14px;
  color: #333;
}
.ck-note {
  color: #999;
  font-size: 12px;
}
</style>
