// packages/react/src/components/amount/Amount.tsx
import { useEffect, useRef, useState } from 'react'
import { formatNumberWithSeparator, numberToChineseCapital, toFixedPrecision } from '@mand-mobile/core'
import { Animate } from '@mand-mobile/core/web'

export interface AmountProps {
  value?: number
  precision?: number
  isRoundUp?: boolean
  hasSeparator?: boolean
  separator?: string
  isAnimated?: boolean
  /** v2 遗留别名，等价于 isAnimated 的过渡开关 */
  transition?: boolean
  isCapital?: boolean
  duration?: number
}

const inBrowser = typeof window !== 'undefined'

export function MdAmount({
  value = 0,
  precision = 2,
  isRoundUp = true,
  hasSeparator = false,
  separator = ',',
  isAnimated = false,
  transition = false,
  isCapital = false,
  duration = 1000,
}: AmountProps) {
  // v2 watch immediate 契约：初始渲染即持 value
  const [displayValue, setDisplayValue] = useState(value)
  const isMounted = useRef(false)
  const animateRef = useRef<{ from: number; to: number } | null>(null)

  const legalPrecision = precision > 0 ? precision : 0

  // v2 契约：value 变化时非动画直接赋值，动画模式经 rAF 过渡收敛
  useEffect(() => {
    if (!inBrowser && !isMounted.current) {
      setDisplayValue(value)
      return
    }
    if (isAnimated || transition) {
      animateRef.current = { from: displayValue, to: value }
      Animate.start(percent => {
        const anim = animateRef.current
        if (!anim) {
          return
        }
        if (percent === 1) {
          setDisplayValue(anim.to)
          return
        }
        setDisplayValue(anim.from + (anim.to - anim.from) * percent)
      }, () => true, () => {}, duration)
    } else {
      setDisplayValue(value)
    }
  }, [value])

  useEffect(() => {
    isMounted.current = true
  }, [])

  const formatted = toFixedPrecision(displayValue, legalPrecision, isRoundUp)
  const text = isCapital
    ? numberToChineseCapital(toFixedPrecision(displayValue, 4, isRoundUp))
    : hasSeparator
      ? formatNumberWithSeparator(formatted, separator)
      : formatted

  return (
    <span className={`md-amount${isCapital ? '' : ' numerical'}`}>
      {isCapital ? ` ${text} ` : text}
    </span>
  )
}

// packages/vue/src/components/amount/Amount.vue
<template>
  <span class="md-amount" :class="{ numerical: !isCapital }">
    <template v-if="!isCapital">{{ nonCapital }}</template>
    <template v-else>{{ capital }}</template>
  </span>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import {
  formatNumberWithSeparator,
  numberToChineseCapital,
  toFixedPrecision,
} from '@mand-mobile/core'
import { Animate } from '@mand-mobile/core/web'

defineOptions({ name: 'md-amount' })

const props = withDefaults(
  defineProps<{
    value?: number
    precision?: number
    isRoundUp?: boolean
    hasSeparator?: boolean
    separator?: string
    isAnimated?: boolean
    /** v2 遗留别名，等价于 isAnimated 的过渡开关 */
    transition?: boolean
    isCapital?: boolean
    duration?: number
  }>(),
  {
    value: 0,
    precision: 2,
    isRoundUp: true,
    hasSeparator: false,
    separator: ',',
    isAnimated: false,
    transition: false,
    isCapital: false,
    duration: 1000,
  },
)

const inBrowser = typeof window !== 'undefined'

const displayValue = ref(0)
const isMounted = ref(false)

const legalPrecision = computed(() => (props.precision > 0 ? props.precision : 0))

const nonCapital = computed(() => {
  const formatted = toFixedPrecision(displayValue.value, legalPrecision.value, props.isRoundUp)
  return props.hasSeparator ? formatNumberWithSeparator(formatted, props.separator) : formatted
})

const capital = computed(() =>
  numberToChineseCapital(toFixedPrecision(displayValue.value, 4, props.isRoundUp)),
)

watch(
  () => props.value,
  (val, oldVal) => {
    if (!inBrowser && !isMounted.value) {
      displayValue.value = val
      return
    }
    if (props.isAnimated || props.transition) {
      animateDisplay(oldVal, val)
    } else {
      displayValue.value = val
    }
  },
  { immediate: true },
)

onMounted(() => {
  isMounted.value = true
})

function animateDisplay(fromValue = 0, toValue = 0) {
  const step = (percent: number) => {
    if (percent === 1) {
      displayValue.value = toValue
      return
    }
    displayValue.value = fromValue + (toValue - fromValue) * percent
  }
  const verify = () => true
  Animate.start(step, verify, () => {}, props.duration)
}
</script>
