// packages/vue/src/components/tab-picker/TabPicker.vue
<template>
  <div class="cu-tab-picker">
    <CuPopup
      :model-value="modelValue"
      position="bottom"
      :mask-closable="maskClosable"
      @update:model-value="onPopupInput"
      @show="onPopupShow"
      @hide="$emit('hide')"
      @mask-click="onCancel"
    >
      <CuPopupTitleBar
        :title="title"
        :describe="describe"
        :large-radius="largeRadius"
        only-close
        @cancel="onCancel"
      >
        <template #cancel>
          <CuIcon name="close" size="lg" />
        </template>
      </CuPopupTitleBar>
      <div class="cu-tab-picker-content">
        <CuTabs ref="tabs" :model-value="currentTab" :key="tabsTmpKey" :ink-length="100">
          <CuScrollView ref="scrollView" :scrolling-x="false" auto-reflow>
            <CuTabPane v-for="(pane, index) in panes" :key="pane.name" :name="pane.name" :label="pane.label">
              <CuRadioList
                :model-value="pane.value"
                :options="pane.options"
                :is-slot-scope="hasSlot"
                icon=""
                icon-inverse=""
                icon-position="right"
                @update:model-value="onSelectPaneItem($event, index)"
              >
                <template v-if="hasSlot" #default="{ option }">
                  <slot :option="option"></slot>
                </template>
              </CuRadioList>
            </CuTabPane>
          </CuScrollView>
        </CuTabs>
      </div>
    </CuPopup>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, useSlots } from 'vue'
import { t } from '@centui/core'
import CuPopup from '../popup/Popup.vue'
import CuPopupTitleBar from '../popup/PopupTitleBar.vue'
import CuIcon from '../icon/Icon.vue'
import CuTabs from '../tabs/Tabs.vue'
import CuTabPane from '../tabs/TabPane.vue'
import CuScrollView from '../scroll-view/ScrollView.vue'
import CuRadioList from '../radio-list/RadioList.vue'
import type { RadioListOption } from '../radio-list/RadioList.vue'

defineOptions({ name: 'cu-tab-picker' })

export interface TabPickerOption {
  value?: string | number
  label?: string
  children?: TabPickerNode
}

export interface TabPickerNode {
  name?: string
  label?: string
  value?: string | number
  children?: TabPickerNode
  options?: TabPickerOption[]
}

const props = withDefaults(
  defineProps<{
    modelValue?: boolean
    data?: TabPickerNode
    defaultValue?: Array<string | number>
    placeholder?: string
    title?: string
    describe?: string
    maskClosable?: boolean
    largeRadius?: boolean
  }>(),
  {
    modelValue: false,
    data: () => ({}),
    defaultValue: () => [],
    placeholder: () => t('md.tab_picker.choose'),
    title: '',
    describe: '',
    maskClosable: true,
    largeRadius: false,
  },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
  (e: 'select', payload: { index: number; value: string | number | boolean | undefined; option: unknown }): void
  (e: 'change', payload: { values: Array<string | number>; options: Array<unknown> }): void
  (e: 'show'): void
  (e: 'hide'): void
}>()

const slots = useSlots()
const tabs = ref<InstanceType<typeof CuTabs> | null>(null)
const scrollView = ref<InstanceType<typeof CuScrollView> | null>(null)

const selected = ref<Array<string | number>>(props.defaultValue.slice())
const oldSelected = ref<Array<string | number>>([])
const currentTab = ref(props.data.name ?? '')
const oldCurrentTab = ref('')
const tabsTmpKey = ref(Date.now())

const hasSlot = computed(() => {
  const fn = slots.default
  if (!fn) {
    return false
  }
  return fn({ option: {} }).some((n) => n.type !== Comment)
})

const panes = computed(() => {
  const result: Array<{
    name?: string
    label?: string
    value: string | number | undefined
    selected: unknown
    options: RadioListOption[]
  }> = []
  let target: TabPickerNode | undefined = props.data
  let cursor = 0
  while (target && target.name) {
    const pane = {
      name: target.name,
      label: target.label || props.placeholder,
      value: selected.value[cursor],
      selected: null as unknown,
      options: (target.options ?? []) as unknown as RadioListOption[],
    }
    let find = false
    const options = (target.options ?? []) as Array<{ value?: string | number; label?: string; children?: TabPickerNode }>
    for (let i = 0, len = options.length; i < len; i++) {
      if (options[i].value === selected.value[cursor]) {
        pane.label = options[i].label as string
        pane.selected = options[i] as unknown as RadioListOption
        target = options[i].children
        find = true
        cursor++
        break
      }
    }
    if (!find) {
      target = undefined
    }
    result.push(pane)
    // v2 契约：pane 推进时同步选中对应 tab
    currentTab.value = pane.name
  }

  return result
})

// created 语义
if (props.data) {
  currentTab.value = props.data.name ?? ''
}

function onPopupInput(val: boolean) {
  emit('update:modelValue', val)
}

function onPopupShow() {
  tabs.value?.reflowTabBar()
  emit('show')
  setTimeout(() => {
    oldSelected.value = selected.value.slice()
    oldCurrentTab.value = currentTab.value
  }, 100)
}

function onCancel() {
  emit('update:modelValue', false)
  setTimeout(() => {
    selected.value = oldSelected.value.slice()
    currentTab.value = oldCurrentTab.value
    tabsTmpKey.value = Date.now()
  }, 100)
}

function onSelectPaneItem(value: string | number | boolean, index: number) {
  selected.value.splice(index, selected.value.length - index, value as string | number)
  // v2 契约：nextTick 后按新 panes 推进 tab / 触发 change
  Promise.resolve().then(() => {
    const nextPane = panes.value[index + 1]

    emit('select', {
      index,
      value,
      option: panes.value[index],
    })

    if (nextPane) {
      currentTab.value = nextPane.name as string
      scrollView.value?.scrollTo(0, 0)
    } else if (value !== '') {
      setTimeout(() => {
        emit('change', {
          values: getSelectedValues(),
          options: getSelectedOptions(),
        })
        emit('update:modelValue', false)
      }, 300)
    }
  })
}

function getSelectedValues() {
  return selected.value.slice()
}

function getSelectedOptions() {
  return panes.value.filter((pane) => pane.value).map((pane) => pane.selected)
}

defineExpose({ getSelectedValues, getSelectedOptions })
</script>

// packages/react/src/components/tab-picker/TabPicker.tsx
import { forwardRef, useEffect, useRef, useState, useImperativeHandle, type ReactNode } from 'react'
import { CuPopup } from '../popup/Popup'
import { CuPopupTitleBar } from '../popup/PopupTitleBar'
import { CuIcon } from '../icon/Icon'
import { CuTabs } from '../tabs/Tabs'
import { CuTabPane } from '../tabs/TabPane'
import { CuScrollView, type ScrollViewExposed } from '../scroll-view/ScrollView'
import { CuRadioList } from '../radio-list/RadioList'
import type { RadioListOption } from '../radio-list/RadioList'

export interface TabPickerOption {
  value?: string | number
  label?: string
  children?: TabPickerNode
}

export interface TabPickerNode {
  name?: string
  label?: string
  value?: string | number
  children?: TabPickerNode
  options?: TabPickerOption[]
}

export interface TabPickerProps {
  value?: boolean
  data?: TabPickerNode
  defaultValue?: Array<string | number>
  placeholder?: string
  title?: string
  describe?: string
  maskClosable?: boolean
  largeRadius?: boolean
  children?: (slotProps: { option: { value?: string | number; label?: string; text?: string } }) => ReactNode
  onSelect?: (payload: { index: number; value: string | number | boolean | undefined; option: unknown }) => void
  onChange?: (payload: { values: Array<string | number>; options: Array<unknown> }) => void
  /** 显隐状态变化（对齐 v2 input 事件） */
  onInput?: (value: boolean) => void
  onShow?: () => void
  onHide?: () => void
}

export interface TabPickerExposed {
  getSelectedValues: () => Array<string | number>
  getSelectedOptions: () => Array<unknown>
}

interface Pane {
  name?: string
  label?: string
  value: string | number | undefined
  selected: unknown
  options: Array<{ value?: string | number; label?: string }>
}

const CHOOSE_TEXT = '请选择'

export const CuTabPicker = forwardRef<TabPickerExposed, TabPickerProps>(function CuTabPicker(
  {
    value = false,
    data = {},
    defaultValue = [],
    placeholder = CHOOSE_TEXT,
    title = '',
    describe = '',
    maskClosable = true,
    largeRadius = false,
    children,
    onSelect,
    onChange,
    onInput,
    onShow,
    onHide,
  },
  ref,
) {
  const tabsRef = useRef<{ reflowTabBar: () => void } | null>(null)
  const scrollViewRef = useRef<ScrollViewExposed | null>(null)

  const [selected, setSelected] = useState<Array<string | number>>(defaultValue.slice())
  const oldSelectedRef = useRef<Array<string | number>>([])
  const [currentTab, setCurrentTab] = useState<string | undefined>(data.name)
  const oldCurrentTabRef = useRef<string | undefined>('')
  const [tabsTmpKey, setTabsTmpKey] = useState(() => Date.now())

  const hasSlot = !!children

  // v2 computed panes：由嵌套 data 与 selected 派生，推进 cursor 走 children
  const buildPanes = (sel: Array<string | number>): Pane[] => {
    const result: Pane[] = []
    let target: TabPickerNode | undefined = data
    let cursor = 0
    while (target && target.name) {
      const pane: Pane = {
        name: target.name,
        label: target.label || placeholder,
        value: sel[cursor],
        selected: null,
        options: (target.options ?? []) as Array<{ value?: string | number; label?: string }>,
      }
      let find = false
      const options = (target.options ?? []) as Array<{ value?: string | number; label?: string; children?: TabPickerNode }>
      for (let i = 0, len = options.length; i < len; i++) {
        if (options[i].value === sel[cursor]) {
          pane.label = options[i].label
          pane.selected = options[i]
          target = options[i].children
          find = true
          cursor++
          break
        }
      }
      if (!find) {
        target = undefined
      }
      result.push(pane)
    }
    return result
  }

  const panes = buildPanes(selected)
  // v2 契约：选中推进时同步选中对应 tab（取最后一个 pane）
  const panesRef = useRef(panes)
  panesRef.current = panes

  // v2 created
  useEffect(() => {
    if (data) {
      setCurrentTab(data.name)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function onPopupShow() {
    tabsRef.current?.reflowTabBar()
    onShow?.()
    setTimeout(() => {
      oldSelectedRef.current = selected.slice()
      oldCurrentTabRef.current = currentTab
    }, 100)
  }

  function onCancel() {
    onInput?.(false)
    setTimeout(() => {
      setSelected(oldSelectedRef.current.slice())
      setCurrentTab(oldCurrentTabRef.current)
      setTabsTmpKey(Date.now())
    }, 100)
  }

  const propsOnChangeRef = useRef(onChange)
  propsOnChangeRef.current = onChange
  const propsSelectRef = useRef(onSelect)
  propsSelectRef.current = onSelect
  const propsInputRef = useRef(onInput)
  propsInputRef.current = onInput

  function onSelectPaneItem(value: string | number | boolean | undefined, index: number) {
    setSelected((prev) => {
      const next = prev.slice(0, index)
      next[index] = value as string | number
      return next
    })
    // v2 nextTick 语义
    setTimeout(() => {
      const nextPanes = buildPanes(
        (() => {
          const next = selected.slice(0, index)
          next[index] = value as string | number
          return next
        })(),
      )
      propsSelectRef.current?.({
        index,
        value,
        option: nextPanes[index],
      })

      const nextPane = nextPanes[index + 1]
      if (nextPane) {
        setCurrentTab(nextPane.name)
        scrollViewRef.current?.scrollTo(0, 0)
      } else if (value !== '') {
        setTimeout(() => {
          const values = nextPanes.filter((p) => p.value).map((p) => p.value as string | number)
          const options = nextPanes.filter((p) => p.value).map((p) => p.selected)
          propsOnChangeRef.current?.({ values, options })
          propsInputRef.current?.(false)
        }, 300)
      }
    }, 0)
  }

  useImperativeHandle(ref, () => ({
    getSelectedValues: () => selected.slice(),
    getSelectedOptions: () => panes.filter((p) => p.value).map((p) => p.selected),
  }))

  return (
    <div className="cu-tab-picker">
      <CuPopup
        value={value}
        position="bottom"
        maskClosable={maskClosable}
        onShow={onPopupShow}
        onHide={onHide}
        onMaskClick={onCancel}
      >
        <CuPopupTitleBar
          title={title}
          describe={describe}
          largeRadius={largeRadius}
          onlyClose
          onCancel={onCancel}
          cancelSlot={<CuIcon name="close" size="lg" />}
        />
        <div className="cu-tab-picker-content">
          <CuTabs key={tabsTmpKey} value={currentTab} inkLength={100} ref={tabsRef as never}>
            <CuScrollView ref={scrollViewRef} scrollingX={false} autoReflow>
              {panes.map((pane, index) => (
                <CuTabPane key={pane.name} name={pane.name} label={pane.label}>
                  <CuRadioList
                    value={pane.value}
                    options={pane.options as never}
                    isSlotScope={hasSlot}
                    icon=""
                    iconInverse=""
                    iconPosition="right"
                    onChangeValue={(v) => onSelectPaneItem(v, index)}
                    children={
                      children
                        ? (slotProps: { option: RadioListOption; index: number; selected: boolean }) =>
                            children({ option: slotProps.option as { value?: string | number; label?: string; text?: string } })
                        : undefined
                    }
                  />
                </CuTabPane>
              ))}
            </CuScrollView>
          </CuTabs>
        </div>
      </CuPopup>
    </div>
  )
})
